### ISSUE TITLE
Cannot build for Android

### ISSUE THREAD

**Issue by wesson818** [xu-li/cordova-plugin-wechat#1]
Hi xu-li,

Great plugin! But when I try to build for Android, build Failed.

The step I installed it is:
1. Install your plugin: cordova plugin add https://github.com/xu-li/cordova-plugin-wechat
2. Add wechat lib(libammsdk.jar) to libs under project. 
3. cordova build android.

And then BUILD FAILED.
I also add preference name="wechatappid" value="YOUR_WECHAT_APP_ID" to config.xml.

Do I missed some steps? Could you help me with this?

Many thanks!

Wesson

**Comment by zilinxueyue** [comment]
Hi,I following the same steps. auth success but share nothing happen. Would you please help to check any issue in my code.
  Wechat.isInstalled(function (installed) {
                    WEIXININSTALL=installed;
                });

                /***************微信登录**************/
   
                Wechat.auth("snsapi_userinfo", function (response) {
                    // you may use response.code to get the access token.
                    alert(JSON.stringify(response));
                }, function (reason) {
                    alert("Failed: " + reason);
                });

        
                Wechat.share({
                    message: {
                        title: "分享",
                        description: "描述",
                        mediaTagName: "分享",
                        thumb: "分享的时候的图片链接",
                        media: {
                            type: Wechat.Type.WEBPAGE, //类型是一个webpage，就是一个网页？
                            webpageUrl: "www.baidu.com"
                        }
                    },
                    scene: Wechat.Scene.TIMELINE   // 分享到朋友圈

                }, function () {
                    alert("分享成功");
                }, function (reason) {
                    alert("分享失败"+reason);
            });
Thanks so much

**Comment by xu-li** [comment]
thumb 不是文字，是图片链接。webpageUrl改成http://www.baidu.com。

On Thu, May 19, 2016 at 3:28 PM, zilinxueyue <notifications@github.com>
wrote:

> Hi,I following the same steps. auth success but share nothing happen.
> Would you please help to check any issue in my code.
> Wechat.isInstalled(function (installed) {
> WEIXININSTALL=installed;
> });
>
>             /***************微信登录**************/
>
>             Wechat.auth("snsapi_userinfo", function (response) {
>                 // you may use response.code to get the access token.
>                 alert(JSON.stringify(response));
>             }, function (reason) {
>                 alert("Failed: " + reason);
>             });
>
>
>             Wechat.share({
>                 message: {
>                     title: "分享",
>                     description: "描述",
>                     mediaTagName: "分享",
>                     thumb: "分享的时候的图片链接",
>                     media: {
>                         type: Wechat.Type.WEBPAGE, //类型是一个webpage，就是一个网页？
>                         webpageUrl: "www.baidu.com"
>                     }
>                 },
>                 scene: Wechat.Scene.TIMELINE   // 分享到朋友圈
>
>             }, function () {
>                 alert("分享成功");
>             }, function (reason) {
>                 alert("分享失败"+reason);
>         });
>
> Thanks so much
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/xu-li/cordova-plugin-wechat/issues/1#issuecomment-220247991>
>



-- 
Thanks.
--
Xu Li,  Shanghai, China

**Comment by zilinxueyue** [comment]
Hi， xu-li
     我用了你的方法 打包release 版本后，第一次可以分享成功，但是第二次分享就没有响应了。我的退出微信登录，再次登录后，又可以分享一次，然后第二次又没有响应了。请问这个问题怎么解？
Thanks‘

**Comment by zilinxueyue** [comment]
@xu-li 
多谢你的分享，我试过了 现在可以用了。是2次分享要有时间间隔，过一会再分享就ok了。
Thanks
