### ISSUE TITLE
分享完会黑屏一秒钟左右

### ISSUE THREAD

**Issue by mkliu** [xu-li/cordova-plugin-wechat#10]
你有这个问题么？我在小米3上测试的，用的ionic

**Comment by xu-li** [comment]
Android用的是老版本的插件。还没更新新版本。不好意思。

**Comment by mkliu** [comment]
我换成新的版本了，sdk本身没问题，感觉是ionic的example app刷新问题

**Comment by mkliu** [comment]
哦，应该是因为分享完了返回的时候刷新了页面导致的。这体验相当不好啊，你的会刷新页面么？

**Comment by xu-li** [comment]
我的意思是，我的那个插件是老版本的。不确定是不是还能用。
而且最近准备写个新版本的给android。

对了，微信出了个[JS的SDK](http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html)，你可以试试那个先。

**Comment by mkliu** [comment]
没事儿，我找出问题了。那个js sdk我看了，说是 “基于微信内的网页开发工具包”，应该是针对公众号页面的

**Comment by mkliu** [comment]
对了，你一般怎么开发plugin？我现在在ionic project里面直接改plugin，然后再去改plugin的git repo。感觉有些麻烦。你怎么弄的？

**Comment by xu-li** [comment]
基本是这样的。感觉还行啊。
