### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by vee2046** [xu-li/cordova-plugin-wechat#100]
platforms\android\src\com\ionicframework\starter\wxapi\WXEntryActivity.java
从42行开始，err静态变量命错误
public void onResp(BaseResp resp)

BaseResp.ErrCode和Wechat的
改成这样就好了
@Override
    public void onResp(BaseResp resp) {
        Log.i(WXEntryActivity.class.getName(), resp.toString());
        switch (resp.errCode) {
            case BaseResp.ErrCode.ERR_OK:
                switch(resp.getType())
                {
                 case ConstantsAPI.COMMAND_SENDAUTH:
                    auth(resp);
                    break;
                 default:
                    Wechat.currentCallbackContext.success();
                    break;
                }
                break;
            case BaseResp.ErrCode.ERR_USER_CANCEL:
                Wechat.currentCallbackContext.error(Wechat.ERROR_USER_CANCEL);
                break;
            case BaseResp.ErrCode.ERR_AUTH_DENIED:
                Wechat.currentCallbackContext.error(Wechat.ERROR_AUTH_DENIED);
                break;
            case BaseResp.ErrCode.ERR_SENT_FAILED:
                Wechat.currentCallbackContext.error(Wechat.ERROR_SENT_FAILED);
                break;
            case BaseResp.ErrCode.ERR_UNSUPPORT:
                Wechat.currentCallbackContext.error(Wechat.ERROR_UNSUPPORT);
                break;
            case BaseResp.ErrCode.ERR_COMM:
                Wechat.currentCallbackContext.error(Wechat.ERROR_COMMON);
                break;
            default:
                Wechat.currentCallbackContext.error(Wechat.ERROR_UNKNOWN);
                break;
        }
        finish();
    }

**Comment by xu-li** [comment]
那个文件是空的啊。你用的是哪个版本的？
