### ISSUE TITLE
请问用此plugin登录的用户多久才能在开放平台的数据统计里看到？

### ISSUE THREAD

**Issue by bieyaqing** [xu-li/cordova-plugin-wechat#103]
我可以通过此plugin拿到登录用户的基本信息吗？

**Comment by xu-li** [comment]
不知道多久能看到，这个应该要问问微信官方。

可以拿到基本信息啊，登录以后有了access token就可以去获取基本信息了。

**Comment by bieyaqing** [comment]
好哒，谢谢～

**Comment by bieyaqing** [comment]
我查看了微信开放平台的 授权后接口调用（UnionID）。如果要拿到用户的基本信息需要 token 跟 openId。token已经拿到了，那openId如何获取？根据API，OpenID是在拿到token的时候同时返回的，请问这部分会加在 cordova-plugin-wechat？ 还是有别的办法？

**Comment by bieyaqing** [comment]
不好意思，之前看到那个code以为是token，其实只是交换token用的那个code。按照步骤还需要用code去换token，那个时候会有openId返回。之后就没有问题了。谢谢你的plugin。
