### ISSUE TITLE
demo失效，点击登陆没反应

### ISSUE THREAD

**Issue by mjbin** [xu-li/cordova-plugin-wechat#104]
大神，我用了你的demo，然后用的我的id和签名打包成的apk，可以检测到微信，但是发送文本闪现了一下返回了失败，微信授权登陆也没反应，在微信没登陆时候，是可以调出微信的登陆界面，可以确定id和签名没问题

**Comment by xu-li** [comment]
错误是什么？iOS还是android？日志里面有错误么？

**Comment by mjbin** [comment]
不好意思，再三确认了下，确实是签名错了，真是不好意思。。谢谢大大。。。
