### ISSUE TITLE
android oauth 會找不到網頁

### ISSUE THREAD

**Issue by KuanYu0729** [xu-li/cordova-plugin-wechat#105]
oauth後，會顯示找不到網頁
網址變成
[app id]://oauth?code=XXX&state=
這樣是對的嗎?
為什麼會找不到網頁??

**Comment by xu-li** [comment]
这个地址你是哪里得到的？

**Comment by KuanYu0729** [comment]
授權時登入帳號，WeChat自動幫我導過去的

**Comment by KuanYu0729** [comment]
另外找不到網頁後，success callback & fail callback 都沒執行
再次執行Wechat.auth也沒回應

**Comment by KuanYu0729** [comment]
剛才看了一下 跟#76有點相似

**Comment by KuanYu0729** [comment]
另外問一下，文件中的AppId是審核後拿到的AppId 還是WeChat公眾號的

**Comment by xu-li** [comment]
APP_ID是审核后拿到的，不是公众号。
