### ISSUE TITLE
Android 微信分享报未知错误

### ISSUE THREAD

**Issue by iourt** [xu-li/cordova-plugin-wechat#106]
我安装插件是提示这个：
The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
Running android-install.Hook: after_plugin_add, Package: 

我怎么消除这个提示呢？麻烦知道的帮我解答一下，谢谢

还有我Android分享的时候一直报：未知错误，好无耐，不会java
能帮我解决一下不，谢谢！

**Comment by iourt** [comment]
ios版本很顺利，安装好就啥问题都没有

**Comment by xu-li** [comment]
你用的是phonegap，cordova，还是ionic等等？你的cordova什么版本```cordova -v```？

**Comment by iourt** [comment]
cordova 5.4.0

**Comment by iourt** [comment]
用了ionic

**Comment by xu-li** [comment]
这个warning已经修复了。但是我觉得你不能安装不应该是这个问题。能不能下载最新版本的插件，然后再安装试试？

**Comment by yipingw** [comment]
作者你好，
我这里也是在安卓上报了同样的错误，ios上正常。

**Comment by yipingw** [comment]
刚才跟踪了一下代码，返回返回了错误码-6，但这个错误码在官方文档里面并没有说明。

**Comment by yipingw** [comment]
问题原因找到了。请先看官方的这段描述：
Q：应用没有审核通过能不能进行调试？
A：iOS应用只要申请并获取到AppID就可进行调试。Android应用除了获取AppID外，应用还要通过审核，否则无法调起微信进行分享，并且需要在网站上填写包名和签名两个字段，签名可使用签名生成工具获取。如有特殊需要，请自行参见《Signature的生成方法》生成。

也就是说必须是经过签名的安卓app才可以成功调用分享，并且你的安卓app的签名内容在微信那里有记录才行。
