### ISSUE TITLE
微信支付参数获取

### ISSUE THREAD

**Issue by jackie19** [xu-li/cordova-plugin-wechat#107]
prepay_id: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
    nonce: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
    timestamp: '1439531364', // timestamp
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string

请问这4个参数是否都从服务端获取？

**Comment by xu-li** [comment]
最好是，因为有密钥等敏感信息。

**Comment by jackie19** [comment]
感谢回复。
另请问：提示普通错误类型 ，一般是什么问题？

**Comment by xu-li** [comment]
一般是参数错了，比如签名算错了。

**Comment by jackie19** [comment]
能不能打印出更详细的错误提示呢？

**Comment by xu-li** [comment]
这是微信的官方SDK返回的错误信息，没有办法。

**Comment by jackie19** [comment]
谢谢。
