### ISSUE TITLE
是不是需要注册一个微信开发者,获取API KEY等等?

### ISSUE THREAD

**Issue by sulliwane** [xu-li/cordova-plugin-wechat#108]
你好,
请问一下用这个分享到微信朋友群功能, 是不是必须要注册微信开发者账户等等?
谢谢!

edit: 或者APP ID. 应该不需要是吧

**Comment by xu-li** [comment]
需要注册帐号的，但是基本功能不需要认证开发者。

**Comment by sulliwane** [comment]
那我不明白为什么安卓上面有一些欧洲的app他们提供这个"分享到微信群"的功能, 但是他们肯定没有注册微信账号...

**Comment by xu-li** [comment]
比如说呢？ 我不是很清楚。

**Comment by sulliwane** [comment]
这个app叫Gallery KK, 他们支持分享到朋友群以及发送到朋友. 我没问,但是几乎100%确定他们开发者没有区微信网站注册账号以及APP ID. 也没有安装微信的ios/android SDK. 
![screenshot_2015-11-20-13-44-15](https://cloud.githubusercontent.com/assets/1733686/11292762/7ccd02a0-8f8d-11e5-9f98-c0eab2c5b2ab.png)

**Comment by xu-li** [comment]
你说的这个是android的[intent](http://developer.android.com/training/sharing/send.html)吧。

**Comment by sulliwane** [comment]
是的! :+1: 你知道iOS的相等API叫什么名字吗? 谢谢

**Comment by xu-li** [comment]
iOS里面类似的叫[UIActivityViewController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIActivityViewController_Class/index.html).有一个插件叫[SocialSharing-PhoneGap-Plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin)，就是用的这个。

**Comment by sulliwane** [comment]
哦明白! 那你的cordova-plugin-wechat不用UIActivityViewController吗?

**Comment by xu-li** [comment]
没用，目的不一样，我的插件为了做专一微信的sdk的功能。跟那个相比，多了登录，支付等，少了跨平台的分享。

**Comment by sulliwane** [comment]
Ok. 谢谢你的回复 :100:
