### ISSUE TITLE
微信支付页面空白，只有个确定按钮

### ISSUE THREAD

**Issue by sqaiyan** [xu-li/cordova-plugin-wechat#109]
商户号，签名，时间戳都是后台返回的，不知道遇到过没，大概是什么问题

**Comment by you-2-can** [comment]
你好，我也遇到了同样的问题，请问你是怎么解决的啊

**Comment by sqaiyan** [comment]
参数错误了，我之前用后天生成的参数，结果返回的签名是错的，自己签名就好了，

**Comment by you-2-can** [comment]
你好，但我使用的是线上服务器获取的参数sign啊，还有就是安卓的没有问题啊，那应该就不是参数的错误吧

**Comment by sqaiyan** [comment]
同样的参数安卓可以支付 ios空白？是不是微信后台那边没有设置ios的证书啥的，我用的公司账号都是设置好的，之前写原生的同学就是签名错误后来自己签的，你那不是这个问题我也就不知道了，可以问问作者吧
