### ISSUE TITLE
不支持5.3.3或以下版本

### ISSUE THREAD

**Issue by ryanlin1986** [xu-li/cordova-plugin-wechat#112]
由于最新关于cordova-common的改动，导致最新版只能在cordova5.4.0或以上版本编译。
因为目前Visual Studio还不支持cordova 5.4.0进行调试， 可否发布0.9.0版到npm， 这样可以根据自己的需要选择适合的版本。

**Comment by xu-li** [comment]
多谢提醒，前一个提交导致了这个问题。已经兼容原来的版本。

**Comment by ryanlin1986** [comment]
感谢修复！

**Comment by gdamao** [comment]
为什么 andorid5.1 的运行这个插件一直没反应，android 4的没问题
