### ISSUE TITLE
插件安装好之后不能使用，debug发现错误是WeChat is not defined

### ISSUE THREAD

**Issue by ghostgrass** [xu-li/cordova-plugin-wechat#113]
插件安装好之后不能使用，debug发现错误是WeChat is not defined，是不是插件没安装好啊

**Comment by xu-li** [comment]
是不是android？

请确认一下亮点是否做对了。
1. 是否通过微信审核了？一定要通过审核了才能测试。
2. 签名是否对了？这个签名如何生成的，可以看[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。生成签名以后，要把签名填到微信官网的你的app设置里面去。

**Comment by ghostgrass** [comment]
谢谢兄弟。
是安卓，签名都弄好了。现在Wechat是有值的。但是点击分享没任何反应，debug发现cordova.js里面的var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);， msgs是undefined，感觉好像是nativeApiProvider没有get到。
插件安装除了appid还有什么特殊的配置吗

**Comment by xu-li** [comment]
没有特殊配置。
如果是Undefined, 应该是没安装对，JS没有引用到。
你是用的phonegap，cordova，还是ionic？怎么安装的？

**Comment by ghostgrass** [comment]
是使用vs cordova的，命令行安装和vs安装我都试了，都不行。
但是我用了https://github.com/vilic/cordova-plugin-wechat是可以的，他这个是来自于你的。
感觉安装的地方可能出了问题

**Comment by xu-li** [comment]
那你用的是不是最新版本的插件？前一个小版本在cordova5.4以下有安装问题。

**Comment by hexiang199020** [comment]
楼主，我的也是显示 undefined  你是怎么弄好的？ 请赐教！

**Comment by dfghj44444** [comment]
我也是undefined
