### ISSUE TITLE
[android]Wechat.auth(scope, resp.state, onSuccess, onErr);没有拉起授权页面也没有执行回调函数

### ISSUE THREAD

**Issue by lianghuiyuan** [xu-li/cordova-plugin-wechat#114]
您好，IOS能正常工作，Android有以下问题。我调用Wechat.auth(scope, resp.state, onSuccess, onErr);时，没有执行任何回调函数也没有报错. 微信授权界面也没有拉起来，除了打印了以下调试信息没有任何反应。
测试环境: 魅族m1 note  FlymeOS4.5.7A   android版本5.1    cordova版本:5.2.0  微信版本:6.3.7

##### 调试信息如下：
>wechat login
app.js:626 wechat installed = 1
app.js:630 从服务器获取state--resp=
app.js:631 Object {state: "dDTCR27aXHfC"}

##### 代码如下：
```
            var stateSuccess = function(resp){
                    console.log("从服务器获取state--resp=");
                    console.log(resp);
                    var onSuccess = function(result){
                        console.log("从微信获取code--result=");
                        console.log(result);
                        checkAccountWechat(result.code, resp.state);
                    };
                    var onErr = function(err){
                        console.log(err);
                    };
                    Wechat.auth(scope, resp.state, onSuccess, onErr);
                };
                $.hello.api.getAuthState(stateSuccess);
```

**Comment by xu-li** [comment]
android的话，很可能是以下的问题:

1. 是否通过微信审核了？一定要通过审核了才能测试。
2. 签名是否对了？这个签名如何生成的，可以看[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。生成签名以后，要把签名填到微信官网的你的app设置里面去。

**Comment by lianghuiyuan** [comment]
非常感谢！确实是签名导致的问题。
