### ISSUE TITLE
授權後，返回應用程式報錯了

### ISSUE THREAD

**Issue by KuanYu0729** [xu-li/cordova-plugin-wechat#115]
我的App有加裝了下面的plugin
https://github.com/apache/cordova-plugin-whitelist
auth完後返回應用程式都會報錯
但是在build前把whitelist的plugin移除再build就不會有事
也能順利授權

**Comment by xu-li** [comment]
错误是什么？

**Comment by KuanYu0729** [comment]
目前只看到App無回應，還在找ROOT過的手機看logcat
