### ISSUE TITLE
普通错误类型

### ISSUE THREAD

**Issue by hachiwang** [xu-li/cordova-plugin-wechat#116]
我参照[你给出的php样例](https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php)，写了一个java版本的, 可以正常生成prepay_id，说明sign的加密没有问题。
但是js端调用sendPaymentRequest的时候返回错误信息：普通错误类型，其对应的wechat errorCode为-1, 但是没有找到相关errorCode的详细信息。

请问，有什么好的方式来调试这个问题。
谢谢。

**Comment by xu-li** [comment]
你可以考虑把你的参数传给[统一下单接口](https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=9_1)试试能不能行。

这个普通类型错误是微信返回的，没有更详细的描述。

补充一句：最好时间戳什么的都是服务器返回(就像我的demo)，这样做比较简单。

**Comment by hachiwang** [comment]
统一下单接口没有问题。可以拿回结果并取到prepay_id, 所有数据都是在server端生成返还。
服务器端返还数据： 
 "params" : {
    "nonce_str" : "SbGxX7ve",
    "package" : "Sign=WXPay",
    "appid" : "wxd678efh567hg6787",
    "sign" : "5725892ff317167458bcc1057d775f6e",
    "partnerid" : "1230000109",
    "prepayid" : "wx20151209183400d5e4fdbbd60934513842",
    "timestamp" : "1449657240"
  }
微信有什么接口可以测试APP端调起支付的参数列表不？
补充一句：所有的测试都是在本地机器和手机android上进行的。会有影响不？
谢谢。

**Comment by xu-li** [comment]
服务器端返回的这个params你直接传给sendPaymentRequest了么？如果是的，那就错了。

我那个服务端的demo是按照微信官方文档写的(同时也给其它地方用的)，所以返回的参数针对微信的那个文档。但是我的插件的参数是我自定义的(我觉得官方的那个命名太难看，比如nonce_str)，所以你要做调整。

1. 没影响
2. 空白页面基本就是参数问题。

**Comment by hachiwang** [comment]
谢谢。问题解决了。统一下单接口和发起支付接口有个参数名不一样，在统一下单接口里为nonce_str, 在发起支付里为noncestr，导致服务器端对发起支付的加密错了，都基于nonce_str了。

PS：下面的url可以验证签名，还是比较有用。
https://pay.weixin.qq.com/wiki/tools/signverify/
