### ISSUE TITLE
分享出现未知错误

### ISSUE THREAD

**Issue by hcw2175** [xu-li/cordova-plugin-wechat#117]
您好：
现在下载demo ionic体验过程中发送消息出现“未知错误”，检测是否按照微信正常。

然后使用自己申请通过的appid也是一样错误，该如何解决呢？

运行环境：华为荣耀6 -- android 5.1.1

**Comment by xu-li** [comment]
应该是签名错了。看[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。

**Comment by hcw2175** [comment]
我用了2个方法验证过签名都是一样的哦：
1、使用微信提供的签名生成工具.apk获取：[微信资源](https://open.weixin.qq.com/cgi-bin/readtemplate?t=resource/app_download_android_tmpl&lang=zh_CN)
2、使用微信提供的文档里提到的命令：keytool -exportcert -alias [key-alias] -keypass [password] -keystore [key-file] -storepass [password] | md5sum

结果都是 ：9968f4a*********f4fa57475, 也把它添加到微信开发平台了。

不知道该如何调试下去了。请问您代码的log如何打印测试呢，我用的是ionic。

**Comment by xu-li** [comment]
1. 你是如何安装的？我的测试DEMO需要用我的那个APP_ID。
2. 你的APP通过审核了么？没通过审核不能测试。

如果要看log，可以从[logcat](http://developer.android.com/tools/help/logcat.html)看到。
