### ISSUE TITLE
支付打开微信后，返回原程序报错：app 已停止

### ISSUE THREAD

**Issue by hachiwang** [xu-li/cordova-plugin-wechat#119]
FYI，支付打开微信后，返回原程序报错：app 已停止，点击确定，app重新被打开。
$adb logcat | grep Wechat

D/Cordova.Plugin.Wechat( 9800): sendPaymentRequest is called.
W/PluginManager( 9800): THREAD WARNING: exec() call to Wechat.sendPaymentRequest blocked the main thread for 42ms. Plugin should use CordovaInterface.getThreadPool().

$adb logcat | grep htc, com.sixiang.htc.client.android_c/com.sixiang.htc.client.android_c是我app名。

E/MtaSDK  (22038): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.sixiang.htc.client.android_c/com.sixiang.htc.client.android_c.wxapi.WXPayEntryActivity}: java.lang.ClassNotFoundException: Didn't find class "com.sixiang.htc.client.android_c.wxapi.WXPayEntryActivity" on path: DexPathList[[zip file "/data/app/com.sixiang.htc.client.android_c-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sixiang.htc.client.android_c-1, /vendor/lib, /system/lib]]

console debug后，发现没有进入wechat回调。
ps: android版本有这个问题。ios版本没有。而且，android的这个问题昨天ionic state reset后出现的，之前发布的版本没有问题。

谢谢

**Comment by xu-li** [comment]
感觉是插件的[安装脚本](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/scripts/android-install.js)没有执行对。

你可以试试2个方法:
1. 删除再重装插件。
2. 手动拷贝插件的代码。拷贝[EntryActivity.java](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/src/android/EntryActivity.java), [WXEntryActivity.java](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/src/android/WXEntryActivity.java), [WXPayEntryActivity.java](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/src/android/WXPayEntryActivity.java)，到你的项目里面(com.sixiang.htc.client.android_c.wxapi下面)，并修改这些文件第一行的package信息。

多谢。

**Comment by hachiwang** [comment]
嗯。这三个文件都存在com.sixiang.htc.client.android_c.wxapi下。比如现在的某个文件WXPayEntryActivity如下，

package com.sixiang.htc.client.wxapi;

public class WXPayEntryActivity extends EntryActivity {

}

**Comment by xu-li** [comment]
package 不对啊。你没发现么？

应该是package com.sixiang.htc.client.**android_c**.wxapi;。

**Comment by hachiwang** [comment]
嗯。我知道什么原因了。自己把自己坑了。我的包名，android和ios不一样。我写了个脚本ionic run前做了包名替换。
