### ISSUE TITLE
分享给朋友的界面，按手机上的返回键进行取消会退出app

### ISSUE THREAD

**Issue by mkliu** [xu-li/cordova-plugin-wechat#12]
不知道iOS有没有这个问题。开个issue来track下。

我看了半天没找到怎么改。看起来是微信activity没有处理这个事件，然后back button到keyup event被propagate到了cordova。cordova就认为是要退出app。

可能需要在哪儿截获下这个event。

**Comment by lyon11** [comment]
android上我把你们的插件导到工程里，使用share接口，没反应，进了方法以后跑了一圈出来了没跑回调，在真机上每卸载重新安装第一次都会报错：[pool-6-thread-1(933): null:-1] - Server response error code:404, error:{"ret":-1, "msg":"invalid appkey"}，之后不会但是也分享不过去，如果把微信数据清空，强行停止，运行的话，会直接跳到登陆界面但登录号以后就退出来了什么都没做，提供我appkey的人说key没问题，这怎么破？求解

**Comment by lyon11** [comment]
我按照你们的和微信官网的把配置都配了，还要做什么其他的配置工作么

**Comment by mkliu** [comment]
你的signature对么？需要匹配app创建对时候提供对android signature hash。建议你用微信官方的sdk sample先走通试试

**Comment by lyon11** [comment]
我把apk打包给别人手机上去装，装好以后第一次分享是成功的，之后就不行了，就算卸载重装也没用

**Comment by lyon11** [comment]
我自己去重新申请了个appid，现在好了，效果不错，哈哈，谢了，赞一个
