### ISSUE TITLE
微信开发平台帐号 报“scope 参数错误或没有 scope 权限”错误

### ISSUE THREAD

**Issue by hcxiong** [xu-li/cordova-plugin-wechat#120]
微信开发平台帐号 报“scope 参数错误或没有 scope 权限”错误
我只用到分享功能！

**Comment by xu-li** [comment]
请问你的应用通过审核了么？你的开发者帐号通过审核了么？在微信的后台里面，[微信登录](https://open.weixin.qq.com/cgi-bin/frame?t=home/wx_login_tmpl&lang=zh_CN&token=7f200786bc5dba2c3ba2de232a72f279ec8b0a73)开通了么？

**Comment by zq2369185957** [comment]
我也是报“scope 参数错误或没有 scope 权限”错误,应用通过审核了,开发者帐号通过审核了,微信登录也开通了,而且登陆的时候也能获取到code值,但是运行不到获取accesstoken这一步,

**Comment by zq2369185957** [comment]
大佬有啥办法木,
