### ISSUE TITLE
关于使用插件点击后没有响应的问题（亲测、分享成功）

### ISSUE THREAD

**Issue by smithzhang010** [xu-li/cordova-plugin-wechat#121]
关于使用插件点击后没有响应，经反复查证，是因为微信分享对于缩略图大小有限制， 官方建议是:
thumbDatapublic byte[] thumbDataBinary data of a thumbnail imageNOTE: The file size should be within 32KB.

所以希望插件对于分享图过大，增加压缩代码：
这里提供一个简单粗暴的方式，参考如下：                 
            if (thumbnail != null) {
                Bitmap thumb = Bitmap.createScaledBitmap(thumbnail, 360, 240, true);
                wxMediaMessage.setThumbImage(thumb);
            }

**Comment by xu-li** [comment]
多谢提供的建议。

**Comment by xu-li** [comment]
我已经更新，在最新版本(0.10.1)里面加入这个功能。

你可以考虑测试一下。 : )

**Comment by MakeHui** [comment]
@xu-li  iOS 同样会有这个问题
```
- (UIImage *)getUIImageFromURL:(NSString *)url
{
    NSData *data = [self getNSDataFromURL:url];
    UIImage *image = [UIImage imageWithData:data];
    CGSize newSize = CGSizeMake(360, 240);
    UIGraphicsBeginImageContext( newSize );
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage* newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return newImage;
}
```

**Comment by xu-li** [comment]
@MakeHui 多谢提醒。已经加到最新版中了。
