### ISSUE TITLE
安卓release版本分享报未知错误

### ISSUE THREAD

**Issue by yesir1006** [xu-li/cordova-plugin-wechat#122]
安卓release版分享的时候先跳到微信界面然后瞬间跳转回来，报未知错误，请问这是什么原因呢？debug版程序运行正常，cordova 5.4.0，ionic，谢谢。（微信平台安卓包名和应用签名都已经验证通过）

**Comment by xu-li** [comment]
应用签名用的是release版本的keystore还是debug版本的？

错误的提示是什么呢？

**Comment by yesir1006** [comment]
http://ionicframework.com/docs/guide/publishing.html 就是按照这个步骤生成的安装包，logcat打印错误说“未知错误”，没有具体的信息，现象就是跳到微信页面显示请稍后然后马上就跳回来了，刚搜索看到http://ionichina.com/topic/55656f0a89dbe3b66a391180#567250d46633924d7959695b 这里有人和我相同的问题，就是不知道怎么解决的

**Comment by xu-li** [comment]
Andorid的debug的keystore和release的keystore不是同一个，而微信需要的应用签名需要keystore来生成，所以你要把你的release的keystore(就是你贴的第一个链接里面的keystore)拿来再生成一遍签名，提交到微信上去。

**Comment by yesir1006** [comment]
确实如你所说，已经解决了，非常感谢🙏
