### ISSUE TITLE
ios下build失败

### ISSUE THREAD

**Issue by mjbin** [xu-li/cordova-plugin-wechat#123]
** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/UmazmProj.app/UmazmProj normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/laozhuorun/Desktop/Umazm-test/platforms/ios/cordova/build-debug.xcconfig,-project,UmazmProj.xcodeproj,ARCHS=i386,-target,UmazmProj,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/laozhuorun/Desktop/Umazm-test/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/laozhuorun/Desktop/Umazm-test/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/laozhuorun/Desktop/Umazm-test/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/laozhuorun/Desktop/Umazm-test/platforms/ios/cordova/build: Command failed with exit code 2

你好，我添加了插件，然后在ios下build失败。请问一下是怎么回事。。xcode是6.4。。

**Comment by xu-li** [comment]
删除插件，然后再build，会不会失败呢？

其它的信息呢？比如，用的cordova版本，或者phonegap，ionic的版本？Mac OS的版本？

**Comment by mjbin** [comment]
删除插件-删除平台-安装平台-安装插件，这步骤下来也是提示这错误
mac os：10.10.3
cordova：5.4.1
ionic：1.7.12

**Comment by xu-li** [comment]
好像cordova 5.4.1有这个问题，参见[这里](https://github.com/driftyco/ionic-cli/issues/282)的最后的一条。

> We had a developer affected with this issue as well downgrading cordova from 5.4.1 to 5.4.0 npm uninstall -g cordova && npm install -g cordova@5.4.0 fixed this issue for us.

**Comment by mjbin** [comment]
试了一下，还是一样的错误

**Comment by xu-li** [comment]
删除插件-删除平台-安装平台-build， 有问题么？

**Comment by mjbin** [comment]
有，单独测试过

**Comment by mjbin** [comment]
在xcode下build了一下有这个错误提示
![e toz vunmn d i wg _w](https://cloud.githubusercontent.com/assets/3965629/11890599/ee4d0bbe-a590-11e5-9eb4-dc46d014371b.jpg)
，不知道这错误是什么意思，上网找了一些，好像也没提供到有效的方法

**Comment by xu-li** [comment]
截图没全啊。上面的呢？

还有，你其它安装的插件呢？会不会和其它插件冲突？

**Comment by mjbin** [comment]
![6mq_fk9cq7pyyufn1q2iyog](https://cloud.githubusercontent.com/assets/3965629/11891681/d87c353e-a59b-11e5-9dfa-d3b4f628e2c5.jpg)
没有安装其他插件， 我是只装了你这个插件的，检查了frameworks文件夹，没有相同的文件

**Comment by mjbin** [comment]
升级Xcode7.2，已解决问题
