### ISSUE TITLE
在安卓上运行闪下就退回到自己的APP了，但是在苹果没问题。说是那个签名不对，可是这个插件不是自己生成的签名吗？不懂怎么解决？

### ISSUE THREAD

**Issue by AberGLJ** [xu-li/cordova-plugin-wechat#125]

**Comment by xu-li** [comment]
插件生成的签名是支付API那里的。

你需要生成的签名是APP的，具体参见文档。

**Comment by AberGLJ** [comment]
我想说的是我没有用支付接口，用的是分享，可还是出问题了。按照您的描述，他应该在安卓上是自动生成的。请问具体的解决方案是什么？

**Comment by AberGLJ** [comment]
我是想分享在安卓上，但是share的时候闪一下就回到自己页面了？

**Comment by AberGLJ** [comment]
在安卓上，APP一定要通过审核才能够使用分享？

**Comment by xu-li** [comment]
参见[官方文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=1417751808&token=&lang=zh_CN)。

```
1.申请你的AppID
请到 开发者应用登记页面 进行登记，登记并选择移动应用进行设置后，将该应用提交审核，只有审核通过的应用才能进行开发。
```

**Comment by AberGLJ** [comment]
我用的是测试账号，应该没那个问题。而且我也用了正式的在用的账号使用，还是一样的

**Comment by xu-li** [comment]
签名问题。我在另外一个issue跟你说了。

**Comment by MakeHui** [comment]
@xu-li  我也遇到了同样的问题, 使用插件自带的签名是可以进行分享的, 但是我用自己的`keystone`重新签名并把签名后的`应用签名`配置到微信开发者后台, 看起来并没有操作上的错误, 但是它无法分享了

**Comment by AberGLJ** [comment]
你的要签名和打包，然后就没事了了。

**Comment by MakeHui** [comment]
@AberGLJ  thx!
找到原因了(比较坑%>_<%)
我mac上生成的keystone有问题, 虽然能通过微信的签名获取工具获取到签名但是并不能成功使用
换用了同事的keystone文件签名就能成功分享了

**Comment by yurychika** [comment]
@MakeHui 想问下怎么解决的？我好像也是一样的问题，keystore生成的签名，然后二次签名提交到微信，但是我的app 点击分享总是闪一下，还是停留在app而不是微信。

@xu-li 能帮帮我吗，这个问题搞了好久，感觉一切都是按照流程来的。我的app本来只有ios版本，今天才刚刚添加了安卓的信息，不知道会不会有延迟？但是看状态已经是通过的，而不是审核

**Comment by xu-li** [comment]
@yurychika https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN

**Comment by yurychika** [comment]
@xu-li 我就是按照这个文档生成的Md5 签名，因为我的安卓app之前在应用商店上过一版，所以应该是不能换Keystore的是吗？ 不知道我的Keystore会不会有问题

**Comment by januslo** [comment]
下载他官方那个检测签名的app去看吧。我是用那个检测出来的字符串放到网站设置里面的

发自我的 iPhone

**Comment by yurychika** [comment]
@xu-li 我在手机上装了md5 签名生成器的apk，生成的签名和教程上的也是一样的。我目前是cordova build了release的包，然后用jarsign 用keystore签名，然后再用zipalign生成release apk，最后把release apk拖到手机上安装。
不过就是有提到的那个一闪的问题，不跳转到微信。

**Comment by yurychika** [comment]
@januslo 你好 链接有吗

**Comment by xu-li** [comment]
@yurychika 有几个注意的地方，第一个是debug和release版本的签名是不一样的，第二个是你的签名要和微信后台里面填写的一样(比如，你用的debug的keystore，那么后台也要填debug的keystore对应的签名)。

Good luck.

**Comment by yurychika** [comment]
@xu-li 兄弟太感谢了，目前可以了，我什么都没用改，可能是微信那边签名添加了之后并不会立刻生效！
太感谢了！中秋快乐！

**Comment by b1ueRa1n** [comment]
我确定appid是正确的, 签名也是正确的, 跟微信开放平台添的一致.还是share不了, 一闪而过了.
后来我参考了@cimichen 在Wechat.java里手动写死了 appId = "wxb24XXXXXXXXX", 这样就可以了.能告诉原因吗 谢谢@xu_li

**Comment by xu-li** [comment]
可能是你第一次装插件的时候，用了一个测试的Key，后来才改成了正式的Key。

默认的Cordova装完插件以后，会拷贝一些配置文件到项目里面去。所以，你以为你改了，其实很多拷贝你都没改。

最简单的方法就是把platform和plugin都remove掉，重新再add。当然，你也可以试试在整个项目中全局搜索你的旧Key。

以上仅仅是我的猜测。

-Xu
