### ISSUE TITLE
能执行isInstalled方法，执行auth时未有任何反应（没错误和成功提示，并且控制台也未报错）

### ISSUE THREAD

**Issue by yanglong2** [xu-li/cordova-plugin-wechat#126]

**Comment by xu-li** [comment]
1. 是否跳转到了微信？
2. 分享功能是否可以用？
3. auth功能需要到微信官方开通权限，是否已经完成？
4. 什么平台？iOS还是Android？
5. Android的话，需要通过审核，才能分享。

**Comment by yanglong2** [comment]
1、未拉取让用户确认登录的界面
2、分享功能会出校闪退的情况，回调里报未知类型错误
3、auth功能已经开通了，在我官方已经通过认证了，而且拿到了appid
4、android，用的meteor技术，但是可用cordova
5、我看微信上的除了支付和卡券需要再申请，其他已获得权限了

**Comment by AberGLJ** [comment]
Android分享时闪一下退回到自己页面，是跳转到了微信。appid是使用测试的账号，请问是什么问题？

**Comment by yanglong2** [comment]
望回复 ，比较急  要做微信登录这块

**Comment by AberGLJ** [comment]
你用这个做登录？

**Comment by AberGLJ** [comment]
你的安卓可以用分享吗

**Comment by yanglong2** [comment]
对  做登录    分享也是闪退不行

**Comment by AberGLJ** [comment]
这个插件不是分享的吗？还可以登录？你的分享是安卓闪退？

**Comment by yanglong2** [comment]
一样闪退，有登录的

**Comment by yanglong2** [comment]
刚刚又亲测了一遍，登录其实也是闪退，我已经看到“微信登录”这几个字了

**Comment by xu-li** [comment]
从你的描述，很可能是[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)的问题。

可以再确认一下iOS是否可以，iOS不需要签名。如果iOS是可以登录和分享的，那么确定是签名问题。

同时，可以看一下logcat里面的输出内容，是否有什么错误。

**Comment by AberGLJ** [comment]
我的iOS可以登录和分享，但是安卓就闪下。如果是签名的话，怎么解决在安卓上的问题呢

**Comment by xu-li** [comment]
你看我的评论啊，生成[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)，可以去看看官方文档。

**Comment by yanglong2** [comment]
已解决，多谢 就是签名不对。

**Comment by AberGLJ** [comment]
你怎么解决签名的问题，安卓在哪里改啊？不懂安卓。
