### ISSUE TITLE
调用之后出bug了

### ISSUE THREAD

**Issue by hujin** [xu-li/cordova-plugin-wechat#127]
调用这个
Wechat.share({
    text: "This is just a plain string",
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});
跳到微信就没反应了

调用这个
Wechat.share({
    message: {
        title: "Hi, there",
        description: "This is description.",
        thumb: "www/img/thumbnail.png",
        mediaTagName: "TEST-TAG-001",
        messageExt: "这是第三方带的测试字段"
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});
直接报错参数错误

**Comment by hujin** [comment]
在ios下面

**Comment by hujin** [comment]
请问是不是微信的开放平台的key也需要的？

**Comment by xu-li** [comment]
安装插件的时候需要的app key就是微信开放平台的key。
