### ISSUE TITLE
android微信支付 参数错误

### ISSUE THREAD

**Issue by mjbin** [xu-li/cordova-plugin-wechat#129]
你好，我在使用微信支付的时候，通过接口调试工具https://pay.weixin.qq.com/wiki/tools/signverify/
生成了sign
![image](https://cloud.githubusercontent.com/assets/3965629/12029367/3e46100c-ae24-11e5-9bf5-90450b07f6ee.png)
现在先在测试阶段不涉及服务端返回的值，但是我一直返回普通错误类型。请问在不涉及服务端的情况下我可以直接这样调用微信的支付接口吗

**Comment by xu-li** [comment]
你的prepay_id哪里来的？那个工具只是计算签名的吧。

**Comment by mjbin** [comment]
prepay_id 看你给的php demo好像是要经过后台计算得到的，但是我现在没有后台，所以我是先写死了一个字符串。然后根据这上面的值再去计算签名

**Comment by xu-li** [comment]
写死的意思是随便写了一个字符串么？这个肯定是不行的。

没有后台，你可以用curl去请求一个prepay_id，理论上是一样的。

**Comment by mjbin** [comment]
好的，明白了，我去试试先，感谢回复
