### ISSUE TITLE
Callback doesn't trigger after successfully shared

### ISSUE THREAD

**Issue by jianbo** [xu-li/cordova-plugin-wechat#13]
Hi, both moment share and session share success callback is not reached, any idea?

                                   Wechat.share({
					    message: {
					        title: $scope.message,
					        description: $scope.message,
					        thumb: $scope.img,
					        media: {
					            type: Wechat.Type.LINK,
					            webpageUrl: $scope.url
					        }
					    },
					    scene: Wechat.Scene.SESSION   
					}, function () {
					    console.log("Success...................");
					}, function (reason) {
					    console.log("Failed.............: " + reason);
					});

**Comment by xu-li** [comment]
iOS or Android? Which version? Are you using ionic? Have you tried [example](https://github.com/xu-li/cordova-plugin-wechat-example)?

**Comment by lyon11** [comment]
android

**Comment by jianbo** [comment]
It happens to me on IOS, I am using Ionic framework. Will try the example
later :

**Comment by xu-li** [comment]
no update. closed.
