### ISSUE TITLE
android下调用支付方法直接退出app

### ISSUE THREAD

**Issue by mjbin** [xu-li/cordova-plugin-wechat#130]
你好，我在android调用微信支付的方法，然后没任何返回信息，直接退掉了app？请问是什么情况，假如我故意修改错误的参数，他是能直接弹出错误的信息的

**Comment by mjbin** [comment]
更新了插件之后不退出了，但是报 fail：普通错误

**Comment by xu-li** [comment]
就是参数错了。 你可以考虑用debug版本的微信SDK再试试。

参见[Debugging in Android](https://github.com/xu-li/cordova-plugin-wechat/wiki/FAQ#debugging-in-android)。

**Comment by mjbin** [comment]
你好，我的是window的，你的debug命令不生效啊。。。
我再试了一下，发现统一下单接口返回来的整个xml数据跟我提交给接口的数据不一样。
我提交的对象
![qq 20151231145855](https://cloud.githubusercontent.com/assets/3965629/12062012/1c629300-afcf-11e5-9416-c34eaf14b185.png)
接口返回来的数据
![qq 20151231145214](https://cloud.githubusercontent.com/assets/3965629/12061993/a3a9f11a-afce-11e5-822f-657e6b49b944.png)
随机字符串，sign是不一样的，但是也返回prepay_id.不太清楚这里有没有问题。

那么，我这里接下来要提交到你插件的一个params对象。里面的sign和nonce我是不是用接口返回来的数据，我这么用还是报普通错误
![qq 20151231150346](https://cloud.githubusercontent.com/assets/3965629/12062043/b72a82b2-afcf-11e5-8242-67a344d8df2d.png)

**Comment by xu-li** [comment]
windows一样的啊，只是命令行 不一样，你找到adb命令，照样执行。

统一下单接口返回的签名是对它返回结果的签名，不用管，只要返回了prepay_id就行。

你传给插件的参数，是你自己的nonce和sign，你看我的demo和官方文档吧，很详细的。
