### ISSUE TITLE
与cordova-plugin-pingpp,中的 libammsdk.jar 包有冲突，请问该怎么解决呢？

### ISSUE THREAD

**Issue by JhonYoung** [xu-li/cordova-plugin-wechat#131]
与cordova-plugin-pingpp,中的 libammsdk.jar 包有冲突，请问该怎么解决呢？

**Comment by xu-li** [comment]
先安装cordova-plugin-pingpp，然后删除platforms/android/libs/libammsdk.jar，然后再安装cordova-plugin-wechat。

不知道为什么，md5哈希出来的libammsdk.jar不一样，他的版本好像比较老，所以需要把我的插件的libammsdk.jar覆盖他的。

**Comment by yanglong2** [comment]
pingpp的libammsdk重写了，而你的libammsdk貌似没怎么修改；可以给个libammsdk的源码吗？我反编译过后有点问题

**Comment by JhonYoung** [comment]
还是非常感谢。我们删除了pingpp的jar包，改用你这边依赖的jar包，结果微信支付不能正常使用了，微信登录可以使用，可能是pingpp提供的jar包有点问题。

**Comment by xu-li** [comment]
@yanglong2 libammsdk是微信官方的sdk，我没有源代码。

**Comment by 519818538** [comment]
@JhonYoung 请问你最后是怎么解决这个冲突问题的呢？支付必须得要，微信分享最好也能用

**Comment by 519818538** [comment]
@yanglong2 请问这个冲突问题你解决了吗？

**Comment by 519818538** [comment]
@xu-li 这个libammsdk.jar 的sdk是微信提供的，为啥你这个和cordova-plugin-pingpp的sdk会不一样呢，有什么终极解决方案吗？屏蔽那个插件里面的sdk完成不了支付

**Comment by xu-li** [comment]
@519818538 你可以问问pingpp的开发，我的SDK是官方([这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319164&token=&lang=zh_CN))的啊。
