### ISSUE TITLE
iOS 9.2分享不能成功

### ISSUE THREAD

**Issue by ayonge20** [xu-li/cordova-plugin-wechat#134]
请问一下啊，你写的微信分享插件，iOS 9.2分享不能成功，请问这个问题该如何解决？

**Comment by xu-li** [comment]
测试发现在iOS 9.2可以分享。

请问：
1. 你是否用的最新版本的插件？
2. 是否用的真机测试？
3. android是否可以分享？
4. 用的什么framework？phonegap, cordova, ionic 还是别的？

**Comment by ayonge20** [comment]
可以了，是之前的插件内容没有更新，下载的是旧的版本的。
