### ISSUE TITLE
求解  ReferenceError: Can't find variable: Wechat

### ISSUE THREAD

**Issue by gdamao** [xu-li/cordova-plugin-wechat#135]
我是在win7开发好后，android 测试没问题 ，生成 ionic platform  add  ios  然后把ios文件复制到苹果里面去xcode7.2打开，
测试结果第一个错误就是ReferenceError: Can't find variable: Wechat

**Comment by xu-li** [comment]
platform add以后，需要build，至少需要prepare才会拷贝资源到项目里面。

当然，最好的方法还是直接在Mac里面做。

**Comment by zannet** [comment]
遇到同样问题，在simulator下正常，真机测试Can't find variable: Wechat

**Comment by gdmec07140540** [comment]
我是在mac上开发的，先开发的android版，微信登录和分享功能都没有问题，后面就build ios，装到真机上调试，也遇到了这个错误

**Comment by gdmec07140540** [comment]
@xu-li ios版的用Safari调试发现wecaht.js没有导入，android版的就有导入

**Comment by xu-li** [comment]
不知道。没碰到过这种情况。

可以试试remove掉iOS platform，再remove掉这个插件，再重新装回来。
