### ISSUE TITLE
xcode7.2 正式打包的时候出现这个错误  was built without full bitcode.

### ISSUE THREAD

**Issue by gdamao** [xu-li/cordova-plugin-wechat#137]
ld: bitcode bundle could not be generated because '/Users/amao/Desktop/Haobango.Weixin/platforms/ios/demo/Plugins/xu.li.cordova.wechat/libWeChatSDK.a(WapAuthHandler.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xu-li** [comment]
*Enable bitcode*改成*No*. See http://stackoverflow.com/questions/30848208/new-warnings-in-ios9.
