### ISSUE TITLE
你的签名参数就是例子的那几个吗？

### ISSUE THREAD

**Issue by match08** [xu-li/cordova-plugin-wechat#140]
需要产出签名的参数就这个几个是吗？看源码是这样
req.partnerId = params.getString("mch_id");
            req.prepayId = params.getString("prepay_id");
            req.nonceStr = params.getString("nonce");
            req.timeStamp = params.getString("timestamp");

**Comment by xu-li** [comment]
还有[sign](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/src/android/Wechat.java#L268)。

为什么不能在 #138 里面说这个问题？
