### ISSUE TITLE
安卓分享的时候会闪一下，微信打不开。没登录的话倒是好的，可以打开微信提示登录

### ISSUE THREAD

**Issue by yczf1836** [xu-li/cordova-plugin-wechat#141]
我就照着Demo写的：
Wechat.share({
            text: "This is just a plain string",
            scene: Wechat.Scene.TIMELINE   // share to Timeline
        }, function() {
            alert("Success");
        }, function(reason) {
            alert("Failed: " + reason);
        });
打不开微信应用

**Comment by xu-li** [comment]
你的签名对么？应用通过审核了么？

可以试试[DEBUG](https://github.com/xu-li/cordova-plugin-wechat/wiki/FAQ#debugging)那块。

**Comment by yczf1836** [comment]
alert("Failed: " + reason);  这个也没有弹出来，大神，方便加我下qq 吗？ 15247429 
什么签名了？应用在本地调试

**Comment by evanux** [comment]
我也遇到了同样的问题，未登录时微信会弹出要求登陆，登陆以后微信会打开一下然后闪退，微信账号已经通过审核了，因为看不到reason，所以把调试输出贴给您，麻烦帮忙看下，谢谢。

V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityResumed
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
D/Cordova.Plugin.Wechat: isWXAppInstalled is called. Callback ID: Wechat1775445222.
D/Cordova.Plugin.Wechat: share is called. Callback ID: Wechat1775445223.
D/Cordova.Plugin.Wechat: Start building message.
D/Cordova.Plugin.Wechat: Start downloading file at http://xxx/Upload/image/cover/569689bbc6ee4.jpg.
D/Cordova.Plugin.Wechat: File was downloaded and saved at /storage/emulated/0/cache/569689bbc6ee4.jpg.
D/Cordova.Plugin.Wechat: Bitmap was downloaded and cached to /storage/emulated/0/cache/569689bbc6ee4.jpg.
D/Cordova.Plugin.Wechat: Bitmap was decoded, dimension: 566 x 566, max allowed size: 320.
E/OpenGLRenderer: CacheDebug: releaseTexture, bitmap = 0x559d142500, ID = 417
E/OpenGLRenderer: CacheDebug: releaseTexture, bitmap = 0x559d0ddd20, ID = 418
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityPaused
I/Cordova.Plugin.Wechat: Message has been sent successfully.
E/OpenGLRenderer: CacheDebug: clearGarbage, ID = 417
E/OpenGLRenderer: CacheDebug: clearGarbage, ID = 418
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onBackground
W/IInputConnectionWrapper: reportFullscreenMode on inactive InputConnection
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityResumed
I/InputMethodManager: [startInputInner] EditorInfo { packageName=com.pingfang.cordova, inputType=0xa1, imeOptions=0x12000000, privateImeOptions=null }, windowGainingFocus=android.view.ViewRootImpl$W@145cdb1b, mServedView=org.apache.cordova.engine.SystemWebView{23cf0ff5 VFEDH.C. .F...... 0,0-720,1184 #64}, mServedInputConnectionWrapper=android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper@82db4b8
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityPaused
W/IInputConnectionWrapper: reportFullscreenMode on inactive InputConnection
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onBackground
W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2306

**Comment by xu-li** [comment]
不好意思，有点其它事情。

从 @evanux 的日志来看，消息是发送到微信了。com.pingfang.cordova是你的package id吧？[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)是不是对呢？签名要和你在微信平台上填写的一样。

**Comment by yczf1836** [comment]
@xu-li 我们申请的是公众平台，没有签名。问下开发平台的签名在cordova 什么地方设置了？

**Comment by xu-li** [comment]
不是公众平台，应该是[开放平台](https://open.weixin.qq.com/)。设置在开放平台里面，你申请以后就知道了。

**Comment by evanux** [comment]
@xu-li ，搞定了，确实是签名的问题，插件本身没有问题的，多谢

**Comment by yczf1836** [comment]
谢谢楼主
