### ISSUE TITLE
EMOTION分享的问题

### ISSUE THREAD

**Issue by fandongjiqi** [xu-li/cordova-plugin-wechat#145]
升级到1.1.1后，分享EMOTION的时候可以打开微信的选择窗口，选择完发送对象后，弹出分享界面，点击分享后，微信进入假死状态，没有提示分享成功。没有任何的返回。

**Comment by xu-li** [comment]
请问这是Android，还是iOS？什么版本的？能否把你的分享图片发给我？

多谢。

**Comment by fandongjiqi** [comment]
这个是andriod的，iOS没有问题。安卓系统是4.4.2，微信版本是6.3.9


![Uploading 4.pic.jpg…]()
![Uploading 3.pic.jpg…]()

**Comment by fandongjiqi** [comment]
这个是andriod的，iOS没有问题。安卓系统是4.4.2，微信版本是6.3.9
如果把EMOTION改成IMAGE的话，可以分享出去。就是EMOTION点击分享后没有任何的反应，停在了选择要发送的人的那个界面
![3 pic](https://cloud.githubusercontent.com/assets/6702031/12383063/360d627e-bddc-11e5-9549-29921bbc7080.jpg)
![4 pic](https://cloud.githubusercontent.com/assets/6702031/12383064/373276da-bddc-11e5-883d-1660076469f2.jpg)

**Comment by xu-li** [comment]
我又测试了一下，这个应该是官方的BUG。

然后我下载了他们[官方的DEMO](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN)，发送表情连微信都打不开。

我发了个邮件给微信。

**Comment by fandongjiqi** [comment]
这个问题是因为EMOTION的参数用的我们服务器上的地址造成了微信无响应，后来，我稍微改了一下代码，把gif图的字节码发给微信就好了。。。。灵感来源于你的IMAGE的操作，先下载，然后发bitmap。。。

**Comment by xu-li** [comment]
好吧，你用的是```WXEmojiObject.emojiData```不是```WXEmojiObject.emojiPath```，对吧？

**Comment by fandongjiqi** [comment]
对。不过这样的话是不是穿本地（本机）的gif就不行了？

**Comment by xu-li** [comment]
一样的。回头我改一下。多谢。

**Comment by fandongjiqi** [comment]
:)
