### ISSUE TITLE
每次登陆都会拉起微信的授权页面

### ISSUE THREAD

**Issue by supershy77** [xu-li/cordova-plugin-wechat#146]
点击微信登陆后到微信授权页面，点击确认登陆后回到登录页，并能正常显示access_token。
但再次点击微信登陆还是重复以上的操作(跳到微信授权页面，点击确认登陆后回到登录页，并能正常显示access_token)。。。
微博和qq的登陆是ok的，如果授权页面确定后，再次点击登陆会直接返回access_token

**Comment by xu-li** [comment]
这是SDK的问题，你需要把access_token记住，比如保存到localStorage里面。
