### ISSUE TITLE
安卓下的支付功能不能使用，未能打开微信APP，返回了普通错误，无法调试。

### ISSUE THREAD

**Issue by berserker001** [xu-li/cordova-plugin-wechat#148]

**Comment by xu-li** [comment]
Android的[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)对么？

**Comment by berserker001** [comment]
签名是发布release版后使用keystore对apk进行签名，之后安装到了手机上，再用官方提供的app获取出key再保存到微信开发者后台的。

**Comment by xu-li** [comment]
如果你确定签名是正确的，可以考虑替换个lib包，然后打开Logcat的日志看看为什么。参见[这里](https://github.com/xu-li/cordova-plugin-wechat/wiki/FAQ#debugging-in-android).

**Comment by xu-li** [comment]
See #138 .

**Comment by berserker001** [comment]
var params = {
    partnerid: '10000100', // merchant id
    prepayid: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
    noncestr: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
    timestamp: '1439531364', // timestamp
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
};
这不用加上package和appid这两个参数吗？

**Comment by berserker001** [comment]
https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=9_12&index=2%E4%BF%9D%E6%8C%81%E4%B8%80%E8%87%B4 这上边是要求有package和appid这俩字段，然后生成sign。

**Comment by xu-li** [comment]
appid在添加plugin的时候就加了，所以不需要。package是写死的，所以也不需要。
