### ISSUE TITLE
报普通错误

### ISSUE THREAD

**Issue by hyitclj** [xu-li/cordova-plugin-wechat#149]
服务器端我自己写的，我按照https://pay.weixin.qq.com/wiki/tools/signverify/这个网址生成一个签名，然后按照官网生成xml传到https://api.mch.weixin.qq.com/pay/unifiedorder，得到success，之后，我将返回的prepayid，noncestr，sign分别换上，结果还是报普通错误。怎么办？提交前后的值都试了，都是报普通错误，求破。php我不太懂，所以写了java的。求大神帮帮忙啊

**Comment by hyitclj** [comment]
我试了一下，二次签名，也不行，还是报普通错误，partnerid:、prepayid、noncestr我都是用的第一次请求的返回值 timestamp我随便写的，写的是：'1412000000'，然后去https://pay.weixin.qq.com/wiki/tools/signverify/去这边生成签名，之后还是报普通错误

**Comment by xu-li** [comment]
1. 第一次发送请求到/pay/unifiedorder的时候，返回值只有```prepay_id```有用。
2. 然后再重新组个HashMap, 这里只有prepayid是原来第一步的值，比如，nonce和timestamp都是新的。
```php
$response = array(
    'appid'     => APP_ID,
    'partnerid' => MCH_ID,
    'prepayid'  => $prepay_id,
    'package'   => 'Sign=WXPay',
    'noncestr'  => generateNonce(),
    'timestamp' => time(),
);
```
3. 然后对于这个HashMap重新算签名，并加入到这个HashMap
```php
$response['sign'] = calculateSign($response, APP_KEY);
```
4. 返回的值传到客户端，并传给微信的插件。

**Comment by hyitclj** [comment]
thanks

**Comment by hejunlong007** [comment]
是的，就是这个 https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php 里面的算法，对吧，除了开头的那三个APP_ID，MCH_ID，APP_KEY 和中间的notify_url 需要改，其他的貌似不需要修改，我这儿也是出现“普通错误类型”，是不是还有哪里需要注意的地方？

**Comment by xu-li** [comment]
android还是ios？android的话，分享什么的对么？如果不对，那就是app的签名不对了。

**Comment by hejunlong007** [comment]
是android的，分享的我试了一下，弹出未知错误。

关于app签名有这样一个小插曲，app签名才开始的确不对，后来我纠正对了。
并在微信网站上进行了修改，是不是修改之后要过一段时间才能生效？

**Comment by xu-li** [comment]
@hejunlong007 我记得不用，立即生效。

**Comment by hejunlong007** [comment]
@xu-li 好的，cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable WECHATAPPID=wxxxxxx  这个插件在ios下安装后 可以直接用吗？貌似 有点 问题

**Comment by hejunlong007** [comment]
www下代码和安卓下是一样的，在ios下调用报的是 发送请求失败

**Comment by hyitclj** [comment]
@hejunlong007 我就是直接装的，直接可以用

**Comment by hejunlong007** [comment]
@hyitclj 好的，我的安卓下成功了，ios下我再卸了再装一遍，估计ios下应该没多大问题

**Comment by hejunlong007** [comment]
@xu-li @hyitclj 
我cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable WECHATAPPID=wxxxxxx 
后 cordova build 就会出错，remove之后就可以build了，你们确定直接安装后可以用？

**Comment by hejunlong007** [comment]
我说在ios下面

**Comment by hyitclj** [comment]
是的，直接装，分享和支付都可以直接用，我都用过了

**Comment by hejunlong007** [comment]
@hyitclj  你是ios下吗？你的cordova版本是多少？我的安装之后build会出错，不确定是不是cordova版本的问题

**Comment by hyitclj** [comment]
5.0以上

**Comment by hejunlong007** [comment]
我的cordova 刚升级到6.0.0 ，安装插件后 build 就会出现下面的错误


Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/pcbeta/Desktop/mdinghuo/platforms/ios/cordova/build-debug.xcconfig,-project,mdinghuo.xcodeproj,ARCHS=i386,-target,mdinghuo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/pcbeta/Desktop/mdinghuo/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/pcbeta/Desktop/mdinghuo/platforms/ios/build/sharedpch

**Comment by hejunlong007** [comment]
cordova 升级到6.0.0后，安装了可以build 了，但是调用支付的时候无反应了

**Comment by hyitclj** [comment]
参数问题吧。。。你后台生成签名什么估计有问题

**Comment by hejunlong007** [comment]
@hyitclj 不太可能是参数问题，因为后台生成签名部分是php代码，我的安卓下的微信支付用的就是这个代码，并且已经可以支付了，

**Comment by hyitclj** [comment]
记住，时间戳是10位，不是13位。我之前就是犯过这个错误，导致android成功了，ios没有成功。你再去查一查吧

**Comment by hejunlong007** [comment]
时间戳是10位，php生成的时间戳是10位

**Comment by hejunlong007** [comment]
你的cordova 版本和xcode的版本是多少？

**Comment by wangchao1002** [comment]
@xu-li 你好  我使用了微信支付插件 一直显示普通错误 签名和相关的参数都和微信开发文档(https://pay.weixin.qq.com/wiki/tools/signverify/)一一对应了 都能对应上 但是还是提示普通错误  希望能得到你的帮助

**Comment by xu-li** [comment]
android 还是 ios啊？普通错误，看起来基本就是android下面的问题。比如app id不对(要用开放平台的)，比如你的app没过审核，比如你的参数不对。
