### ISSUE TITLE
请问使用Share media出现“JSON error"是什么问题

### ISSUE THREAD

**Issue by yaoyonstudio** [xu-li/cordova-plugin-wechat#150]
你好，今天试了一下这个插件，Share text没问题，但使用Share media的时候，报了
”JSON error“，请问是什么问题？
盼复，感谢。

**Comment by xu-li** [comment]
贴一下你的JS代码？应该是参数错了。

**Comment by yaoyonstudio** [comment]
是参数写错了，不好意思。
非常感谢。

**Comment by lixueli0205** [comment]
我也出现了这个错误，请问是哪里的参数要改？
