### ISSUE TITLE
ios端不能付款

### ISSUE THREAD

**Issue by hyitclj** [xu-li/cordova-plugin-wechat#153]
ios端微信支付，跳过去只一个空白页面（最上面有一个返回），只有中间有一个确定按钮（白色背景的弹窗，弹窗上面只有蓝色的确定二字），点击确定之后返回应用，然后走了error方法，弹出“用户点击取消并返回”，ios端支付有什么特别要注意的地方吗？

截图如下：
http://cckhn.img47.wal8.com/img47/499083_20141027142839/145405339007.png
求帮帮忙啊

**Comment by hyitclj** [comment]
http://cckhn.img47.wal8.com/img47/499083_20141027142839/145405339007.png

**Comment by vevHack** [comment]
我也遇到过这个问题，这个貌似是签名引起的，你检查一下后台的签名计算的参数是否正确

**Comment by xu-li** [comment]
你的签名错了，可以去看看支付的签名文档]。

**Comment by hyitclj** [comment]
同一套签名啊，android可以用，难道ios的签名和android的不一样？

**Comment by hyitclj** [comment]
String text = "appid=wxfff1e0d2b4ca6732"
                  + "&body=APP支付"
                  + "&mch_id=1308950901"
                  + "&nonce_str=1add1a30ac87aa2db72f57a2375d8fec"
                  + "&notify_url=http://121.225.202.163:8888/myopic-dev/appUser/alipay"
                  + "&out_trade_no="+payNo+"&spbill_create_ip="+payIp+""
                  + "&total_fee="+money+"&trade_type=APP"
                  + "&key=teamnavi888TWCLJ201601261451why8";

**Comment by xu-li** [comment]
应该iOS和Android的是一样的，因为签名都是后台做的。

请问你的插件版本是哪个？如果方便的话，能否把你的APP信息发到我邮箱，我晚上帮你看看？

**Comment by hyitclj** [comment]
邮箱多少哦

**Comment by hyitclj** [comment]
ios分享是可以用的，android付款是可以用的，ios付款是不行的，ios装的是1.1.3版本

**Comment by xu-li** [comment]
AthenaLightenedMyPath@gmail.com. 需要你的APP_ID, MCH_ID, APP_KEY. 如果是Android，还要你的package name。

**Comment by hyitclj** [comment]
thanks

**Comment by SuuSatoshigi** [comment]
遇到啊和hyitclj一样的问题。按照支付的readme。
var params = {
    partnerid: '10000100', // merchant id    这个是确认没问题
    prepayid: 'wx201411101639507cbf6ffd8b0779950874', 
                                         // prepay id 后台发来的package，我把prepay id取出来
    noncestr: '1add1a30ac87aa2db72f57a2375d8fec', // nonce 
    timestamp: '1439531364', // timestamp 
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
};
除了这几个参数还差什么么，iOS端。 APP_KEY在readme并没有提到要用和怎么提供。。

**Comment by xu-li** [comment]
@SuuSatoshigi 安装插件的时候提供了APP_KEY。

**Comment by SuuSatoshigi** [comment]
处理好了～thanks～
