### ISSUE TITLE
This plugin cannot work properly on android device

### ISSUE THREAD

**Issue by AndyHan1001** [xu-li/cordova-plugin-wechat#154]
I have to allow wechat login for my app. My app is built with ionic and meteor, which is a hybrid app. It works fine on ios device but failed on android device. By the way, my testing android device is nexus 6p

**Comment by xu-li** [comment]
It seems that your app signature is wrong. See [Official Document](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN).
