### ISSUE TITLE
I rebuild the app in a new laptop,cordova 6.00 and target 22, get below error on console

### ISSUE THREAD

**Issue by xiao1dian** [xu-li/cordova-plugin-wechat#156]
E/Cordova.Plugin.Wechat(5453) : Index 1 out of range [0...1]
E/Cordova.Plugin.Wechat(5453) : Index 1 out of range [0...1]

it works on the old window7 laptop, today I set up a mac laptop, get above errors.

**Comment by xiao1dian** [comment]
the details log is as below.


D/Cordova.Plugin.Wechat( 5453): sendAuthRequest is called. Callback ID: Wechat1135105740.
E/Cordova.Plugin.Wechat( 5453): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat( 5453): Auth request has been sent successfully.
D/Cordova.Plugin.Wechat(31784): plugin initialized.
D/Cordova.Plugin.Wechat(31784): isWXAppInstalled is called. Callback ID: Wechat1872258040.
D/Cordova.Plugin.Wechat(31784): sendAuthRequest is called. Callback ID: Wechat1872258045.
E/Cordova.Plugin.Wechat(31784): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat(31784): Auth request has been sent successfully.
D/Cordova.Plugin.Wechat(31784): sendAuthRequest is called. Callback ID: Wechat1872258046.
E/Cordova.Plugin.Wechat(31784): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat(31784): Auth request has been sent successfully.
D/Cordova.Plugin.Wechat(31784): sendAuthRequest is called. Callback ID: Wechat1872258047.
E/Cordova.Plugin.Wechat(31784): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat(31784): Auth request has been sent successfully.
D/Cordova.Plugin.Wechat(31784): sendAuthRequest is called. Callback ID: Wechat1872258048.
E/Cordova.Plugin.Wechat(31784): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat(31784): Auth request has been sent successfully.
D/Cordova.Plugin.Wechat(31784): sendAuthRequest is called. Callback ID: Wechat1872258049.
E/Cordova.Plugin.Wechat(31784): Index 1 out of range [0..1)
I/Cordova.Plugin.Wechat(31784): Auth request has been sent successfully.

**Comment by xu-li** [comment]
I'm afraid I haven't tested this plugin in Cordova 6, will do this week.

**Comment by xu-li** [comment]
Tested using cordova 6.0.0, and everything works fine.

Could you please paste your source code here? I suspect that you have used the wrong parameters.
