### ISSUE TITLE
报普通错误

### ISSUE THREAD

**Issue by hyitclj** [xu-li/cordova-plugin-wechat#157]
我在开放平台申请应用的时候，只填了ios端的，android端没填，现在android端支付报普通错误，ios端可以支付，什么问题啊？然后我把android端信息也填进去了，还是报普通错误，什么问题啊？求帮忙

**Comment by xu-li** [comment]
你的android能不能分享信息？如果不能，基本就是android的应用签名错了。

**Comment by hyitclj** [comment]
签名不会错的，软件签的，要不你试试我的账号，看能不能付款？

**Comment by hyitclj** [comment]
it's ok.Thanks

**Comment by xu-li** [comment]
请问是什么错误？

**Comment by whistlebabystar** [comment]
请问怎么解决的？我这里微信分享可以调用，但是支付的时候报普通错误

**Comment by xu-li** [comment]
@whistlebabystar 你的支付参数的签名错了。看一下我的那个DEMO，或者看一下以前的几个issue。

**Comment by hyitclj** [comment]
@xu-li @whistlebabystar 是审核？？我什么都没动，前一天晚上不能用，然后我把android平台的填写了，第二天上午也不能用，然后到中午就可以用了。。。奇葩

**Comment by whistlebabystar** [comment]
@xu-li 请问哪些参数需要生成签名呢？

**Comment by whistlebabystar** [comment]
@hyitclj 微信确实要审核一段时间，不过我用的是已上线的app的包名和签名及开发账号，所以不会存在这样的问题

**Comment by whistlebabystar** [comment]
@xu-li 搞定了，的确是参数签名的问题，弄了一个星期了，非常感谢！
