### ISSUE TITLE
请问这个插件支持微信支付吗？

### ISSUE THREAD

**Issue by likunNet** [xu-li/cordova-plugin-wechat#158]

**Comment by xu-li** [comment]
是的，可以参考文档。

On Mon, Feb 15, 2016 at 3:34 PM, likun_net <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xu-li/cordova-plugin-wechat/issues/158>.
>



-- 
Thanks.
--
Xu Li,  Shanghai, China
