### ISSUE TITLE
你好，之前我在其他项目用你的插件是可以授权登录的。但是你升级之后发现你的微信授权登录可以，但是回调不来，没有进去回调函数里面去。但是可以跳到微信授权登录。谢谢

### ISSUE THREAD

**Issue by AberGLJ** [xu-li/cordova-plugin-wechat#159]

**Comment by xu-li** [comment]
Android还是iOS啊？回到应用了么？日志里面有什么记录？

**Comment by AberGLJ** [comment]
ios的，回到应用了。

**Comment by AberGLJ** [comment]
日志里有个警告其他什么也没有

**Comment by xu-li** [comment]
所以，警告的内容是？还有，JS是不是有错误呢？删掉最新版的插件，用以前版本的呢？

**Comment by AberGLJ** [comment]
以前的我看过，没事，警告是微信返回来的正常警告。js按照文档一样

**Comment by AberGLJ** [comment]
THREAD WARNING: ['Wechat'] took '71.761963' ms. Plugin should use a background thread.这个是警告，我在成功回调那里加了console和原来您的alert但是都没有用，没走到那里，账号是正式的账号。

**Comment by xu-li** [comment]
那你用以前版本的插件可以么？ 我没记得我改过登录啊。

**Comment by AberGLJ** [comment]
奇怪的是我重新remove我的项目，再来是可以的，可能是我的项目有东西干扰到了。谢谢了。
