### ISSUE TITLE
在IOS上，微信分享，缩略图设置不了，显示微信默认的link图标

### ISSUE THREAD

**Issue by David-Pan** [xu-li/cordova-plugin-wechat#161]
Wechat.isInstalled(function (installed) {
        if (!installed) {
          alert("请先安装微信~");
        } else {
          Wechat.share({
            message: {
              title: "123",
              description: "123",
              thump: "img/456.png",
              mediaTagName: "TEST-TAG-001",
              messageExt: "这是第三方带的测试字段",
              messageAction: "<action>dotalist</action>",
              media: {
                type: Wechat.Type.LINK,
                webpageUrl: currentUrl
              }
            },
            //text:"微信分享测试",
            scene: Wechat.Scene.SESSION   // share to SESSION
          }, function () {
            $ionicLoading.show({template: '分享成功！', noBackdrop: true, duration: 2000});
          }, function (reason) {
            alert("微信分享失败，请重新试一次！失败原因: " + reason);
          });
        }
      }, function (reason) {
        alert("微信分享失败: " + reason);
      });

**Comment by xu-li** [comment]
```image/456.png```是什么图片？在哪里的？是iOS还是Android？什么版本的插件？

**Comment by richagain** [comment]
你看看是不是路径里面有"-"或是"_"字符。包含这两个字符其中的一个就会参数出错。

对你有帮助的话可以关注我的公众号“智助”。

**Comment by David-Pan** [comment]
http://7xlmph.com1.z0.glb.clouddn.com/ij0xm5pv/FlOm3DhPddUVVCnYA8HV0esbNbiR
这是测试图片路径。在IOS上，分享出去，显示的是微信默认那个链接图标，在Android上显示的是在微信开放平台上注册的应用图标。

**Comment by xu-li** [comment]
可能是因为没有文件后缀？没测试过，回头我试试。

**Comment by xu-li** [comment]
没问题，图片还是指定的链接。应该跟网速有关系。
