### ISSUE TITLE
ios 微信支付 参数格式错误

### ISSUE THREAD

**Issue by DemacL** [xu-li/cordova-plugin-wechat#162]
你好,请问安卓和ios可不可用同一个appid调用微信支付?我现在安卓端用你的这个插件没 问题 但是ios端调用的话报  参数格式错误的提示 不能启动微信  启动微信分享没有问题

**Comment by huyong36** [comment]
我正好刚才也调试了一下，是参数错误，android这边
        mch_id: '10000100', // merchant id
        prepay_id: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
        nonce: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
        timestamp: '1439531364', // timestamp
        sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
改成这样就行了

**Comment by DemacL** [comment]
params: {
    "partnerid": "1310604501",
    "prepayid": "wx201602182020490655e35d480821365382",
    "noncestr": "077E29B11BE80AB57E1A2ECABB7DA330",
    "timestamp": "1455798044",
    "sign": "F3B17E2A30CB9ABBEA88DCE3A522971D"
}           我的ios这边某次请求返回参数这样子的   Wechat.sendPaymentRequest(params, function() {}调用这个就报错了  说是  参数格式错误   是什么问题了？

**Comment by huyong36** [comment]
你把参数改成我上面的那种格式试试

**Comment by xu-li** [comment]
什么版本的插件？最新版的插件，两种格式在android和iOS都行的。

**Comment by DemacL** [comment]
那格式是跟安卓端一样   请问是不是需要在ios工程里面配置appid什么的？其他地方的问题呢？调不起来微信  谢谢各位了

**Comment by xu-li** [comment]
@DemacL 装插件的时候，会自动设置好的。

像你出现的情况，你可以用xcode打开，看看URL Type。参见[官方文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=1417694084&token=&lang=zh_CN)。

**Comment by DemacL** [comment]
那请问是不是生成的params值不对？没通过微信的验证？

**Comment by DemacL** [comment]
嗯  是这样的  我添加插件时候用的appid参数不是现在实际支付用的appid   会不会有影响了？xcode我自己手动改了appid为实际支付的appid还是同样的问题  是不是需要卸载重装？谢谢了

**Comment by DemacL** [comment]
嗯  是这样的  我添加插件时候用的appid参数不是现在实际支付用的appid   会不会有影响了？xcode我自己手动改了appid为实际支付的appid还是同样的问题  是不是需要卸载重装？谢谢了

**Comment by DemacL** [comment]
嗯  是这样的  我添加插件时候用的appid参数不是现在实际支付用的appid   会不会有影响了？xcode我自己手动改了appid为实际支付的appid还是同样的问题  是不是需要卸载重装？谢谢了

**Comment by xu-li** [comment]
卸载重装最安全。

支付的“**参数格式错误**”，有2种情况:
1. params是空的。
2. 没有所有必须的参数(partnerid, prepayid, ...)。

所以你还有可能是JS的问题。

**Comment by DemacL** [comment]
好的  谢谢  那我安卓ios用同一个appid是没问题的吧？

**Comment by xu-li** [comment]
没问题啊。

**Comment by DemacL** [comment]
好  十分感谢

**Comment by DemacL** [comment]
@huyong36 @xu-li    果然params改成这样就可以调用了mch_id: '10000100', // merchant id
prepay_id: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
nonce: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
timestamp: '1439531364', // timestamp
sign: '0CB01533B8C1EF103065174F50BCA001', // signed string   不知道为什么我的那种方式在安卓端可以调用 在IOS端就报错
