### ISSUE TITLE
安卓auth没有反应

### ISSUE THREAD

**Issue by garyganyang** [xu-li/cordova-plugin-wechat#164]
目前只有Android环境,
证书和签名都应该是对的,

微信平台上面填写的内容
Android平台
应用下载地址：未填写
应用签名：e0128c09905e8836ff6f4cacacac527a
包名：com.ionicframework.duobao430759

尝试auth的时候没有反应, 只有几行日志. 求问会是什么问题呢, 我需要做点什么来解决呢?
I/Sensors (  440): sns_pwr.c(279):acquiring wakelock
D/wpa_supplicant(20307): wlan0: Control interface command 'SIGNAL_POLL'
D/Cordova.Plugin.Wechat(24179): **sendAuthRequest is called. Callback ID: Wechat1839292435.**
E/Cordova.Plugin.Wechat(24179): Index 1 out of range [0..1)
I/Timeline(24179): Timeline: Activity_launch_request time:107850473
D/SystemAdController( 1464): Activity:ActivityInfo{238ecc36 com.tencent.mm.plugin.base.stub.WXEntryActivity}is not the default one
I/ActivityManager(  826): START u0 {flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras)} from uid 10162 on display 0
E/ActivityManager(  826): Invalid thumbnail dimensions: 0x0
V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb(24179): xu.li.test.cordova.plugin.wechat.MainActivity  onActivityPaused
D/PowerKeeperEventLogManager( 1852): notifyForegroundCompomentChanged ComponentInfo{com.tencent.mm/com.tencent.mm.plugin.base.stub.WXEntryActivity}
I/Timeline(  826): Timeline: App_transition_ready time:107850492
V/LocationPolicy(  826): onProcessStateChanged
I/Cordova.Plugin.Wechat(24179): **Auth request has been sent successfully.**
W/PluginManager(24179): THREAD WARNING: exec() call to Wechat.sendAuthRequest blocked the main thread for 37ms. Plugin should use CordovaInterface.getThreadPool().
W/ActivityManager(  826): getTasks: caller 10101 does not hold REAL_GET_TASKS; limiting output
E/ActivityManager(  826): Invalid thumbnail dimensions: 0x0

**Comment by xu-li** [comment]
怎么感觉是你参数传错了？

```
E/Cordova.Plugin.Wechat(24179): Index 1 out of range [0..1)
```

**Comment by garyganyang** [comment]
不好意思, 问题已经解决了,  弄了半天才用了不同的测试机才发现 是手机问题, 我的小米2S 更新了下系统就解决了.  一切工作正常目前
