### ISSUE TITLE
上传AppStore遇到的问题

### ISSUE THREAD

**Issue by hyitclj** [xu-li/cordova-plugin-wechat#167]
调用微信支付。。。iOS应用在AppStore上面被拒了，好像不允许使用微信支付，支付需要使用In-App Purchase，这个怎么绕过他呢？怎么办呢？因为我看到也有一些苹果应用可以使用微信支付啊，比如美团等

**Comment by hyitclj** [comment]
https://developer.apple.com/app-store/review/guidelines/
第11项

**Comment by ace68723** [comment]
@hyitclj  我们一般的做法是，检查一下有没有安装微信再调用，AppStore测试的时候一般不会装微信，可以绕开。你可以试试

**Comment by yaorunlong** [comment]
审核的时候不显示，审核完再显示
