### ISSUE TITLE
Share link 的时候出现Failed:JSON error

### ISSUE THREAD

**Issue by ilovetochangetheworld** [xu-li/cordova-plugin-wechat#169]
微信分享 text内容没问题，但是涉及到message：的时候就会出现Failed:JSON error。下面是代码：
 Wechat.share({
            message: {
              media: {
                type: Wechat.Type.LINK,
                webpageUrl: "http://tech.qq.com/zt2012/tmtdecode/252.htm"
              }
            },
            scene: Wechat.Scene.TIMELINE   // share to Timeline
          }, function () {
            alert("Success");
          }, function (reason) {
            alert("Failed: " + reason);
          });
按照例子上Share media也是同样的错误。

**Comment by xu-li** [comment]
我的demo里面的"..."的意思是省略，title和description是必填的。

```
Wechat.share({
    message: {
        title: "Hi, there", 
        description: "This is description.",
        thumb: "www/img/thumbnail.png", 
        media: {
            type: Wechat.Type.LINK,
            webpageUrl: "http://tech.qq.com/zt2012/tmtdecode/252.htm"
        }
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

```

**Comment by ilovetochangetheworld** [comment]
噢，原来是必填项。谢谢了
