### ISSUE TITLE
mac上 插件添加失败

### ISSUE THREAD

**Issue by giantss** [xu-li/cordova-plugin-wechat#172]
![4e4b151d-d7df-4562-b908-391f40b38d60](https://cloud.githubusercontent.com/assets/13778798/13803620/131d6f16-eb81-11e5-9f6c-1c316ef2ab3e.png)

cordova 版本 5.3.3

**Comment by xu-li** [comment]
你的网络好么？看起来好像是网络问题啊。

**Comment by wujianfei** [comment]
你可以先下载下来，然后直接拉进去，这样就很快了，应该不会有问题的，我的也是Mac
