### ISSUE TITLE
为什么要在安装插件的时候就把appID给赋值到安卓配置中

### ISSUE THREAD

**Issue by wujianfei** [xu-li/cordova-plugin-wechat#173]
为什么一定要在安装的时候，就把appID带到安卓配置中，我如果想动态更改怎么办？

**Comment by wujianfei** [comment]
我可以把pluginInitialize中的initWXAPI初始化方法写到execute中吗，会不会有影响，这样在动态调用的时候在赋值给appId并且动态调用初始化，这样做还有什么没考虑到的，比如多次初始化的时候，资源越来越大等问题。

**Comment by xu-li** [comment]
1. 因为每个申请的App都有一个ID和对应的包名等，应该不支持动态更改APP ID (没试过)。
2. 99%的人不需要动态修改APP ID。

**Comment by wujianfei** [comment]
是啊，但是我们有这需求，如果自己动手改就费劲了。

**Comment by GuoDapeng** [comment]
app id 填错了。得重构项目了。白折腾了。悲剧……

**Comment by xu-li** [comment]
重装plugin不行？或者查找替换呢？

**Comment by GuoDapeng** [comment]
删除后安装好了。这个插件真的很好用，谢谢^_^
