### ISSUE TITLE
分享链接下方服务号名称左边的Logo如何显示

### ISSUE THREAD

**Issue by destiny1020** [xu-li/cordova-plugin-wechat#175]
作者您好，

最近我在尝试使用您开发的插件，我发现在DEMO程序中每次分享下方有一个角标：Cordova插件，前面还有一个小logo。在我的分享链接中，服务号的名字能够正常显示，但是前面的小logo没有。

我想请问一下这个小logo是在哪里配置呢？我貌似没有看到程序里面有这个参数，猜想可能是要在服务号里面配置？但是我也没有发现这个配置项。

还请赐教！
谢谢！

**Comment by xu-li** [comment]
我用的是开放平台 <https://open.weixin.qq.com/>申请的，可以设置LOGO。

2016-03-22 22:24 GMT+08:00 destiny1020 <notifications@github.com>:

> 作者您好，
>
>
> 最近我在尝试使用您开发的插件，我发现在DEMO程序中每次分享下方有一个角标：Cordova插件，前面还有一个小logo。在我的分享链接中，服务号的名字能够正常显示，但是前面的小logo没有。
>
> 我想请问一下这个小logo是在哪里配置呢？我貌似没有看到程序里面有这个参数，猜想可能是要在服务号里面配置？但是我也没有发现这个配置项。
>
> 还请赐教！
> 谢谢！
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xu-li/cordova-plugin-wechat/issues/175>
>



-- 
Thanks.
--
Xu Li,  Shanghai, China
