### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by wflashy** [xu-li/cordova-plugin-wechat#176]
你好！
Android开发 转发微信好友出现 JSON error，我的应用签名也是正确填写了的，请问是什么问题？
IOS测试正常。

**Comment by xu-li** [comment]
能把你的代码贴一下么？ 可能是有些必要的参数你忘记加了。

**Comment by wflashy** [comment]
在Android和IOS都是用的这段代码。IOS正常，Android提示JSON error。
Wechat.isInstalled(function (installed) {
            if(installed=='NO'){
              $ionicLoading.show({
                template: "请安装微信！"
                ,noBackdrop:false
                ,duration:800
              });reutrn;}
            Wechat.share({
              message:{
                media: {
                  type: Wechat.Type.LINK,
                  webpageUrl:url
                }
              },
              scene: Wechat.Scene.SESSION
            },function(){
              $ionicPopup.alert({
                title: '提示',
                okType:'button-calm',
                template:'邀请成功!'
              });
            },function(reason){
              alert("Failed: " + reason);
            });

          }, function (reason) {
            alert("Failed: " + reason);
          });

**Comment by wflashy** [comment]
在Android和IOS都是用的这段代码。IOS正常，Android提示JSON error。
Wechat.isInstalled(function (installed) {
            if(installed=='NO'){
              $ionicLoading.show({
                template: "请安装微信！"
                ,noBackdrop:false
                ,duration:800
              });reutrn;}
            Wechat.share({
              message:{
                media: {
                  type: Wechat.Type.LINK,
                  webpageUrl:url
                }
              },
              scene: Wechat.Scene.SESSION
            },function(){
              $ionicPopup.alert({
                title: '提示',
                okType:'button-calm',
                template:'邀请成功!'
              });
            },function(reason){
              alert("Failed: " + reason);
            });
          }, function (reason) {
            alert("Failed: " + reason);
          });

**Comment by xu-li** [comment]
See #169 .
