### ISSUE TITLE
分享没缩略图

### ISSUE THREAD

**Issue by xueenda** [xu-li/cordova-plugin-wechat#177]
```
Wechat.share({
        message: {
          title: "专访张小龙：产品之上的世界观",
          description: "微信的平台化发展方向是否真的会让这个原本简洁的产品变得臃肿？",
          thumb: "http://d2okfajvs3iw45.cloudfront.net/post/image_1458214021645.jpg",
          media: {
            type: Wechat.Type.WEBPAGE,
            webpageUrl: "http://tech.qq.com/"
          }
        },
        scene: Wechat.Scene.TIMELINE   // share to Timeline
      }, function () {
        self.showDialog('', 'Success');
      }, function (reason) {
        self.showDialog('错误', reason);
      });
```

**Comment by xueenda** [comment]
后来我用的这个 图片地址 https://cordova.apache.org/images/cordova_256.png 也不行， 小于32k

**Comment by xueenda** [comment]
大的 小的 http https 图片都试了没一个好使得

**Comment by xu-li** [comment]
用的ionic么？[whitelist](https://cordova.apache.org/docs/en/5.0.0/guide/appdev/whitelist/)设置对了么？日志里面写的什么？

**Comment by xueenda** [comment]
对 whitelist 应该没问题 
<image src="https://cordova.apache.org/images/cordova_256.png"/> 
图片都能load 出来 嵌套的iframe 有http https 也没问题

**Comment by xu-li** [comment]
日志里面写的什么？

**Comment by xueenda** [comment]
咋看日志 我这个装的release版本 （Android studio？）
debug 版本 我用chrome html5 app inspector 看

**Comment by xu-li** [comment]
[Logcat](http://developer.android.com/tools/help/logcat.html)

**Comment by xueenda** [comment]
是不是我装了cordova plugin add cordova-plugin-file 就行了

permission问题

03-24 21:47:31.503 27895 27939 D Cordova.Plugin.Wechat: Start downloading file at http://n.sinaimg.cn/news/20160324/xkbh-fxqswxx0225043.jpg.
03-24 21:47:31.505 27895 27895 D cr_Ime  : [ImeAdapter.java:253] updateKeyboardVisibility: type [0->0], flags [0], show [true], 
03-24 21:47:31.505 27895 27895 D cr_Ime  : [ImeAdapter.java:326] hideKeyboard
03-24 21:47:31.505 27895 27895 D cr_Ime  : [InputMethodManagerWrapper.java:56] isActive: true
03-24 21:47:31.506 27895 27895 D cr_Ime  : [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow
03-24 21:47:32.239 27895 27939 W System.err: java.io.FileNotFoundException: /storage/emulated/0/cache/xkbh-fxqswxx0225043.jpg: open failed: EACCES (Permission denied)

**Comment by xu-li** [comment]
模拟器？你用真机试试呢？

**Comment by xueenda** [comment]
对啊 我用的真机试的 这样吧 你把微信分享需要的plugin 还有config.xml 该设的字段告诉我 这样方便点

**Comment by xu-li** [comment]
什么版本的android？

可以试试再加个权限:
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`到AndroidManifest.xml.

不需要其它插件，还有config.xml安装插件的时候，会自动设置。不放心的话，可以卸载，再重新安装插件。

**Comment by xueenda** [comment]
6.0.1 Nexus 5
行 我加上试试看

**Comment by xueenda** [comment]
加了read write permission都不行啊 好像有点问题
有可能你的代码用的ENV 参数不对 

你看看这个 stackoverflow

http://stackoverflow.com/questions/23527767/open-failed-eacces-permission-denied

**Comment by xueenda** [comment]
你好 我把Wechat.java 代码 481 那个if section 改成这个了
```
URL ImageUrl = new URL(url);

HttpURLConnection conn = (HttpURLConnection) ImageUrl.openConnection();
conn.setDoInput(true);
conn.connect();
try{
    inputStream = conn.getInputStream();
}catch (IOException e) {
    e.printStackTrace();
}
```
好使了

**Comment by xu-li** [comment]
多谢。

**Comment by xu-li** [comment]
测试了一下，Android API 23没有这个问题啊。

**Comment by xueenda** [comment]
那可能是我permission 不对吧
