### ISSUE TITLE
iOS的朋友圈分享里，无法粘贴

### ISSUE THREAD

**Issue by fxfred** [xu-li/cordova-plugin-wechat#178]
iOS 分享到朋友圈，“这一刻的想法…”里想粘贴些东西，但无法粘贴。而且，粘贴板里的内容也被自动清空了。
发给朋友的地方，也有同样问题。
不知如何解决？是否lib版本不对，还是调用参数有问题？
谢谢

**Comment by xu-li** [comment]
这个插件不提供UI，怎么会有这个问题？你用的是cordova,ionic,phonegap,还是其它？

**Comment by fxfred** [comment]
找到问题了。是wechat的lib要更新成最新的就好了。
