### ISSUE TITLE
安装插件把appid 写进去了，安卓机做测试的时候一直报未知错误

### ISSUE THREAD

**Issue by coolara** [xu-li/cordova-plugin-wechat#179]
需要在config里做什么配置，
除了分享Wechat.share  代码
还需要在项目里做什么修改呢
谢谢了
`config.xml加了<preference` name="wechatappid" value="wx5f70b602946*****" />

**Comment by coolara** [comment]
已经解决了，签名问题，
那个分享成功之后由用户选择返回app 还是微信怎么弄

**Comment by xu-li** [comment]
那个是微信SDK自己实现的，插件改不了。
