### ISSUE TITLE
微信授权登录页面不返回

### ISSUE THREAD

**Issue by ace68723** [xu-li/cordova-plugin-wechat#18]
iOS授权登录的时候点完ok就停在微信里面了，用的是你测试的id。不知道是不是ID的问题

**Comment by cheft** [comment]
我也有这种问题，点返回应用没反应

**Comment by xu-li** [comment]
@ace68723 , @cheft 是否已经设置了URL Type？可参照[官方的iOS接入指南](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN).

**Comment by ace68723** [comment]
@cheft 在info－URL Types－URL Schemes中添加微信开发品台上申请的AppID就可以了

**Comment by ace68723** [comment]
@xu-li 多谢:)
