### ISSUE TITLE
这个插件的微信支付功能怎么集成到安卓平台上？

### ISSUE THREAD

**Issue by xiaofazai** [xu-li/cordova-plugin-wechat#180]
要怎样配置？

**Comment by xu-li** [comment]
可以参考[官方文档](https://pay.weixin.qq.com/wiki/doc/api/index.html)。

**Comment by xu-li** [comment]
日志里面是什么？可以分享么? android的签名弄对了么？

**Comment by xiaofazai** [comment]
看不到日志是什么啊，我是打包好apk在手机上运行的，签名应该是没问题的

**Comment by xu-li** [comment]
可以分享图片或者链接么？
