### ISSUE TITLE
报普通错误

### ISSUE THREAD

**Issue by xiaofazai** [xu-li/cordova-plugin-wechat#181]
我把下面这段代码复制进点击事件里，在手机上提示普通错误
var params = {
    partnerid: '10000100', // merchant id
    prepayid: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
    noncestr: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
    timestamp: '1439531364', // timestamp
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
};

Wechat.sendPaymentRequest(params, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

**Comment by xu-li** [comment]
什么平台？android的话，签名对了么？

**Comment by xiaofazai** [comment]
是在Android平台的，签名对了的

**Comment by xu-li** [comment]
Logcat日志里面写的什么？
