### ISSUE TITLE
Unable to share to WeChat due to bad_param

### ISSUE THREAD

**Issue by flintcreativestudio** [xu-li/cordova-plugin-wechat#182]
之前好好的，不知道差不多一个月前一分享，微信打开后报：
 Sharing Error
Unable to share to WeChat due to bad_param

这是在iOS. 麻烦抢救！

Wechat.share({
              message: {
                  title: 'Test',
                  thumb: picture_url,
                  description: 'test',
                  media: {
                      type: Wechat.Type.LINK,
                      webpageUrl: test_url
                  }
              },
              scene: Wechat.Scene.TIMELINE
          }, function () {
              console.log('share success!');
          }, function (reason) {
              console.log(reason);
          });

PS: 今天检查了参数，发现 Wechat.Type.LINK 不存在，Wechat.Type.WEBPAGE 才存在，不过改了还是一样。之前用的 Wechat.Type.LINK 是好好的。

**Comment by xu-li** [comment]
额，从来没有Wechat.Type.LINK这个常量啊？你可以blame一下[wechat.js](https://github.com/xu-li/cordova-plugin-wechat/blame/develop/www/wechat.js). 

是不是你用了别的插件？

**Comment by flintcreativestudio** [comment]
App里点击分享，到达微信报错后，Xcode Log显示这个：

My-iPhone-5 networkd[91] <Error>: nw_interface_get_agents SIOCGIFAGENTIDS failed for interface "" (index 11, type other): [6] Device not configured

**Comment by flintcreativestudio** [comment]
还有什么可以测试的方法吗。。求救大师～

**Comment by xu-li** [comment]
你的日志能不能贴全一点？这个好像不是插件相关的。

**Comment by flintcreativestudio** [comment]
我去。。。weixin app id 少了一个字母 －－ 打扰了。
