### ISSUE TITLE
安卓下面的问题

### ISSUE THREAD

**Issue by moonlit77** [xu-li/cordova-plugin-wechat#183]
问题：
1.  protected boolean sendAuthRequest(CordovaArgs args, CallbackContext callbackContext) {
        final IWXAPI api = getWXAPI();

        final SendAuth.Req req = new SendAuth.Req();
        try {
            req.scope = args.getString(0);
            //对req.state赋值没有检查args的长度。ios是有的
            req.state = args.getString(1);  
2.cordOVA运行您给的例子
     a.分享报未知错误
     b.js里调用Wechat.auth，当微信本身处于未登陆状态,会调起微信，登陆了微信本身后，app收不到回调数据。
     c.登陆了微信本身后，调用Wechat.auth，就完全没反应，不会调起微信

**Comment by xu-li** [comment]
有没有错误日志？[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)对么？

**Comment by moonlit77** [comment]
非常感谢您的来信，问题我们已经解决了，是安卓签名没搞对。



庄华
 
发件人： lixu
发送时间： 2016-04-13 19:52
收件人： xu-li/cordova-plugin-wechat
抄送： moonlit77
主题： Re: [xu-li/cordova-plugin-wechat] 安卓下面的问题 (#183)
有没有错误日志？签名对么？

**Comment by moonlit77** [comment]
您好，问题已经解决了，是安卓app签名没搞对。
另外第一个问题，看漏了你的catch段的代码，代码是没问题的。
