### ISSUE TITLE
auth在安卓下面无法工作

### ISSUE THREAD

**Issue by wstygk** [xu-li/cordova-plugin-wechat#184]
如题，auth在安卓下面无法工作。

**Comment by xu-li** [comment]
有没有错误日志？[签名](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)对么？

**Comment by KuanYu0729** [comment]
我這裡也發生一樣的事
logcat:
`--------- beginning of main
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11777
--------- beginning of system
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:2999] from screen [on:0 period:419193026] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-5ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:419193028] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): notifying of data activity 1
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): notifying of data activity 0
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-5ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-58 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:2998] from screen [on:0 period:419196051] gl rssi=-58 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-58 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:419196053] gl rssi=-58 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-5ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-58 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.5 bcn=0 [on:0 tx:0 rx:0 period:3000] from screen [on:0 period:419199082] gl rssi=-58 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-58 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.5 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:419199084] gl rssi=-58 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.3 bcn=0 [on:0 tx:0 rx:0 period:3001] from screen [on:0 period:419202124] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-9ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.3 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:419202125] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.1 bcn=0 [on:0 tx:0 rx:0 period:3000] from screen [on:0 period:419205152] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-6ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.1 bcn=0 [on:0 tx:0 rx:0 period:2] from screen [on:0 period:419205154] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/chromium(19078): [ERROR:xwalk_autofill_client.cc(172)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-4ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.1 bcn=0 [on:0 tx:0 rx:0 period:2998] from screen [on:0 period:419208180] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-5ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.1 bcn=0 [on:0 tx:0 rx:0 period:5] from screen [on:0 period:419208185] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:3002] from screen [on:0 period:419211205] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:5] from screen [on:0 period:419211210] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11778
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11779
E/WifiTrafficPoller(  737): notifying of data activity 1
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12281 Rx=11781
E/MPlugin (16173): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
E/Vold    (  212): Failed to find mounted volume for /storage/sdcard1/Android/data/com.bbk.appstore/files/MqttConnection/
E/VoldCmdListener(  212): runCommand_may_async(), ret=400
E/PushSdk..Wave(16173): 151228-keyUrl is empty
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:2995] from screen [on:0 period:419214240] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-4ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.0, 0.0, 0.0  rx=0.0 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:419214241] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/NativeCrypto(16173): ssl=0xab362f08 cert_verify_callback x509_store_ctx=0xe3be95d8 arg=0x0
E/NativeCrypto(16173): ssl=0xab362f08 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12296 Rx=11792
E/WifiTrafficPoller(  737): notifying of data activity 3
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): notifying of data activity 0
E/chromium(19078): [ERROR:xwalk_autofill_client.cc(172)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
E/WifiStateMachine(  737):  ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=1.5 bcn=0 [on:0 tx:0 rx:0 period:3005] from screen [on:0 period:419217270] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-8ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=1.5 bcn=0 [on:0 tx:0 rx:0 period:3] from screen [on:0 period:419217273] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=8.8, 0.0, 0.0  rx=7.8 bcn=0 [on:0 tx:0 rx:0 period:3002] from screen [on:0 period:419220298] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,60,60,65] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=8.8, 0.0, 0.0  rx=7.8 bcn=0 [on:0 tx:0 rx:0 period:4] from screen [on:0 period:419220302] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,60,60,65] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11795
E/WifiStateMachine(  737):  ConnectedState (when=-6ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=4.4, 0.0, 0.0  rx=3.9 bcn=0 [on:0 tx:0 rx:0 period:2999] from screen [on:0 period:419223330] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-9ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=4.4, 0.0, 0.0  rx=3.9 bcn=0 [on:0 tx:0 rx:0 period:4] from screen [on:0 period:419223334] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): notifying of data activity 1
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): notifying of data activity 0
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiStateMachine(  737):  ConnectedState (when=-3ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=2.2, 0.0, 0.0  rx=1.9 bcn=0 [on:0 tx:0 rx:0 period:2994] from screen [on:0 period:419226361] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-7ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=2.2, 0.0, 0.0  rx=1.9 bcn=0 [on:0 tx:0 rx:0 period:3] from screen [on:0 period:419226364] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiStateMachine(  737):  ConnectedState (when=-6ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=1.1, 0.0, 0.0  rx=1.5 bcn=0 [on:0 tx:0 rx:0 period:2998] from screen [on:0 period:419229392] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-14ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=1.1, 0.0, 0.0  rx=1.5 bcn=0 [on:0 tx:0 rx:0 period:8] from screen [on:0 period:419229400] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiStateMachine(  737):  ConnectedState (when=-1ms what=131143 arg1=10060 arg2=18) !CMD_START_SCAN 10060 18 ic=1 proc(ms):2 dur:1700 rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=0.7 fiv=20000 [on:0 tx:0 rx:0 period:2964] from screen [on:0 period:419232371]
E/WifiStateMachine(  737):  L2ConnectedState (when=-12ms what=131143 arg1=10060 arg2=18) !CMD_START_SCAN 10060 18 ic=1 proc(ms):13 dur:1700 rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=0.7 fiv=20000 [on:0 tx:0 rx:0 period:10] from screen [on:0 period:419232381]
E/WifiStateMachine(  737): WifiStateMachine CMD_START_SCAN source 10060 txSuccessRate=0.55 rxSuccessRate=0.73 targetRoamBSSID=any RSSI=-56
E/WifiStateMachine(  737): stopReconnectWifi Wfd=false StopScan=false mDontReconnectAndScan=false
E/WifiMonitor(  737): handleEvent unknown: 15  CTRL-EVENT-SCAN-STARTED
E/WifiStateMachine(  737): [1,460,708,113,031 ms] noteScanstart no scan source
E/WifiStateMachine(  737):  ConnectedState (when=0 what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=0.7 bcn=0 [on:0 tx:0 rx:0 period:13] from screen [on:0 period:419232404] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-2ms what=131155 arg1=15!CMD_RSSI_POLL 15 0 "Youholder" 00:24:a5:b4:cc:eb rssi=-56 f=2462 sc=80 link=65 tx=0.5, 0.0, 0.0  rx=0.7 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:419232405] gl rssi=-56 ag=0 hr ticks 0,0,2 ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  737):  get link layer stats 0
E/WifiStateMachine(  737): calculateWifiScore() we set wifi's score to 80. old score 60
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiTrafficPoller(  737): TRAFFIC_STATS_POLL true Token 131 num clients 12
E/WifiTrafficPoller(  737):  packet count Tx=12299 Rx=11796
E/WifiStateMachine(  737):  ConnectedState (when=-14ms what=147461!SCAN_RESULTS_EVENT 0 0 found=17 known=0 got=17 bcn=0
E/WifiStateMachine(  737):  L2ConnectedState (when=-16ms what=147461!SCAN_RESULTS_EVENT 0 0 found=17 known=0 got=17 bcn=0
E/WifiStateMachine(  737):  ConnectModeState (when=-17ms what=147461!SCAN_RESULTS_EVENT 0 0 found=17 known=0 got=17 bcn=0
E/WifiStateMachine(  737):  DriverStartedState (when=-17ms what=147461!SCAN_RESULTS_EVENT 0 0 found=17 known=0 got=17 bcn=0
E/WifiStateMachine(  737):  SupplicantStartedState (when=-18ms what=147461!SCAN_RESULTS_EVENT 0 0 found=17 known=0 got=17 bcn=0
E/WifiStateMachine(  737): [1,460,708,114,865 ms] noteScanEnd WorkSource{10060}
E/WifiStateMachine(  737): wifi setScanResults statecom.android.server.wifi.WifiStateMachine$ConnectedState@1f1a5a46 sup_state=COMPLETED debouncing=false
E/WifiStateMachine(  737):  ConnectedState (when=-1ms what=131131 arg1=10013!CMD_GET_CONFIGURED_NETWORKS uid=10013 10013 0 num=5
E/WifiStateMachine(  737):  L2ConnectedState (when=-1ms what=131131 arg1=10013!CMD_GET_CONFIGURED_NETWORKS uid=10013 10013 0 num=5
E/WifiStateMachine(  737):  ConnectModeState (when=-2ms what=131131 arg1=10013!CMD_GET_CONFIGURED_NETWORKS uid=10013 10013 0 num=5
`
簽名也對，分別是Lenovo、ViVo、Huawei P7

**Comment by xu-li** [comment]
没看到问题啊？不工作是指没调起微信么？如果是，那基本就是签名错了。

**Comment by KuanYu0729** [comment]
我是用同一份簽名包多個apk，在別的apk可以順利調起微信

**Comment by xu-li** [comment]
签名包你指的是keystore么？这个没问题，但是你最后算出来的签名要和你在微信管理后台设置的签名一致。

**Comment by KuanYu0729** [comment]
我現在是簽名一致，如果微信處於未登入的狀態，WeChat會順利開啟讓我登入，但授權頁面就不會再出來了

**Comment by KuanYu0729** [comment]
專案重建後又沒事了....
