### ISSUE TITLE
ios调转白屏的问题，在android端是正常的，

### ISSUE THREAD

**Issue by glweijiazhi** [xu-li/cordova-plugin-wechat#185]
@xu-li 你好，我也遇到ios调转白屏的问题，在android端是正常的，跪求帮看看！！！！不胜感激
我的代码如下：
  var payKey = "appid=wx455af6cafe0fd542&noncestr="+nonce_str+"&package=Sign=WXPay&partnerid=1303123701&prepayid=" + “prepayid已经正确返回 +"&timestamp=" +  timestamp  + "&key=正确的key";
                           var paysign = hex_md5(payKey).toLocaleUpperCase();
                               var params = {
                                   partnerid: '1303123701', 
                                   prepayid: “prepayid已经正确返回”, 
                                   noncestr:noncestrPay, // nonce
                                   timestamp:timestamp, 
                                   sign: paysign 
                               };
                              
                               Wechat.sendPaymentRequest(params, function () {
                                   alert("支付成功");
                                
                               }, function (reason) {
                                   Const.hideLoading();
                                   alert("支付失败，错误原因：: " + reason);
                               });

**Comment by xu-li** [comment]
白屏是不是只有一个确定的按钮？

如果是，就是你的参数错了(很可能是签名)。
