### ISSUE TITLE
auth在安卓下面无法工作

### ISSUE THREAD

**Issue by wstygk** [xu-li/cordova-plugin-wechat#186]
具体表现是第一次调用时界面一闪而过。也不报错，控制台也无信息可看。后面无论如何调用auth，都没有反应。请教什么原因。
注：安装时appid是赋值了的

**Comment by sharpest1221** [comment]
我也出现auth没反应的问题，android下。好像成功调起了一次，比较诡异。。。

**Comment by xu-li** [comment]
我觉得是android的签名问题。除了认证，分享可以正常么？如果分享也不行，那就是android的签名问题。

**Comment by Micjoyce** [comment]
@xu-li 对于android认证有没有wiki可以参考呢？ 我也遇到这个问题，在ios中可以登录，但是在android中即时时分享也会跳转弹出  “未知错误”

**Comment by xu-li** [comment]
签名问题。参见[官方文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。
