### ISSUE TITLE
微信未登录时, app请求授权，跳转至微信app，不登陆直接点返回按钮，没有回调任何信息

### ISSUE THREAD

**Issue by bopro** [xu-li/cordova-plugin-wechat#187]
如题
点击返回没有任何callback，都不知道没授权成功。能加嘛？ 在哪加合适？

**Comment by xu-li** [comment]
你的代码怎么写的？日志里面写的什么？ 应该会调用回调函数的。

**Comment by bopro** [comment]
Wechat.auth('snsapi_userinfo', +new Date(), function(response){

          alert(JSON.stringify(response));

        }, function(faild){

          alert('wechat faild');

        });


没有任何日志 点击返回应该是走alert('wechat faild'); 才是预期该走的对吧？

**Comment by xu-li** [comment]
是的。日志我指的是android的LOGCAT里面的。看一下。

**Comment by moonlit77** [comment]
八成是微信开放平台注册的app签名不对，网上找找安卓app签名的攻略

**Comment by bopro** [comment]
@moonlit77 不点返回, 去登陆的话能正常授权。 只是打印不出来logcat, 所以不知道什么问题。万恶的x党，啥都墙。

**Comment by bopro** [comment]
05-06 19:33:57.948 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: you.test.app.MainActivity  onActivityResumed
05-06 19:33:58.018 21276-21276/you.test.app I/ActivityManager: Timeline: Activity_idle id: android.os.BinderProxy@29a997e8 time:107035180
05-06 19:33:58.758 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
05-06 19:33:59.888 21276-21341/you.test.app D/Cordova.Plugin.Wechat: isWXAppInstalled is called. Callback ID: Wechat621343517.
05-06 19:33:59.988 21276-21341/you.test.app D/Cordova.Plugin.Wechat: sendAuthRequest is called. Callback ID: Wechat621343518.
05-06 19:33:59.998 21276-21341/you.test.app I/ActivityManager: Timeline: Activity_launch_request id:com.tencent.mm time:107037162
05-06 19:33:59.998 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: you.test.app.MainActivity  onActivityPaused
05-06 19:34:00.008 21276-21341/you.test.app I/Cordova.Plugin.Wechat: Auth request has been sent successfully.
05-06 19:34:00.278 21276-21276/you.test.app W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
05-06 19:34:00.798 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onBackground
这是点击返回按钮后的3行日志
05-06 19:34:02.998 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: you.test.app.MainActivity  onActivityResumed
05-06 19:34:03.028 21276-21276/you.test.app I/ActivityManager: Timeline: Activity_idle id: android.os.BinderProxy@29a997e8 time:107040195
05-06 19:34:03.798 21276-21276/you.test.app V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
@xu-li

**Comment by xu-li** [comment]
这个日志是正常的，可能需要直接到android的代码里面调试了。

换个手机，是否正常呢？

**Comment by Nataila** [comment]
为什么我用android的话，点击微信登录无法调出微信？  

  el.find('.wx-signin').on 'click', ->
  ┊ newDate = +new Date()
  ┊ scope = "snsapi_userinfo"
  ┊ state = "_#{newDate}"
  ┊ Wechat.auth scope, state, (args) ->
  ┊ ┊ loginApiReq(args, 'weixin')
  ┊ , (fail) ->
  ┊ ┊ return notify("登录失败")

Wechat.auth scope, state, (args) -> 这句没有执行？？

**Comment by yangchengwork** [comment]
请教，我在iOS可以运行，但在小米Note pro上有如下log，请教如何定位问题。谢谢
06-22 17:49:57.000 I/chromium(14530): [INFO:CONSOLE(41)] "wechat test ", source: file:///android_asset/www/js/index.js (41)
06-22 17:49:57.000 E/ActivityManager( 1109): Invalid thumbnail dimensions: 0x0
06-22 17:49:57.000 W/InputMethodManagerService( 1109): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@33a16299 attribute=null, token = android.os.BinderProxy@3cfe73fe
06-22 17:49:57.010 V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb(14530): com.gump.sulong.http.test.MainActivity  onActivityPaused
06-22 17:49:57.020 I/Cordova.Plugin.Wechat(14530): Auth request has been sent successfully.
06-22 17:49:57.020 W/PluginManager(14530): THREAD WARNING: exec() call to Wechat.sendAuthRequest blocked the main thread for 34ms. Plugin should use CordovaInterface.getThreadPool().
06-22 17:49:57.020 D/PowerKeeperEventLogManager( 4574): notifyForegroundCompomentChanged ComponentInfo{com.tencent.mm/com.tencent.mm.plugin.base.stub.WXEntryActivity}
06-22 17:49:57.030 I/Timeline( 1109): Timeline: App_transition_ready time:332776221
06-22 17:49:57.040 V/LocationPolicy( 1109): writePolicyLocked()
06-22 17:49:57.080 W/ActivityManager( 1109): getTasks: caller 10146 does not hold REAL_GET_TASKS; limiting output
06-22 17:49:57.110 I/Timeline( 1109): Timeline: App_transition_ready time:332776303
06-22 17:49:57.110 E/ActivityManager( 1109): Invalid thumbnail dimensions: 0x0
06-22 17:49:57.120 W/ActivityManager( 1109): Finishing task with all activities already finished
06-22 17:49:57.120 W/ActivityManager( 1109): Duplicate finish request for ActivityRecord{173dde12 u0 com.tencent.mm/.plugin.base.stub.WXEntryActivity t13639 f}
06-22 17:49:57.120 W/InputMethodManagerService( 1109): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@317c95e attribute=null, token = android.os.BinderProxy@3cfe73fe
06-22 17:49:57.120 D/PowerKeeperEventLogManager( 4574): notifyForegroundCompomentChanged ComponentInfo{com.gump.sulong.http.test/com.gump.sulong.http.test.MainActivity}
06-22 17:49:57.130 I/Timeline( 1109): Timeline: App_transition_ready time:332776324
06-22 17:49:57.130 V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb(14530): com.gump.sulong.http.test.MainActivity  onActivityResumed
06-22 17:49:57.150 I/Timeline(14530): Timeline: Activity_idle id: android.os.BinderProxy@1c153f6b time:332776344
06-22 17:49:57.160 W/ActivityManager( 1109): getTasks: caller 10146 does not hold REAL_GET_TASKS; limiting output
06-22 17:49:57.210 I/Timeline( 1109): Timeline: App_transition_stopped time:332776405
06-22 17:49:57.230 W/System.err( 3389): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
06-22 17:49:57.230 W/System.err( 3389): 	at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:98)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:393)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
06-22 17:49:57.230 W/System.err( 3389): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.HttpUtil.accessInternetByPost(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.WebApiAccessHelper.accessInternetByPost(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.WebApiAccessHelper.checkRichPurchaseOnlineResult(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager.updateNaTrafficPurchaseStatus(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager.access$000(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager$1.run(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-22 17:49:57.230 W/System.err( 3389): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-22 17:49:57.230 W/System.err( 3389): 	at java.lang.Thread.run(Thread.java:818)
06-22 17:49:57.230 W/System.err( 3389): org.json.JSONException: Value No of type java.lang.String cannot be converted to JSONObject
06-22 17:49:57.230 W/System.err( 3389): 	at org.json.JSON.typeMismatch(JSON.java:111)
06-22 17:49:57.230 W/System.err( 3389): 	at org.json.JSONObject.<init>(JSONObject.java:160)
06-22 17:49:57.230 W/System.err( 3389): 	at org.json.JSONObject.<init>(JSONObject.java:173)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.RequestResult.parseJson(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.RequestResult.<init>(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.FeatureOnlineResult.<init>(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.PurchaseOnlineResult.<init>(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.webapi.WebApiAccessHelper.checkRichPurchaseOnlineResult(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager.updateNaTrafficPurchaseStatus(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager.access$000(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at com.miui.networkassistant.traffic.purchase.CooperationManager$1.run(Unknown Source)
06-22 17:49:57.230 W/System.err( 3389): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-22 17:49:57.230 W/System.err( 3389): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-22 17:49:57.230 W/System.err( 3389): 	at java.lang.Thread.run(Thread.java:818)
06-22 17:49:57.230 I/CooperationManager( 3389): mina updateNaTrafficPurchaseStatus no response
06-22 17:49:57.380 D/WhetstoneService( 4126): deal background too Frequently, ingore
06-22 17:49:57.560 D/SecurityCenter( 4639): memDiff : 78, timeDiff : 1466588997562
06-22 17:49:57.560 D/SecurityCenter( 4639): cycle_memory
06-22 17:49:57.560 D/SecurityCenter( 4639): screen on : true, enable : true
06-22 17:49:57.560 D/SecurityCenter( 4639): notifyNotification
06-22 17:49:57.580 D/PhoneStatusBar( 3185): updateNotification pkg=com.miui.securitycenter;id=20004
06-22 17:49:57.930 V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb(14530): WXStat trigger onForeground
06-22 17:49:57.980 I/XiaomiFirewall( 3389): firewall pkgName:com.gump.sulong.http.test, result:0x0

**Comment by yangchengwork** [comment]
尝试更新libammsdk.jar文件后没有出现Error，但还是无法授权
