### ISSUE TITLE
使用xcode打包时总报错

### ISSUE THREAD

**Issue by merlin-li** [xu-li/cordova-plugin-wechat#191]
ld: bitcode bundle could not be generated because '/Users/mouri/Desktop/dream/xinrenshe/platforms/ios/信人社/Plugins/cordova-plugin-wechat/libWeChatSDK.a(WapAuthHandler.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xu-li** [comment]
See #137.
