### ISSUE TITLE
android闪退

### ISSUE THREAD

**Issue by jiaxiaxia** [xu-li/cordova-plugin-wechat#194]
在android上分享成功之后出现闪退现象

**Comment by xu-li** [comment]
LOGCAT日志里面是什么？

**Comment by jiaxiaxia** [comment]
我是直接按装到手机上的。不会看logcat啊

**Comment by jiaxiaxia** [comment]
点击分享之后，就程序停止运行了。但是到微信盆友圈看的时候，已经分享成功了。会是什么问题啊

**Comment by jiaxiaxia** [comment]
但是在ios一切都很好

**Comment by jiaxiaxia** [comment]
求指点迷津，实在找不出来是什么原因啊

**Comment by xu-li** [comment]
ios如果正常，但是android不正常，基本是签名问题。

LOGCAT可以看android官网上怎么查看。

**Comment by jiaxiaxia** [comment]
我重新装了一下插件，就好了。谢谢大神
