### ISSUE TITLE
Android分享至朋友圈崩溃

### ISSUE THREAD

**Issue by dada0z** [xu-li/cordova-plugin-wechat#196]
@xu-li 大神你好
**分享到朋友圈ios正常，Android程序崩溃。
朋友圈查看分享成功
包名签名通过GenSignature查看与微信平台上的一样。**
[由于github上传文件不成功，所以我把logcat抓到的所有log放在了这个地址。](https://github.com/dada0z/dada0z.github.io/blob/master/file/log.zip)
烦请有时间，帮忙看一眼。

**Comment by xu-li** [comment]
好像你安装的时候没有装对。建议你重新装一下插件，并确保com.shequdaren.active.wxapi.WXEntryActivity 这个文件存在。如果还不行，就从我的插件源代码里面，手动拷贝一下这些文件("EntryActivity.java", "WXEntryActivity.java", "WXPayEntryActivity.java")，并修改包名。

错误在这里: 
```
E/MtaSDK  (14233): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.shequdaren.active/com.shequdaren.active.wxapi.WXEntryActivity}: java.lang.ClassNotFoundException: Didn't find class "com.shequdaren.active.wxapi.WXEntryActivity" on path: DexPathList[[zip file "/data/app/com.shequdaren.active-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.shequdaren.active-1, /vendor/lib, /system/lib]]
```

**Comment by xu-li** [comment]
#194 可能相关。

**Comment by dada0z** [comment]
非常感谢！
问题解决了，可以关闭了。
