### ISSUE TITLE
能否提供 ionic2 的版本。。。

### ISSUE THREAD

**Issue by boboxiaodd** [xu-li/cordova-plugin-wechat#197]
ionic2 安装这个plugin 后，无法使用 Wechat 对象

**Comment by xu-li** [comment]
ionic2还没看过，回头我看一下。

**Comment by boboxiaodd** [comment]
我试过了，Wechat是全局变量，可以直接用，只是TS编辑器会提示 Wechat未定义，但还是能正常使用。

**Comment by SummerFans** [comment]
wechat为什么不是在windows.plugins里面

**Comment by 799956381** [comment]
ionic2
我的直接报错了“cannot find name wechat” @boboxiaodd @xu-li

**Comment by Asher-Wall** [comment]
能正常使用？？？？都调不到？怎么使用？ @boboxiaodd

**Comment by Asher-Wall** [comment]
ionic2+angular2能正常使用？？？？都调不到？怎么使用？来来来，把你调用的导入写法贴出来让急需的人看看@boboxiaodd

**Comment by universalMachine** [comment]
给大家提供一个简单的方案
如果一个page需要用到Wechat，可以在它的ts里面import的下一行加上
declare var Wechat:any;
这样就可以在ts里面使用Wechat变量了

**Comment by SummerFans** [comment]
支付宝也是可以这样的
![image](https://cloud.githubusercontent.com/assets/5702450/20660575/5e4eb264-b585-11e6-90cd-d418ffdd5350.png)

**Comment by zhengmin4516** [comment]
```
var scope = "snsapi_userinfo",
    state = "_" + (+new Date());
			Wechat.auth(scope, state, response =>  {
          this.getInfo(response.code);

			}, reason => {
			    alert("Failed: " + reason);
		});
```
ionic2 要换成这种写法，不然`this.getInfo()`报错
