### ISSUE TITLE
微信支付成功,点击完成,APP就错误,重启.不知道是不是以下问题导致的

### ISSUE THREAD

**Issue by XIQLiang** [xu-li/cordova-plugin-wechat#198]
打包的时候提示:
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.b.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
刚刚接触ionic ,对java也不熟,望能解答一下.这个warning问题应该怎么解决.

**Comment by XIQLiang** [comment]
"EntryActivity.java", "WXEntryActivity.java", "WXPayEntryActivity.java"这几个文件在platforms中没找到,重新安装也是没有,如果收到的安装的话, 是不是需要复制到 src/packageName/wxapi/文件夹中?

**Comment by xu-li** [comment]
是的。

**Comment by XIQLiang** [comment]
刚才试了,支付完没错了,非常感谢! 但支付前提示普通错误,重新支付一次才可以.

**Comment by XIQLiang** [comment]
参数中 spbill_create_ip   是::1  不知道是不是这个问题.

**Comment by XIQLiang** [comment]
解决了,是我的APPID,弄错了.

**Comment by XIQLiang** [comment]
感谢作者提供插件,及帮助!

**Comment by xu-li** [comment]
没事。解决了就好。

**Comment by 236xzl** [comment]
Object {partnerid: "1345012201", prepayid: "wx20160524154806677792e3f80741382465", noncestr: "4EPeY8zathMkNc7R", timestamp: "1464239867167", sign: "30DA136114C8F4AF708FCC55C7B95F5B"} 
这些是我的参数，支付的时候报普通错误是什么情况？？

**Comment by XIQLiang** [comment]
缺少参数吧!
看看这里https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_12&index=2,

**Comment by cbx1024** [comment]
一直提示普通错误，是怎么回事呢！我的参数：
var params = {
			partnerid: 'wxb4ba3c02aa476ea1',
			package: 'Sign=WXPay',			
			partnerid: '1305176001', // merchant id
			prepayid: 'wx2016052814505302370e6ea70856260150', // prepay id
			noncestr: 'bb7514fdc793ea87e588235a0c61bf0a', // nonce
			timestamp: '1464418253', // timestamp
			sign: 'E5B862E3AE52535FEA883DB45150869E', // signed string
		};

**Comment by xu-li** [comment]
不是缺少参数，就是你的APP签名不对。你能分享链接什么的么？ @cbx1024

**Comment by cbx1024** [comment]
分享不了只是界面看到闪了一下，不过ios那边到时能够正常使用（同样的参数）

**Comment by cbx1024** [comment]
@xu-li 这是提示“普通错误”的日志信息
05-31 15:47:17.714 4241-4241/com.cbx.weixinpay I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@18f0ed16 time:65736024
05-31 15:47:18.444 4241-4241/com.cbx.weixinpay V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
05-31 15:47:26.973 4241-4440/com.cbx.weixinpay D/Cordova.Plugin.Wechat: sendPaymentRequest is called. Callback ID: Wechat1484519176.
05-31 15:47:26.983 4241-4440/com.cbx.weixinpay I/Timeline: Timeline: Activity_launch_request time:65745291
05-31 15:47:26.993 4241-4241/com.cbx.weixinpay V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.cbx.weixinpay.MainActivity  onActivityPaused
05-31 15:47:27.003 4241-4440/com.cbx.weixinpay I/Cordova.Plugin.Wechat: Payment request has been sent successfully.
05-31 15:47:27.003 4241-4440/com.cbx.weixinpay W/PluginManager: THREAD WARNING: exec() call to Wechat.sendPaymentRequest blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool().
05-31 15:47:27.303 4241-4241/com.cbx.weixinpay W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
05-31 15:47:27.793 4241-4241/com.cbx.weixinpay V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onBackground
05-31 15:48:00.675 4241-4241/com.cbx.weixinpay D/Cordova.Plugin.Wechat: com.tencent.mm.sdk.modelpay.PayResp@240f7257
05-31 15:48:00.695 4241-4241/com.cbx.weixinpay V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.cbx.weixinpay.MainActivity  onActivityResumed
05-31 15:48:00.846 4241-4241/com.cbx.weixinpay I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@18f0ed16 time:65779152
05-31 15:48:01.496 4241-4241/com.cbx.weixinpay V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground
