### ISSUE TITLE
安装了插件之后，调用支付功能，APP崩溃！

### ISSUE THREAD

**Issue by 236xzl** [xu-li/cordova-plugin-wechat#199]
我看了下报错信息， Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zgtg.app.wxapi.WXPayEntryActivity" on path: DexPathList[[zip file "/data/app/com.zgtg.app-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zgtg.app-2, /vendor/lib, /system/lib]]

**Comment by xu-li** [comment]
See #198

**Comment by 236xzl** [comment]
是不是要在我的包名下面建立一个wxapi的文件夹，然后把那三个文件复制进去，这样就可以了，我这么做之后还是报错，同样的错误

**Comment by cbx1024** [comment]
@xu-li 
@XIQLiang 
一直提示普通错误，是怎么回事呢！
我的参数：
var params = {
appid: 'wxb4ba3c02aa476ea1',
package: 'Sign=WXPay',

partnerid: '1305176001', // merchant id
prepayid: 'wx2016052814505302370e6ea70856260150', // prepay id
noncestr: 'bb7514fdc793ea87e588235a0c61bf0a', // nonce
timestamp: '1464418253', // timestamp
sign: 'E5B862E3AE52535FEA883DB45150869E', // signed string
};

日志：
05-28 16:15:33.621: W/PluginManager(21399): THREAD WARNING: exec() call to Wechat.sendPaymentRequest blocked the main thread for 61ms. Plugin should use CordovaInterface.getThreadPool().
