### ISSUE TITLE
微信登录没有完成实现？

### ISSUE THREAD

**Issue by xiuxiu** [xu-li/cordova-plugin-wechat#20]
你好，目前通过auth命令获得code，接下来按照文档应该获取access_token，完成登录。

所以这部分是还没有实现的意思是吗

**Comment by landys** [comment]
获得code之后，其实已经完成授权。一般还需要发两次请求，先获得access_token和open_id，再获得用户基本信息。这两次请求可以放在客户端，也可以放在服务器端完成，这个用户自己选择实现。

**Comment by xiuxiu** [comment]
了解。就是想确认下这个project的实现情况，源代码里面没有看到。

这样的话html拿到code还要再发起一次ajax请求去走下面两步略有点不顺，怪怪的感觉。

**Comment by xu-li** [comment]
官方SDK里面也是这么做的。就像 @landys 说的，你可以放在客户端，也可以放在服务端，比较自由吧。
