### ISSUE TITLE
弹出2次授权窗口

### ISSUE THREAD

**Issue by zilinxueyue** [xu-li/cordova-plugin-wechat#202]
Hi, xuli
   谢谢你的解答 现在能分享了。不过出现一个问题，我按照一下的方式调用：
 Wechat.isInstalled(function (installed) {
        WEIXININSTALL=installed;
    });

    /***************微信登录**************/
        //var scope = "snsapi_userinfo";
    Wechat.auth("snsapi_userinfo", function (response) {
        // you may use response.code to get the access token.
        alert(JSON.stringify(response));
    }, function (reason) {
        alert("Failed: " + reason);
    });

    Wechat.share......

调到登录微信界面后我需要返回2次can能回到app. 就是弹出了2次授权登录的界面。 请问一下这个要怎么解决？ 可以把 share的代码放进 auth success 里面吗？ 顺便问下 auth的response.code 分别代表什么

谢谢！

**Comment by xu-li** [comment]
弹两次授权，可能是你的代码写错了。

可以把share放进success里面，但是没必要把？

response.code用来换取access token，你可以参考一下官方文档。

**Comment by zilinxueyue** [comment]
额 我就是按照 先
Wechat.isInstalled
Wechat.auth
Wechat.share
这个顺序调用的。有什么地方需要修正没有
Thanks

**Comment by xu-li** [comment]
这3个函数都可以单独调用，无所谓顺序，看你业务需求来定。
