### ISSUE TITLE
怎么直接返回APP内部页面，不要重新初始化APP

### ISSUE THREAD

**Issue by raymondjhs** [xu-li/cordova-plugin-wechat#203]
从APP内部某个页面分享成功后返回APP，每次都会自动重新初始化APP。您遇到过这问题吗？
能不能直接返回原来分享的那个页面？怎么实现？

**Comment by xu-li** [comment]
不会重新初始化啊，只有内存不够了，才会重新初始化。

**Comment by raymondjhs** [comment]
我用你的demo试验了一下。

将app.js文件代码改了一个地方，$urlRouterProvider.otherwise('/tab/about');，也就是app打开后的默认页面是About.

切换到Demo，分享成功后，返回App，这时App自动切换到About页面。

请问有没有办法直接返回到Demo页面？

**Comment by hxzAugustinus** [comment]
我测试时，点返回会重启app，不知道什么原因

**Comment by fsorange** [comment]
我也遇到此问题，请问各大神如何解决？

**Comment by xiaoyuan518** [comment]
我也出现这个问题了,一开始是可以回到分享前的页面的,但是后来platform报错,我重新安装platform以后就不行了,app总是重新启动,而且也不能分享了,这是什么原因呢?哪位大神可以解决?

**Comment by xiaoyuan518** [comment]
会出现"很抱歉,xxx应用已经停止运行."

**Comment by zhengdewei0817** [comment]
我想了个曲线救国的方法  应该并不是APP重启了  只是路由跳转了   所以我把需要跳转回来的逻辑写在了$rootscope中  这样就不至于调不到了   不知道有没有更好的方法

**Comment by raymondjhs** [comment]
找到答案了，在config.xml文件加一行
<preference name="AndroidLaunchMode" value="singleTask" />

**Comment by raymondjhs** [comment]
找到答案了，在config.xml文件加一行
`<preference name="AndroidLaunchMode" value="singleTask" />`

**Comment by ryanlin1986** [comment]
@raymondjhs 我们试过你说的解决方案还是不行哦

**Comment by clyquan** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues/340

参考这个
