### ISSUE TITLE
我也遇到了安卓下auth没有反应和share报错的情况

### ISSUE THREAD

**Issue by evanux** [xu-li/cordova-plugin-wechat#204]
我之前的安卓app一直是可以正常使用的，今天发布新版本的时候测试时突然发现点击auth没有任何反应，点击分享无论是分享好友还是朋友圈都弹出    分享失败：未知错误    的对话框。

因为之前的微信插件一直是可以使用的，签名应该是没有问题的，今天又重新计算了一下签名，和之前的结果是一样的，和微信后台的结果也是一样的。

share时的log这样

06-03 01:57:24.421 30756-30823/com.pingfang.cordova D/Cordova.Plugin.Wechat: plugin initialized.
06-03 01:57:24.421 30756-30823/com.pingfang.cordova D/Cordova.Plugin.Wechat: isWXAppInstalled is called. Callback ID: Wechat1065917451.
06-03 01:57:24.431 30756-30823/com.pingfang.cordova D/Cordova.Plugin.Wechat: share is called. Callback ID: Wechat1065917452.
06-03 01:57:24.431 30756-30799/com.pingfang.cordova D/Cordova.Plugin.Wechat: Start building message.
06-03 01:57:24.441 30756-30799/com.pingfang.cordova D/Cordova.Plugin.Wechat: Start downloading file at http://ping2.thinkers.net.cn/Upload/image/cover/574e63d06bbd8.jpg.
06-03 01:57:24.441 30756-30799/com.pingfang.cordova D/libc: [NET] android_getaddrinfofornetcontext+,hn 21(0x70696e67322e74),sn(),hints(known),family 0,flags 1024, proc=com.pingfang.cordova
06-03 01:57:24.441 30756-30799/com.pingfang.cordova D/libc: [NET] android_getaddrinfo_proxy get netid:0
06-03 01:57:24.441 30756-30799/com.pingfang.cordova D/libc: [NET] android_getaddrinfo_proxy-, success
06-03 01:57:24.471 30756-31296/com.pingfang.cordova I/MID: read mid from Settings.System
06-03 01:57:24.501 30756-31296/com.pingfang.cordova I/System: exec(/system/bin/cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq @ com.tencent.wxop.stat.common.l.b:-1)
06-03 01:57:24.541 30756-31296/com.pingfang.cordova I/System: exec(/system/bin/cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq @ com.tencent.wxop.stat.common.l.c:-1)
06-03 01:57:24.551 30756-30799/com.pingfang.cordova D/Cordova.Plugin.Wechat: File was downloaded and saved at /storage/emulated/0/cache/574e63d06bbd8.jpg.
06-03 01:57:24.551 30756-30799/com.pingfang.cordova D/Cordova.Plugin.Wechat: Bitmap was downloaded and cached to /storage/emulated/0/cache/574e63d06bbd8.jpg.
06-03 01:57:24.571 30756-30799/com.pingfang.cordova D/Cordova.Plugin.Wechat: Bitmap was decoded, dimension: 640 x 400, max allowed size: 320.
06-03 01:57:24.601 30756-31296/com.pingfang.cordova D/WifiManager: getScanResults: Base Package Name=com.pingfang.cordova, uid=10394
06-03 01:57:24.631 30756-30756/com.pingfang.cordova V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityPaused
06-03 01:57:24.631 30756-30799/com.pingfang.cordova I/Cordova.Plugin.Wechat: Message has been sent successfully.
06-03 01:57:24.681 30756-31307/com.pingfang.cordova D/libc: [NET] android_getaddrinfofornetcontext+,hn 13(0x70696e676d612e),sn(),hints(known),family 0,flags 1024, proc=com.pingfang.cordova
06-03 01:57:24.681 30756-31307/com.pingfang.cordova D/libc: [NET] android_getaddrinfo_proxy get netid:0
06-03 01:57:24.691 30756-31307/com.pingfang.cordova D/libc: [NET] android_getaddrinfo_proxy-, success
06-03 01:57:25.031 30756-30756/com.pingfang.cordova D/Cordova.Plugin.Wechat: com.tencent.mm.sdk.modelmsg.SendMessageToWX$Resp@bfba147
06-03 01:57:25.141 30756-30756/com.pingfang.cordova V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityResumed
06-03 01:57:25.141 30756-30804/com.pingfang.cordova W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init
06-03 01:57:25.161 30756-30756/com.pingfang.cordova I/InputMethodManager: [startInputInner] EditorInfo { packageName=com.pingfang.cordova, inputType=0xa1, imeOptions=0x12000000, privateImeOptions=null }, windowGainingFocus=android.view.ViewRootImpl$W@b186882, mServedView=org.apache.cordova.engine.SystemWebView{fc84b93 VFEDH.C.. .F...... 0,0-720,1134 #64}, mServedInputConnectionWrapper=android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper@faf4b0e
06-03 01:57:25.961 30756-30756/com.pingfang.cordova V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: WXStat trigger onForeground

然后就报错了

auth登陆时的log这样

06-03 02:06:35.151 30756-30823/com.pingfang.cordova D/Cordova.Plugin.Wechat: sendAuthRequest is called. Callback ID: Wechat1065917455.
06-03 02:06:35.171 30756-30756/com.pingfang.cordova V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityPaused
06-03 02:06:35.181 30756-30823/com.pingfang.cordova I/Cordova.Plugin.Wechat: Auth request has been sent successfully.
06-03 02:06:35.251 30756-30756/com.pingfang.cordova V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.pingfang.cordova.MainActivity  onActivityResumed
06-03 02:06:35.251 30756-30804/com.pingfang.cordova W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init
06-03 02:06:41.401 30756-30756/com.pingfang.cordova I/chromium: [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)

然后就没有反应了，请帮忙看一下？谢谢

**Comment by evanux** [comment]
不好意思，找到问题了，还是签名问题，debug和release的签名是不同的，不过我不清楚，在android studio里直接按debug按钮真机调试的情况下，应该如何配置keystore？

**Comment by xu-li** [comment]
你可以看这里: http://stackoverflow.com/questions/17189076/what-is-the-equivalent-of-eclipse-custom-debug-keystore-in-android-studio
