### ISSUE TITLE
android android-install.js code bug

### ISSUE THREAD

**Issue by wzhsh90** [xu-li/cordova-plugin-wechat#205]
1、the code ' plugins     = context.opts.plugins || [];' is wrong ,should replace with ' plugins     = context.opts.cordova.plugins || [];'

2、the fellow code is not neccessary
if (plugins.indexOf('cordova-plugin-wechat') === -1) {
        return ;
 }

I use the plugin ,so plugins will contains 'cordova-plugin-wechat' certainly.

that is my suggest , may it can help you.

**Comment by xu-li** [comment]
This is not a bug. See #190 .
