### ISSUE TITLE
提示找不到类啊

### ISSUE THREAD

**Issue by joshualzb** [xu-li/cordova-plugin-wechat#207]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ionicframework.payment501461/com.ionicframework.payment501461.wxapi.WXPayEntryActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ionicframework.payment501461.wxapi.WXPayEntryActivity" on path: DexPathList[[zip file "/data/app/com.ionicframework.payment501461-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 8942): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime( 8942): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2408)
E/AndroidRuntime( 8942): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 8942): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 8942): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8942): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8942): 	at android.app.ActivityThread.main(ActivityThread.java:5277)
E/AndroidRuntime( 8942): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8942): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8942): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
E/AndroidRuntime( 8942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
E/AndroidRuntime( 8942): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ionicframework.payment501461.wxapi.WXPayEntryActivity" on path: DexPathList[[zip file "/data/app/com.ionicframework.payment501461-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 8942): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 8942): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 8942): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 8942): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
E/AndroidRuntime( 8942): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2247)
E/AndroidRuntime( 8942): 	... 10 more
E/AndroidRuntime( 8942): 	Suppressed: java.lang.ClassNotFoundException: com.ionicframework.payment501461.wxapi.WXPayEntryActivity
E/AndroidRuntime( 8942): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 8942): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 8942): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 8942): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 8942): 		... 13 more
E/AndroidRuntime( 8942): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by xu-li** [comment]
重新安装插件，或者手动拷贝WXPayEntryActivity等类文件到你的项目里面。
