### ISSUE TITLE
分享成功，但无法正常回调

### ISSUE THREAD

**Issue by zhangxd1222** [xu-li/cordova-plugin-wechat#208]
分享朋友圈成功后， // 简单分享文字
        Wechat.share({
            text: "This is just a plain string",
            scene: Wechat.Scene.TIMELINE   // share to Timeline
        }, function () {
            console.log("Success");
        }, function (reason) {
            console.log("Failed: " + reason);
        });  但却没有成功回调，正常的话，应该执行console.log('success'),请问下是否是哪儿有什么问题？

**Comment by xu-li** [comment]
是不是android？logcat里面什么内容？可能是类没找到，可以尝试重新安装插件或者手动拷贝类文件。

See #207 .
