### ISSUE TITLE
android下libammsdk.jar

### ISSUE THREAD

**Issue by yaorunlong** [xu-li/cordova-plugin-wechat#210]
lib下libammsdk.jar重复的话，请跳过生成或者强制覆盖。不要安装一半断掉。所以请处理一下这个情况。

**Comment by xu-li** [comment]
这个是cordova默认的处理，我觉得可以理解，它告诉你哪里错了，你可以自己决定是否删除原来的。

比如这样：
1. 删除原来的libammsdk.jar
2. 安装wechat插件
3. 用旧的libammsdk.jar覆盖新的libammsdk.jar

**Comment by yaorunlong** [comment]
我知道可以那样，但是我如果好几个插件都要安装libammsdk.jar的话，岂不是很麻烦。尤其是你把所有插件都save到xml后。之后还要把用了libammsdk.jar的插件都重装。如果你这边能做处理的话，我觉得插件适应性会更强吧。然后我不知道插件里面是不是能解决,就提了这么个问题

**Comment by xu-li** [comment]
能解决，但没有一个完美的方案。

比如，你安装的时候，碰到没个插件用的版本不一样，怎么办？删除其中某一个插件的时候，是否要删掉？

**Comment by yaorunlong** [comment]
覆盖，然后给个提示就行。或者你不复制到libs下也行，当然也要给个提示
