### ISSUE TITLE
ios 9.3.2 无法分享

### ISSUE THREAD

**Issue by JackyWolf008** [xu-li/cordova-plugin-wechat#212]
iphone5 version9.3.2
cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID --save
插件应该是最新的版本
分享失败
由于app还未发布到app store，现在使用的是ad-hoc模式，我知道android必须是release版本，ios ad-hoc模式有影响吗？

**Comment by xu-li** [comment]
没试过ad-hoc，不过未发布的肯定能分享的。

**Comment by JackyWolf008** [comment]
"未发布的"是指什么模式？我开发者模式也试过，无法分享，现在app还没有发布到app store，我如何才能测试这个插件可以正常分享？

**Comment by JackyWolf008** [comment]
放到app store上的版本，下载后，只是第一次分享成功，之后一直失败，为什么？

**Comment by januslo** [comment]
@JackyWolf008 建议你检查一下Wechat这个对象在调用的时候是否已经正常加载，我发现这个插件在加载的顺序上是不确定的，甚至有时候在页面加载完成1秒以后才会被成功加载（特别是在第一次调用的时候）。 我在程序的第一页加一个$interval去做重复的检查 Wechat.isInstalled，直到找到或者重复检查一定次数以后才停止。一般这样以后的页面加载都很顺利。

**Comment by xu-li** [comment]
测试可以分享的。
