### ISSUE TITLE
Share to Session (PM) or to Timeline (moments) crashes on Android

### ISSUE THREAD

**Issue by edesaintchamas** [xu-li/cordova-plugin-wechat#213]
Hi there,

I'm having an issue when using the latest version of this plugin on android.

The following code does not work specifically on Android (it opens a window saying please wait, and then  crashes a few seconds later). None of the success or error event are fired.

                Wechat.share({
                    message: {
                        title: 'Title',
                        description: 'Description',
                        thumb: img,
                        media: {
                            type: Wechat.Type.LINK,
                            webpageUrl: url
                        }
                    },
                    scene: Wechat.Scene.TIMELINE   // share to Timeline
                }, function(){
                    // never called on android
                    $messages.alert('Success', 'Success');
                }, function(reason){
                    // never called on android
                    $messages.alert('Error', reason);
                });                
 
The same code, for sharing to chat (`Wechat.Scene.SESSION`) does not work either.
Of course Wechat is installed on the phone, and I check if the plugin can detect wechat before trying to share (`Wechat.isInstalled(...)`).

It works fine on iOS though, so it seems to be an android related issue (maybe SDK?).

Thanks for your help!

**Comment by xu-li** [comment]
1. Have you checked your app signature? App signature is required in android. The signature generated using your keystore should match the one you set in your app settings on wechat website.
2. Has your app been approved? It will not work if your app hasn't been approved by wechat team.
3. What's in the logcat?

-Xu

**Comment by edesaintchamas** [comment]
Hi,

Our app is already in production on iOS, and everything works fine, we have already been through wechat validation procedure and so on.

1. Yes app signature is ok (com.xxx.yyy) and match the one registered with wechat
2. Yes the wechat app account has been approved (and is already implemented with iOS)
3. How can I access the log?

Thanks!

**Comment by xu-li** [comment]
1. com.xxx.yyy is the package name, not the app signature I was referring to. [app signature](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN).
2. Okay.
3. [logcat](https://developer.android.com/studio/command-line/logcat.html).

**Comment by edesaintchamas** [comment]
Hi,

1. Yes the app is signed, but apparently we need to communicate the signature to Wechat, and do not have the right account type for now to do it. So I guess the issue might come from here. We are creating the new account, and if this solves this issue I will come back commenting on that and close this case.
3. Will provide you a logcat if 1. does not solve the issue.

Thanks again for your answers, much appreciated!

**Comment by gztrd** [comment]
你好 xu-li,

我们现在申请的微信移动应用已经通过审核了，但是android上的分享依旧不能成功，请问你知道这是什么原因吗？ 谢谢

**Comment by edesaintchamas** [comment]
Apparently we were not using the right account type. We created a new wechat account and its now working perfectly.

It was working on iOS though, which is weird. I would be interested to know why, in order to understand what we miss :)

Anyway, this was not a technical issue, so I'm closing this case.
Thanks again for your answers
