### ISSUE TITLE
android 调用微信授权，返回重新启动APP。

### ISSUE THREAD

**Issue by gitHubLie** [xu-li/cordova-plugin-wechat#214]
android 调用微信授权，返回重新启动APP。 IOS没有问题。APP无法获取授权信息 。
 try {
            req.scope = args.getString(0);
            req.state = args.getString(1);
        } catch (JSONException e) {
            Log.e(TAG, e.getMessage());

```
        req.scope = "snsapi_userinfo";
        req.state = "wechat";
    }
```

req.scope    req.state 都是空的。

**Comment by lyccccx** [comment]
我也遇到这个问题，请问你解决了吗

**Comment by lyccccx** [comment]
我的是在Android上运行的，点击确认授权按钮后APP就重启了，不知道怎么解决，你解决了吗

**Comment by clyquan** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues/340

参考我的办法
