### ISSUE TITLE
android 机上微信支付不能返回到原app

### ISSUE THREAD

**Issue by wzhsh90** [xu-li/cordova-plugin-wechat#215]
现象模拟：

step 1、通过app 先调出微信支付(但并不支付)
step 2、kill 掉原app
step 3、点击微信支付返回

结果：
 1、不修改源码情况 程序crash
 2、修改源码
 if(null!=Wechat.instance){
            if (Wechat.instance.getWxAPI() == null) {
                Log.d(Wechat.TAG,"===3");
                startMainActivity();
            } else {
                Log.d(Wechat.TAG,"===2");
                Wechat.instance.getWxAPI().handleIntent(getIntent(), this);
            }
        }
        else{
            Log.d(Wechat.TAG,"===1");
            startMainActivity();
        }   

进入1 ，但手机效果不正常
![screenshot_2016-06-21-16-57-23](https://cloud.githubusercontent.com/assets/16187191/16252051/b6400928-385d-11e6-8bb4-7c1758efd3e5.png)

解决方法：
修改startMainActivity 方法

   final String packageName = getPackageName();
        final Intent launchIntent = getPackageManager().getLaunchIntentForPackage(packageName);
        if(null!=launchIntent){
            final String mainActivity = launchIntent.getComponent().getClassName();
            final Intent intent = new Intent(Intent.ACTION_MAIN);
            intent.setPackage(packageName);
            intent.addCategory(Intent.CATEGORY_LAUNCHER);
            intent.setComponent(new ComponentName(packageName, mainActivity));
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            getApplicationContext().startActivity(intent);
        }

//       Intent intent = new Intent();
//        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
//        intent.setPackage(getApplicationContext().getPackageName());
//        getApplicationContext().startActivity(intent);

**Comment by luntanwang** [comment]
同样的现象
出错原因：修改了app的id导致的
解决方案：把插件remove掉，再次添加插件即可
