### ISSUE TITLE
android不能调起微信登陆

### ISSUE THREAD

**Issue by genyii** [xu-li/cordova-plugin-wechat#216]
IOS是可以的，Android上有问题：
Wechat.isInstalled 正常，Wechat.auth没反应

`06-27 16:42:53.404 8687-8759/com.genyii.asdf W/PluginManager: THREAD WARNING: exec() call to Wechat.sendAuthRequest blocked the main thread for 36ms. Plugin should use CordovaInterface.getThreadPool().
`

**Comment by xu-li** [comment]
android的签名对么？调用分享可以么？

**Comment by phanthinh** [comment]
+1 similar issue. Why closed it?

**Comment by woshibt** [comment]
我也遇到同样的问题。
11-09 18:32:08.156  3001  3056 I Cordova.Plugin.Wechat: Auth request has been sent successfully.
11-09 18:32:08.156  3001  3056 W PluginManager: THREAD WARNING: exec() call to Wechat.sendAuthRequest blocked the main thread for 50ms. Plugin should use CordovaInterface.getThreadPool().
11-09 18:32:08.239   864 17246 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@869392e attribute=null, token = android.os.BinderProxy@3492ebe
11-09 18:32:08.240   864 17244 W ActivityManager: Finishing task with all activities already finished
11-09 18:32:08.240   864 17244 W ActivityManager: Duplicate finish request for ActivityRecord{cf152c4 u0 com.tencent.mm/.plugin.base.stub.WXEntryActivity t172 f}

**Comment by xzf158** [comment]
同样的问题：
11-11 14:23:32.599 11941-11988/com.xxx.app I/chromium: [INFO:EventDispatcher.cpp(141)] EventDispatcher::dispatch() parent class is : wx_item.cn
11-11 14:23:32.656 11941-11955/com.xxx.app W/aoc: Suspending all threads took: 13.353ms
11-11 14:23:32.700 11941-11992/com.xxx.app I/Cordova.Plugin.Wechat: Auth request has been sent successfully.
11-11 14:23:32.701 11941-11992/com.xxx.app W/PluginManager: THREAD WARNING: exec() call to Wechat.sendAuthRequest blocked the main thread for 62ms. Plugin should use CordovaInterface.getThreadPool().
