### ISSUE TITLE
 android 分享不成功 返回jsonError

### ISSUE THREAD

**Issue by zhangykun** [xu-li/cordova-plugin-wechat#217]

**Comment by zhangykun** [comment]
cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID
我直接这样添加的，可以判断微信是否安装了，就是分享不了。。是什么 原因？需要配置config.xml吗？

**Comment by xu-li** [comment]
android需要设置签名，可以看一下FAQ。

**Comment by zhangykun** [comment]
签名是设置好了的啊。。我是ionic生成一个debug apk安装到手机上面，能够判断微信是否安装了。这应该表示 插件安装好了。就是Wechat.share方法走不进去。

**Comment by xu-li** [comment]
判断微信是否安装不需要签名也能用。

**Comment by januslo** [comment]
同样的问题，我可以授权登录，请问授权登录是否需要对签名？我发起的是图片分享，使用dataurl。代码大致如下：

`
  $scope.share = function () {alert('share')
      var fullCanvas = document.getElementById('canvas');
      try {
        Wechat.isInstalled(function (installed) {alert(installed)
          if (installed) {
            alert('come')
            Wechat.share({
              message:{
                media:{
                  type:Wechat.Type.IMAGE,
                  image:fullCanvas.toDataURL()
                }
              },
              scene:Wechat.Scene.TIMELINE
            },function(){
              alert('success');
            },function(reaseon){
              alert('err'+reaseon)
            });
          } else {
            savePicToAlbum();
          }
        });
      }catch(e){alert(e.message)
        savePicToAlbum();
      }
    };
`

**Comment by xu-li** [comment]
是的，title和description是必选参数。
