### ISSUE TITLE
libammsdk.jar 包是精简过了的么？

### ISSUE THREAD

**Issue by efon6653** [xu-li/cordova-plugin-wechat#218]
我还有别一个插件用到这个包，两个插只有一个能用，libammsdk.jar名字一样，但内容应该不一样。请问你这个是原始包么？

**Comment by xu-li** [comment]
是原始包，[官方](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN)下载的。
