### ISSUE TITLE
现在预见最多的问题就是  返回普通错误, 各种百度, 谷歌都找过了, 无解啊

### ISSUE THREAD

**Issue by ChinaGNU** [xu-li/cordova-plugin-wechat#223]
参数签名没问题, 已经在微信验证过了,   应用签名也生成了,    最后一直普通错误!!!!!!!懵逼了,谁拯救一下我

**Comment by cimichen** [comment]
大家都跌倒在同一个坑里，iOS支付一点问题都没有，安卓的死活就是普通错误，有没有坑外的人拉一把？

**Comment by xu-li** [comment]
@luo975974740 

你可以试试用libammsdk_debug.jar替换掉正式版的libammsdk.jar。Debug的是我从官方的demo拷贝过来的，区别在于会在Logcat里面输出微信的错误信息。

当然我还是更倾向于签名错了。你打包APK的keystore和你生成签名的keystore要是同一个，同时你的签名要和微信平台上设置的一样。

-Xu

**Comment by kinglionsoft** [comment]
首先感谢作者分享。
我也是出现普通错误，对比了下微信文档，发现问题出在package=“Sign=WXPay“这里。这个固定且必填的（bs tx）作者应该是在插件中写死了，那么在服务器签名时，也要包含这个。

**Comment by cimichen** [comment]
成功从坑中跳出，我的坑在Wechat.java的265行req.appId = getAppId();
将替换为req.appId = "wxb24873debcf8df2b";
在java文件中将appId写死，成功从坑中跳出。

不太熟悉安卓，不清楚535行this.appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");的preferences.getString的值从何处获取，希望作者关注一下。

**Comment by xu-li** [comment]
@kinglionsoft 服务器签名我有个demo的，可以参考一下。不过还好你看文档仔细。

@cimichen 这个是从config.xml里面获取的，你安装这个插件的时候传的参数会写到config.xml里面。不过看你的情况，iOS可用，那就是对的。你用的是cordova什么版本？或者是ionic？

-Xu

**Comment by cimichen** [comment]
@xu-li  cordova版本号6.1.1，执行命令cordova plugin add cordova-plugin-wechat --variable wechatappid=XXXXXXXXXXXX，完成后不修改config.xml

**Comment by frank39** [comment]
我安卓报普通错误，ios提示统一下单的appid和拉起支付的appid不一样，但是我看了，服务器的appid和我安装插件的时候appid是一样的

**Comment by frank39** [comment]
@xu-li 求解大神

**Comment by mayaqi123** [comment]
您好，麻烦问一下“在服务器签名时，也要包含这个”是在哪添加？

**Comment by mayaqi123** [comment]
@kinglionsoft 您好，麻烦问一下“在服务器签名时，也要包含这个”是在哪添加？

**Comment by kinglionsoft** [comment]
@mayaqi123 服务器签名之的参数中要有package=“Sign=WXPay“

**Comment by mayaqi123** [comment]
@kinglionsoft 谢谢您的回答

**Comment by mayaqi123** [comment]
@kinglionsoft 我是个新手，还是没太明白，还想请教您一下，是在    $param = array(
            'appid'            => APP_ID,
            'mch_id'           => MCH_ID,
            'nonce_str'        => generateNonce(),
            'body'             => 'Test product name',
            'out_trade_no'     => time(),
            'total_fee'        => 1,
            'spbill_create_ip' =>get_client_ip(),
            'notify_url'       => 'http://localhost',
            'trade_type'       => 'APP',

        );
这部分添加呢？还是在下面这部分添加？
   curl_setopt_array($ch, array(
            CURLOPT_URL            => "https://api.mch.weixin.qq.com/pay/unifiedorder",
            CURLOPT_POST           => true,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER     => array('Content-Type: text/xml'),
            CURLOPT_POSTFIELDS     => $xml1,
            package=>'Sign=WXPay'
        ));

**Comment by kinglionsoft** [comment]
@mayaqi123 加在上面部分

**Comment by mayaqi123** [comment]
@kinglionsoft 谢谢您的回复，不过我的依然是普通错误/(ㄒoㄒ)/~~

**Comment by mayaqi123** [comment]
这个就是签名的问题，签名好了就不会报错了，感谢楼主分享，谢谢！

**Comment by wangchao1002** [comment]
@mayaqi123 老铁 我和你的问题同样  但是我使用微信接(https://pay.weixin.qq.com/wiki/tools/signverify/),
来进行调试,签名是一样 ,结果还是显示普通错误 希望能得到你的帮助

**Comment by iiDestiny** [comment]
后来集成的 PIng ++ 支付。。。

**Comment by wangchao1002** [comment]
@iiDestiny 老铁  你后来没有使用这个插件了?

**Comment by iiDestiny** [comment]
没有了，我不是前端的。。。。。
