### ISSUE TITLE
微信分享多图

### ISSUE THREAD

**Issue by jason-shen** [xu-li/cordova-plugin-wechat#224]
你好xu－li
感谢你这个那么好的插件、我想了解一下、怎么实现多图分享、请指教

谢谢

**Comment by xu-li** [comment]
据我所知，手机端的API不支持多图分享。多图分享好像都是用web端实现的。没仔细研究过。

-Xu

**Comment by jason-shen** [comment]
能研究一下吧？

**Comment by kongkang** [comment]
单张图的我还没搞明白，图片对象格式是什么……

**Comment by CuiDeQun** [comment]
请问微信分享多图可以提供些思路吗

**Comment by jasonz1987** [comment]
微信sdk 暂不支持～
