### ISSUE TITLE
未安装微信时登录提示 发送请求失败，但看微信wxapi中有提示相关授权方法

### ISSUE THREAD

**Issue by efon6653** [xu-li/cordova-plugin-wechat#225]
未安装微信时登录提示 发送请求失败，但看微信wxapi中有提示相关授权方法，要如何才能调用此方法呢？
+(BOOL) sendReq:(BaseReq*)req;

/*! @brief 发送Auth请求到微信，支持用户没安装微信，等待微信返回onResp
 *
 * 函数调用后，会切换到微信的界面。第三方应用程序等待微信返回onResp。微信在异步处理完成后一定会调用onResp。支持SendAuthReq类型。
 * @param req 具体的发送请求，在调用函数后，请自己释放。
 * @param viewController 当前界面对象。
 * @param delegate  WXApiDelegate对象，用来接收微信触发的消息。
 * @return 成功返回YES，失败返回NO。
 */

**Comment by xu-li** [comment]
这个不能掉用，回头我测试一下不安装微信能不能登录吧。

**Comment by xu-li** [comment]
@efon6653 能不能把你的app id和app secret发我邮箱？我测试一下。 邮箱: AthenaLightenedMyPath@gmail.com.

**Comment by xu-li** [comment]
可能你想说的是sendAuthReq，试了一下，所谓"支持用户没安装微信"就是弹出一个层，告诉用户没装微信。区别于sendReq就是，sendAuthReq会弹层，sendReq会返回错误。

**Comment by efon6653** [comment]
其实，强出的应该是 是否允许发送短信到微信获取授权的界面。

**Comment by xu-li** [comment]
没看懂。

**Comment by xu-li** [comment]
今天又试了一下，是会发短信的。昨天的时候，我忘记我开了VPN了。
