### ISSUE TITLE
安卓支付完成之后，应用崩溃重启

### ISSUE THREAD

**Issue by cimichen** [xu-li/cordova-plugin-wechat#226]
在安卓上调用微信支付，支付完成后点击完成或点击物理返回，应用崩溃重启。issues [#198](https://github.com/xu-li/cordova-plugin-wechat/issues/198)，不太明白#198的解决方法。有解决这个问题的朋友解答一下么？谢谢

**Comment by wowgeeker** [comment]
可能是contributors都忘记这事了吧， 很简单。 
找到plugin.xml:

```
        <source-file src="src/android/Wechat.java" target-dir="src/xu/li/cordova/wechat" />
        <source-file src="src/android/Util.java" target-dir="src/xu/li/cordova/wechat" />
 
       <!-- add 3 lines here -->
        <source-file src="src/android/EntryActivity.java" target-dir="src/xu/li/cordova/wechat" />
        <source-file src="src/android/WXEntryActivity.java" target-dir="src/xu/li/cordova/wechat" />
        <source-file src="src/android/WXPayEntryActivity.java" target-dir="src/xu/li/cordova/wechat" />  
        <!-- endof add -->


        <source-file src="src/android/libammsdk.jar" target-dir="libs" />
```

在这个repo没更新的情况下， 你可以自己fork一个工程， 然后cordova plugin add [你的git repo] --variable wechatappid=[app_id]

例如， 我fork改正后删掉原来的plugin， 然后这样就可以了
ionic plugin add https://github.com/wowgeeker/cordova-plugin-wechat --variable wechatappid=[你的app_id]

**Comment by cimichen** [comment]
Thank you very very much.

**Comment by xu-li** [comment]
@wowgeeker 你的方法应该不起作用。EntryActivity.java等文件需要拷贝到你的包名的目录(比如，你叫com.company.awesomeapp，就应该拷贝到com/company/awsomeapp/wxapi下面)。这也是为什么需要[android-install.js](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/scripts/android-install.js)。

@cimichen 不需要fork，你重装一下试试。

**Comment by cimichen** [comment]
重新安装也好用

**Comment by wowgeeker** [comment]
@xu-li , 确实， 之所以能成功还是因为我有个手动拷贝的操作。

**Comment by wowgeeker** [comment]
@xu-li ， 确实只是在我调试的时候起作用。 我的问题是微信支付官网上的签名是去年做的， 昨天重新生成了没在官网改， 所以导致app调用不了微信支付。
