### ISSUE TITLE
楼主，求救我测试的时候出现未知错误是什么原因？

### ISSUE THREAD

**Issue by andyzhao85** [xu-li/cordova-plugin-wechat#227]
楼主，求救我测试发送消息给微信的时候出现“Failed:未知错误"是什么原因？尝试了各种方法都未解决，头都大了，麻烦告知

**Comment by xu-li** [comment]
是不是android？android基本是签名问题，你可以看一下FAQ里面。

**Comment by andyzhao85** [comment]
同时，微信登录点击一点反应没有，也同是这个原因造成的吗？

**Comment by xu-li** [comment]
不确定，可能是你的JS，可能微信没装，可能是签名。

**Comment by andyzhao85** [comment]
微信肯定装了，方便留个QQ沟通吗？

**Comment by andyzhao85** [comment]
我查看了安装包的签名，发现签名和微信应用里的签名是一致的，晕死了

**Comment by andyzhao85** [comment]
应用签名：049a9fde46bfc5087f3825582208b248   是要写这种格式的应用签名吗？ 还是写SHA1这种？

**Comment by xu-li** [comment]
是的。QQ基本不用。你可以考虑看一下Logcat里面有什么问题么。

**Comment by andyzhao85** [comment]
现在签名用了微信自己提供的签名工具，解决了这个问题，但分享的时候有时提示"请求失败"，是什么问题？
