### ISSUE TITLE
Wechat is not defined  出现这种错误是为什么？急

### ISSUE THREAD

**Issue by andyzhao85** [xu-li/cordova-plugin-wechat#228]
Wechat is not defined  出现这种错误是为什么？急
微信登录可以正常跳转，微信分享却出现这种错误，急死了，搞了半天不知道是什么问题

**Comment by xu-li** [comment]
贴一下你的代码吧。应该是代码问题。

**Comment by andyzhao85** [comment]
$scope.shareText = function () {
			
            if (typeof Wechat === "undefined") {
                alert("您的手机尚未安装微信");
                return false;
            };
			
            Wechat.share({
                    message: {
                        title: $scope.data.title,
                        description: $scope.data.body,
                        thumb: $scope.data.photo[0].photo,
                        media: {
                            type: Wechat.Type.WEBPAGE,
                            //类型是一个webpage，就是一个网页？
                            webpageUrl: "www.baidu.com"
                        }
                    },
                    scene: Wechat.Scene.TIMELINE // 分享到朋友圈
                },
                function () {
                    alert("分享成功");
                },
                function (reason) {
                    alert("分享失败" + reason);
                });
        };


        //发送给微信好友	

        $scope.sendText = function () {
			
            if (typeof Wechat === "undefined") {
                alert("您的手机尚未安装微信");
                return false;
            };
			
            Wechat.share({
                    message: {
                        title: $scope.data.title,
                        description: $scope.data.body,
                        thumb: $scope.data.photo[0].photo,
                        media: {
                            type: Wechat.Type.WEBPAGE,
                            //类型是一个webpage，就是一个网页？
                            webpageUrl: "www.baidu.com"
                        }
                    },
                    scene: Wechat.Scene.SESSION // 表示分享给好友
                },
                function () {
                    alert("发送成功");
                },
                function (reason) {
                    alert("发送失败" + reason);
                });
        };

**Comment by xu-li** [comment]
登录的代码呢？还有你的index.html的代码？

**Comment by andyzhao85** [comment]
$scope.wxlogin = function () {

            if (typeof Wechat === "undefined") {
                alert("您的手机尚未安装微信");
                return false;
            };

            var scope = "snsapi_userinfo",
                state = "_" + (+new Date());
            Wechat.auth(scope, state,
                function (response) {

                    // you may use response.code to get the access token.
                    alert(JSON.stringify(response));
                },
                function (reason) {
                    alert("Failed: " + reason);
                });
        };

**Comment by andyzhao85** [comment]
index.html代码


<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
<title></title>
<link rel="stylesheet" href="lib/ionic/css/ionic.min.css">
<link rel="stylesheet" href="css/photoswipe.css">
<link rel="stylesheet" href="css/default-skin/default-skin.css">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/yyy.css">
<link rel="stylesheet" href="css/sxb.css">
<link rel="stylesheet" href="css/hbs.css">



<script src="lib/ionic/js/ionic.bundle.min.js"></script>


<script type="text/javascript" src="lib/jquery.min.js"></script>



<script>
var onDeviceReady = function(){
	document.getElementById("videoCapture").addEventListener("click", videoCapture);
	}
</script>



<script src="cordova.js"></script>
<script src="lib/photoswipe.min.js"></script>
<script src="lib/photoswipe-ui-default.min.js"></script>
<script src="lib/Cvideo.js"></script>
<script src="lib/Cform.js"></script>
<script src="lib/Ceditor.js"></script>
<script src="js/app.js"></script>
<script src="js/route.js"></script>
<script src="js/services/Localstorage.js"></script>
<script src="js/services/Cfg.js"></script>
<script src="js/services/Cphoto.js"></script>
<script src="js/services/VideoCapture.js"></script>
<script src="js/services/Util.js"></script>
<script src="js/services/User.js"></script>
<script src="js/services/News.js"></script>
<script src="js/services/Backcall.js"></script>
<script src="js/services/FromStateServ.js"></script>

<script src="js/controllers/HelpCtrl.js"></script>
<script src="js/controllers/UpdateCtrl.js"></script>
<script src="js/controllers/AboutusCtrl.js"></script>
<script src="js/controllers/ScoreCtrl.js"></script>

<script src="js/controllers/AddnewsCtrl.js"></script>
<script src="js/controllers/HuiyuankuCtrl.js"></script>
<script src="js/controllers/HykdiankaiCtrl.js"></script>
<script src="js/controllers/HykgdzhaopianCtrl.js"></script>
<script src="js/controllers/HykzhanshiCtrl.js"></script>
<script src="js/controllers/HykziliaoCtrl.js"></script>
<script src="js/controllers/JigouCtrl.js"></script>
<script src="js/controllers/JigouinfoCtrl.js"></script>
<script src="js/controllers/JigouxiangqingCtrl.js"></script>
<script src="js/controllers/JigoukuCtrl.js"></script>
<script src="js/controllers/LoginCtrl.js"></script>
<script src="js/controllers/MimaCtrl.js"></script>
<script src="js/controllers/MineCtrl.js"></script>
<script src="js/controllers/MyCtrl.js"></script>
<script src="js/controllers/MyinfoCtrl.js"></script>
<script src="js/controllers/MyjgCtrl.js"></script>
<script src="js/controllers/MyxiangceCtrl.js"></script>
    <script src="js/controllers/MyjgxiangceCtrl.js"></script>
<script src="js/controllers/JigouXiangceCtrl.js"></script>
<script src="js/controllers/NewsCtrl.js"></script>
<script src="js/controllers/NewsdetailCtrl.js"></script>
<script src="js/controllers/PaihangbangdzCtrl.js"></script>
<script src="js/controllers/PaihangbanghyCtrl.js"></script>
<script src="js/controllers/PaihangbangrqCtrl.js"></script>
<script src="js/controllers/QuizhiCtrl.js"></script>
<script src="js/controllers/RegCtrl.js"></script>
<script src="js/controllers/SearchCtrl.js"></script>
<script src="js/controllers/TuijianCtrl.js"></script>
<script src="js/controllers/TjyirenCtrl.js"></script>
<script src="js/controllers/ZhaopinCtrl.js"></script>
<script src="js/controllers/ZhaopinptCtrl.js"></script>
<script src="js/controllers/ZhaopinviewCtrl.js"></script>
<script src="js/controllers/ZixunCtrl.js"></script>
<script src="js/controllers/ZixunliebiaoCtrl.js"></script>
<script src="js/controllers/NavCtrl.js"></script>
<script src="js/controllers/AddnewsCtrl.js"></script>

<script src="js/controllers/HuodongCtrl.js"></script>
<script src="js/controllers/ShiziCtrl.js"></script>

<script src="js/directives/hideTabs.js"></script>

</head>
<body ng-app="app">
<ion-pane>
  <ion-nav-bar class="bar-dark" ng-dblclick="Util.scrollTop()">

 <ion-nav-buttons side="left">
        <button class="button buttons button-clear header-item" ng-click="Util.goBack($state)"><i class="icon ion-ios-arrow-back"></i></button>
    </ion-nav-buttons>
    <ion-nav-buttons side="right"> 
      
      <button class="button button-clear ion-plus toLogin" ng-show="Util.isLogin()" ng-click="Util.toAddPage($state, Cphoto)"></button>
    </ion-nav-buttons>
  </ion-nav-bar>
  <ion-nav-view animation="slide-left-right"></ion-nav-view>
</ion-pane>

 

 
<ion-footer-bar ng-controller="FooterCtrl" ng-show="!flag">
  <div class="tabs tabs-icon-top" ng-class="{'tabs-item-hide': $root.hideTabs}"> <a class="tab-item" ui-sref="home"> <i class="icon ion-ios-home-outline"></i> 首页 </a> <a class="tab-item" ng-click="$state.go('cats')"> <i class="icon ion-navicon"></i> 分类 </a> <a class="tab-item" ng-click="$state.go('tuijian-tabs.huiyuan')"> <i class="icon ion-ios-pulse"></i> 推荐 </a> <a class="tab-item" ng-click="$state.go(Util.myPage())"> <i class="icon ion-ios-person-outline"></i> 我 </a> </div>
</ion-footer-bar>


<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true"> 
  
  
  <div class="pswp__bg"></div>
  
  
  <div class="pswp__scroll-wrap"> 
    
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    
    <div class="pswp__ui pswp__ui--hidden">
      <div class="pswp__top-bar"> 
        
        
        
        <div class="pswp__counter"></div>
        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
        <button class="pswp__button pswp__button--share" title="Share"></button>
        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
        <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
        
         
        
        
        <div class="pswp__preloader">
          <div class="pswp__preloader__icn">
            <div class="pswp__preloader__cut">
              <div class="pswp__preloader__donut"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="pswp__share-modal pswp__share-modal-hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>
      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"> </button>
      <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"> </button>
      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

**Comment by xu-li** [comment]
没看出来有什么问题啊。你是不是在浏览器里面测试？需要到真机上测试的。

**Comment by andyzhao85** [comment]
浏览器提示“Wechat is not defined”  真机点击是没反应

**Comment by andyzhao85** [comment]
index.html 代码复制不过来，你要这个代码想看什么问题？

**Comment by andyzhao85** [comment]
方便的话加我QQ： 270968307   或者留个邮箱我发给你

**Comment by xu-li** [comment]
那我更倾向于看一下你的JS有没有语法错误。 index.html刚才我看到了啊。

**Comment by andyzhao85** [comment]
是不是我安装你的插件，然后再加上我刚才发给你的那些登录和分享的代码就可以用了？需要不需要其他操作了？

**Comment by andyzhao85** [comment]
还是我有哪个步骤没有做？

**Comment by xu-li** [comment]
不需要啊，安装插件完，你要ionic build/run android，就可以用了.

**Comment by andyzhao85** [comment]
那就奇怪了，搞死了

**Comment by andyzhao85** [comment]
config.xml  这件文件要不要配置的？

**Comment by xu-li** [comment]
不需要。不过有个人好像有这个问题。你可以把platform remove掉，再add试试。

**Comment by andyzhao85** [comment]
我试试看吧，非常感谢回复

**Comment by andyzhao85** [comment]
登录功能，后台处理要怎么处理，demo有吗？

**Comment by xu-li** [comment]
后台处理看你自己的业务逻辑啊。

**Comment by gaochunrong** [comment]
弹出登录界面，登录后却没有出现授权界面，请问什么原因呢？
