### ISSUE TITLE
rx timeout

### ISSUE THREAD

**Issue by zyyanzi** [xu-li/cordova-plugin-wechat#229]
跳转未正常， rx timeout, 代码如下：
Wechat.share({
            text: "This is just a plain string",
            scene: Wechat.SCENE.TIMELINE // share to Timeline
        }, function () {

            alert("Success");
        }, function (reason) {
            alert("Failed: " + reason);
        });

**Comment by xu-li** [comment]
是android的么？基本是签名问题吧。看一下FAQ。

**Comment by zyyanzi** [comment]
网络问题
