### ISSUE TITLE
可以添加微信支付吗？

### ISSUE THREAD

**Issue by Mavlarn** [xu-li/cordova-plugin-wechat#23]
非常感谢这个插件，解决了我的一大问题，但是还有一个问题就是微信支付，请问有计划添加吗？
我也做过简单的cordova的插件，如果要实现微信支付，需要怎么做，如果你没有时间，我可以试试看能不能实现一下。

**Comment by xu-li** [comment]
多谢支持。

关于支付，考虑过实现，但是由于没有现成的微信APP通过审核，所以没有加上。 如果你有通过审核的APP，同时也不介意共享给我，我可以抽空实现一下。

当然如果你想自己实现，那当然欢迎pull request。

**Comment by Mavlarn** [comment]
我不太明白共享是共享代码？还是共享app，现在做的app是真实要给客户用的。

**Comment by xu-li** [comment]
微信的APP，就是那些key什么的，这样我才能调试。 不需要你的源代码。

**Comment by wozzup** [comment]
@xu-li 徐工！我去申请一下看，哈哈

**Comment by aqingsao** [comment]
@xu-li 您好，

我们app的微信支付也在申请当中，估计需要几个工作日。过几天通过了再联系您，看看是否还需要。
