### ISSUE TITLE
iOS的依赖库dylib是老版本的xcode,现在7.0以后的xcode库后缀都是tbd了建议更新下,不然直接使用会报错

### ISSUE THREAD

**Issue by chenjin0624** [xu-li/cordova-plugin-wechat#230]

**Comment by xu-li** [comment]
没啊，我新建的ionic项目在xcode7.3.1不会报错。你用的是cordova什么版本？

**Comment by chenjin0624** [comment]
这个应该跟cordova版本没关系吧，我就是用npm的命令行安装的，我看到你plugin.xml文件里的导入配置项是dylib类型的然后我再使用时也确实报错了是我自己手动更改这些库才能用的，你可以在确认下配置文件呢，也有可能是我的错(因为我没写过cordova的插件，O(∩_∩)O哈哈~)。这个插件很实用，良心插件哦。
plugin.xml：
        <framework src="libz.dylib" />
        <framework src="libsqlite3.0.dylib" />
        <framework src="CoreTelephony.framework" />
        <framework src="SystemConfiguration.framework" />
        <framework src="Security.framework" />
        <framework src="libstdc++.6.dylib" />

**Comment by chenjin0624** [comment]
这个应该跟cordova版本没关系吧，我就是用npm的命令行安装的，我看到你plugin.xml文件里的导入配置项是dylib类型的然后我再使用时也确实报错了是我自己手动更改这些库才能用的，你可以在确认下配置文件呢，也有可能是我的错(因为我没写过cordova的插件，O(∩_∩)O哈哈~)。这个插件很实用，良心插件哦。
plugin.xml：
        
        <framework src="libz.dylib" />
        <framework src="libsqlite3.0.dylib" />
        <framework src="CoreTelephony.framework" />
        <framework src="SystemConfiguration.framework" />
        <framework src="Security.framework" />
        <framework src="libstdc++.6.dylib" />

**Comment by GP2513** [comment]
@chenjin0624 请问下 
2016-09-02 13:13:43.492 wqdemo[313:34139] +[WXApi sendAuthReq:viewController:delegate:]: unrecognized selector sent to class 0x1004325a8
2016-09-02 13:13:43.493 wqdemo[313:34139] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> +[WXApi sendAuthReq:viewController:delegate:]: unrecognized selector sent to class 0x1004325a8

这是什么问题
