### ISSUE TITLE
由于图片问题无法分享

### ISSUE THREAD

**Issue by loooooook** [xu-li/cordova-plugin-wechat#231]
你好，我目前使用的是1.1.3版本，但进行微信分享的时候有些能分享有些却不能，经测试确认应该是图片的原因导致的，但无法确认是由于图片的什么因素导致的，求解答，谢谢！
可以分享的图片http://thumb.syt.qinsilk.com/goods/album/7/20160606/96ea502cf19e4028adbd0e3c6c139b04.jpg
不可以分享的图片
http://thumb.qinsilk.com/goods/album/93851/20160714/d836ce12905849178cacce91b4cef7ca.jpg

**Comment by xu-li** [comment]
可能是图片太大了。对于大图片，我会裁成300宽的，但是还是可能突破微信的限制。

**Comment by loooooook** [comment]
首先非常感谢你在百忙之中抽出时间来答复。之前我也是认为是图片的宽高限制导致分享不了，因为我对那张分享不了的图片的宽高均设置为256之后就可以分享了。不过不知道你有没有发现，我第一张可以分享的图片的宽高均为800，但它却是可以分享成功的。所以我才怀疑宽高不是唯一的制约因素，是否还存在别的什么原因？

**Comment by xu-li** [comment]
不是，微信的缩略图限制是32k，没有宽高限制。之前有人抱怨说图片分享不了，其实是因为文件大小超过限制了。所以我的做法就是在程序里面自动把图片裁成300px的，这样超过32k的几率就小很多。

你的情况就是第一张图片，在300px裁剪以后，没有超过32k。但是第二张超过了。

**Comment by loooooook** [comment]
恩 好的 非常感谢

**Comment by leedorian** [comment]
即便是两张很小的图都是108*108，原图都不超过10K，一张可以分享，另一张不可以，猜测是放大后超过32K了？图片缩放没有必要吧，用户自己使用符合微信标准的图就好了。

**Comment by jasonz1987** [comment]
图片尺寸小于300 应该不会放大了，我在这个地方加了一个二次保护，就是当图片缩放之后，判断图片大小，如果仍然大于32k则进行质量压缩，直至小于32k. 具体看 #457 #459

**Comment by leedorian** [comment]
@jasonz1987 解决了，感谢
