### ISSUE TITLE
android闪现微信界面后无反应

### ISSUE THREAD

**Issue by shally12** [xu-li/cordova-plugin-wechat#232]
system information:
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v0.12.7
Android版本: 5.0.2
代码如下：
`$scope.shareToWx = function(){
    Wechat.isInstalled(function (installed) {
      alert("Wechat installed: " + (installed ? "Yes" : "No"));
    }, function (reason) {
      alert("Failed: " + reason);
    });

 Wechat.share({
      message: {
        title: "Hi, there",
        description: "This is description.",
        thumb: "img/ionic.png",
        mediaTagName: "TEST-TAG-001",
        messageExt: "这是第三方带的测试字段",
        messageAction: "<action>dotalist</action>",
        media: {
          type: Wechat.Type.LINK,
          webpageUrl: 'http://tech.qq.com/zt2012/tmtdecode/252.htm'
        }
      },
      scene: Wechat.Scene.TIMELINE   // share to Timeline
    }, function () {
      alert("Success");
    }, function (reason) {
      alert("Failed: " + reason);
    });
}`

**Comment by xu-li** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues?utf8=%E2%9C%93&q=%E9%97%AA%E7%8E%B0

**Comment by yangheng** [comment]
这个问题是不是 应用程序没有签名啊？我也遇到过，android下面需要签名，需要在微信开放平台填写正确的签名信息才行
