### ISSUE TITLE
请问是否可以选择分享到朋友圈或选择好友分享

### ISSUE THREAD

**Issue by zyyanzi** [xu-li/cordova-plugin-wechat#235]
如题

**Comment by xu-li** [comment]
可以。https://github.com/xu-li/cordova-plugin-wechat/blob/develop/www/wechat.js#L5

**Comment by zyyanzi** [comment]
可能我没清楚表达我的意思，你说的可能只是通过代码写死分享到目的地，我的意思是：点击分享，这个插件是否提供弹出狂询问用户分享给好友、还是分享到朋友圈，之前看到ios好像有这个选择。

**Comment by xu-li** [comment]
点击分享，你的JS弹出自己写的popup，然后有2个选项，根据选项的不同掉用不同的函数(传不同的参数)。

如果ios里面重复了，那么判断当前是否是iOS，如果是，这个自定义popup就不用弹出，直接调用Wechat.share。
