### ISSUE TITLE
调用支付出现白色确定按钮，点击确定返回“普通错误”

### ISSUE THREAD

**Issue by leyan17** [xu-li/cordova-plugin-wechat#237]
var params = {
                mch_id:'1321236301',// merchant id
                prepay_id: 'wx20160608161736fe46a8b0dc0458021304',
                nonce: 'au4prLnGJ2wqqHow', // nonce
                timestamp: '1465373854', // timestamp
                sign: '0CD8F8E17D1C591404E571BC5B573758', // signed string
            };

集成方式是cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable wechatappid=（myappid）

还需添加什么么？（我的appid和params里的都是之前项目中可用的）

**Comment by leyan17** [comment]
有时候返回的是“failed：用户点击取消并返回”。急！盼回复

**Comment by xu-li** [comment]
后台返回的参数错误。邮件中说了。
