### ISSUE TITLE
苹果版本用这个插件， 只有第一次分享成功了，然后就没有然后了。。

### ISSUE THREAD

**Issue by junzaivip** [xu-li/cordova-plugin-wechat#238]
如题，麻烦帮忙看看呢 我按照您的方法全部都设置了， Android版本是可以正常使用的， 但是IOS版本就只能分享成功第一次。 其他人也有遇见这个问题吗？

**Comment by xu-li** [comment]
日志里面有东西么？别人基本都是iOS没问题，android都是问题。

**Comment by junzaivip** [comment]
项目[1135:1234833] INFO: fetch-response is unable to open the file /private/var/mobile/Containers/Data/Application/8CAE935D-E89F-43A2-87B9-E8C3FF3A299F/Library/Caches/com.junzaivip/nsurlcache/fsCachedData/329A64A5-FEF7-48D2-A004-9C5AC7C81315. Errno: 1
2016-07-28 17:07:28.517 项目[1135:1234741] THREAD WARNING: ['Wechat'] took '43.050049' ms. Plugin should use a background thread.
2016-07-28 17:07:28.541 项目[1135:1234741] THREAD WARNING: ['Wechat'] took '22.382080' ms. Plugin should use a background thread.

**Comment by junzaivip** [comment]
发送请求失败

**Comment by xu-li** [comment]
这个问题没碰到过。你重装一下App试试？

**Comment by liangxp** [comment]
我也是IOS的没法分享  头疼中，点击分享完全没反应，Android正常

**Comment by xu-li** [comment]
有什么错误么？
