### ISSUE TITLE
Wechat is not defined 

### ISSUE THREAD

**Issue by dfghj44444** [xu-li/cordova-plugin-wechat#239]
平台；mac
ionic 1.3版本
cordova－android@5.2
代码如下：  
       Wechat.isInstalled(function (installed) {
            alert("Wechat installed: " + (installed ? "Yes" : "No"));
        }, function (reason) {
            alert("Failed: " + reason);
        });
真机android测试，提示Wechat is not defined
update1.签名不签名都一样
update2.ios一样的问题，没有成功和失败的alert（）；，啥也没有，肯定是也没找到wechat

**Comment by dfghj44444** [comment]
没做签名，难道没签名就连变量Wechat也检测不到了？

**Comment by dfghj44444** [comment]
刚刚测试，签了名的也一样

**Comment by dfghj44444** [comment]
iOS编译log里有这条：CDVPlugin class CDVWechat (pluginName: wechat) does not exist.

**Comment by dfghj44444** [comment]
难道不能写在主页的初始化里？

**Comment by xu-li** [comment]
重装一下插件试试？重装以后再build？

**Comment by Liuhui11** [comment]
window.Wechat.isInstalled(function (installed) {
        alert('Wechat installed: ' + (installed ? 'Yes' : 'No'))
      }, function (reason) {
        alert('Failed: ' + reason)
      }) @dfghj44444

**Comment by mingxin-yang** [comment]
@Liuhui11 添加了window之后报Cannot read property 'isInstalled' of undefined的问题了
