### ISSUE TITLE
ios编译失败

### ISSUE THREAD

**Issue by wzcrystal** [xu-li/cordova-plugin-wechat#240]
添加这个插件之后，cordova build ios 时失败，失败code如下：

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/mac/Desktop/MobileFlup/platforms/ios/cordova/build-debug.xcconfig,-project,爱吉随访.xcodeproj,ARCHS=i386,-target,爱吉随访,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/mac/Desktop/MobileFlup/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/mac/Desktop/MobileFlup/platforms/ios/build/sharedpch

这是什么原因？

**Comment by xu-li** [comment]
http://stackoverflow.com/questions/34166175/cordova-run-with-ios-error-error-code-65-for-command-xcodebuild-with-args ?

**Comment by wzcrystal** [comment]
是要下载证书？

**Comment by xu-li** [comment]
你有apple开发者账号么？你发布的话要这个账号的。

**Comment by wzcrystal** [comment]
有开发者账号

**Comment by xu-li** [comment]
你用xcode打开项目，然后xcode会帮你下载必要的profile的。

**Comment by wzcrystal** [comment]
好的，我试试
