### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by wangzhiqiang1975** [xu-li/cordova-plugin-wechat#243]
运行例子时间有报JSON error

**Comment by xu-li** [comment]
具体代码？iOS还是android？

**Comment by yangguangpeng** [comment]
我也试过了例子，在安卓里出现json error同样的问题。

**Comment by yangguangpeng** [comment]
Wechat.share({
    message: {
        media: {
            type: Wechat.Type.LINK,
            webpageUrl: "http://tech.qq.com/zt2012/tmtdecode/252.htm"
        }
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

**Comment by xu-li** [comment]
需要title和description吧。

**Comment by yangguangpeng** [comment]
谢谢，xu-li
