### ISSUE TITLE
android 授权后  程序停止工作 

### ISSUE THREAD

**Issue by EasonJi** [xu-li/cordova-plugin-wechat#244]
麻烦看一下 android 授权后  程序停止工作  是什么原因？？3Q 万分感谢
开放平台注册了， 应用也签名也没有问题

**Comment by xu-li** [comment]
插件是最新版的么？

**Comment by EasonJi** [comment]
已经解决了  安装的时候  通过这个命令
cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID
插件下载不下来 报错，之后先把 cordova-plugin-wechat 下载到本地 直接放到项目中 修改配置 wechatapid  ，IOS没有问题 android 授权后 程序停止工作
解决方式 ，如果运命令运程下载不下来的话 可以先从网站下到本地
用cordova plugin add 本地插件的地址 --variable wechatappid=YOUR_WECHAT_APPID 安装
就没有问题 ，谢谢你的插件，很实用 ，3Q

**Comment by xu-li** [comment]
很可能你改的不是同一个文件，而且应该要重新```cordova build```。

不管怎么样，可以用了就行。
