### ISSUE TITLE
微信登陆被AppStore拒绝 

### ISSUE THREAD

**Issue by flintcreativestudio** [xu-li/cordova-plugin-wechat#246]
AppStore 规定使用微信登陆的话，不能强制需要用户安装第三方App才能使用该App。

以前很多人检测微信是否安装，否的话，隐藏微信登陆的按钮。现在AppStore已不支持微信稳当里面推荐的 ’如果没安装微信，隐藏掉微信登陆按钮‘

https://www.zhihu.com/question/34080893 

有描述原生接口的另一种验证的方式，能发送短信来验证。

我们能不能在这个插件也使用这个功能呢？

**Comment by xu-li** [comment]
最新版的插件有这个功能的。

**Comment by flintcreativestudio** [comment]
大哥，能否教怎么调用吗？文档没写

**Comment by xu-li** [comment]
不用调用，自动的啊。

**Comment by gaochunrong** [comment]
你好，今天下午我在ionic 装上了你cordova-plugin-wechat这个插件，也参考了上一个分享的例子，首先提示Wechat plugin is not installed.另外用这个处理微信第三方登录时，appid,appsecret这两个密钥如何配置，非常期待回复，或邮箱联系：397192243@qq.com,这方面项目咨询与合作。
