### ISSUE TITLE
分享至微信的链接，点击如何返回App

### ISSUE THREAD

**Issue by meiyalei** [xu-li/cordova-plugin-wechat#247]
利用该插件分享至微信的链接，
如何设置url才能，点击链接之后返回App内相应的页面？

**Comment by xu-li** [comment]
不行的。

**Comment by meiyalei** [comment]
好的，了解。多谢啦。

2016-08-31 22:54 GMT+08:00 lixu <notifications@github.com>:

**Comment by xiao1dian** [comment]
如果不行，怎么处理呢？



在 2016-09-06 17:36:43，"CaserWing" <notifications@github.com> 写道：
好的，了解。多谢啦。

2016-08-31 22:54 GMT+08:00 lixu <notifications@github.com>:
