### ISSUE TITLE
运行例子的Wechat.auth未能启动微信登录，也没报错

### ISSUE THREAD

**Issue by junhui75165** [xu-li/cordova-plugin-wechat#253]
例子我加了try  catch也没有报错也没有启动微信登录返回access_token，
`function WechatUse(){
        alert(2);
        try {
          var scope = "snsapi_userinfo";
          Wechat.auth(scope, function (response) {
            // you may use response.code to get the access token.
            alert(3);
            alert(JSON.stringify(response));
          }, function (reason) {
            alert("Failed: " + reason);
          });
        }catch (e){
          alert(e);
        }
      }`

使用的是安卓锤子T2，执行完alert2之后并没有3打印出来，想问一下什么原因

还有一个是微信分享使用例子提示是json error

**Comment by xu-li** [comment]
可以分享么？不可以分享的话，就是签名错了。可以去看FAQ。

**Comment by junhui75165** [comment]
分享的提示都是未知错误，前面不是在拿到access_token之后设置的吗，如果设置签名在哪里可以设置的，有没例子可以参考一下0.0

**Comment by xu-li** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN

**Comment by xinyi1989** [comment]
我也遇到了上面这个问题，点击之后没有反应。我看您上面的链接，微信上面说 调用时的Apk包名和签名是否与开放平台填写的一致。
我想问下，如果我的测试Apk没有签名，可以吗？
还会有什么其他问题能导致调用没有反应吗？

**Comment by junhui75165** [comment]
@xinyi1989 签名应该是必须的，文档中有个apk可以根据appkey生产签名，直接复制使用就行

**Comment by xinyi1989** [comment]
@junhui75165   我自己按照这个网页上面的给apk进行了签名。在微信开放平台也进行了配置。http://www.cnblogs.com/qianxudetianxia/archive/2011/04/09/2010468.html

现在点击还是没有反应。你那个现在可以调用微信正常登录吗？

**Comment by junhui75165** [comment]
@xinyi1989 正常了，当时因为签名不清楚随便填了个

**Comment by xinyi1989** [comment]
@junhui75165   有qq或者邮箱联系方式吗？我这边还是不好用，具体的签名和一些配置 能帮我看看吗？

**Comment by junhui75165** [comment]
@xinyi1989 这里的这个签名指的是微信开放平台的，并不是安卓的什么签名
![image](https://cloud.githubusercontent.com/assets/3411959/18899164/a2310fc8-8569-11e6-952b-bf8a4751a7dd.png)

**Comment by xinyi1989** [comment]
@junhui75165   那这么签名配置到项目的那个文件呢？  下面是我申请的测试的开放平台信息
![qq 20160928105617](https://cloud.githubusercontent.com/assets/22472112/18899261/33e38ef0-856a-11e6-959d-07bfd6f6ae98.png)

**Comment by junhui75165** [comment]
@xinyi1989 这里有签名生成工具 https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN

**Comment by xinyi1989** [comment]
@junhui75165  谢谢，恩 现在应该是可以了。
现在是提示scope参数错误或者没有scope权限。应该是我申请的开放平台没有开发者资质。
谢谢！！

**Comment by celinalc** [comment]
@xinyi1989 我现在提示的也是scope参数错误或者没有scope权限，请问是什么原因？你的解决了吗？谢谢

**Comment by xinyi1989** [comment]
@celinalc  你看下你的开放平台是否已经审核通过？
![qq 20160929154706](https://cloud.githubusercontent.com/assets/22472112/18945191/03992b36-865c-11e6-8c72-12ddb49f0e53.png)

**Comment by celinalc** [comment]
@xinyi1989 开发者资质一定要认证吗？我的移动应用已经通过了，可以得到appid

**Comment by xinyi1989** [comment]
@celinalc  一定要认证，我得已经认证通过，可以正常调用了。那个需要认证一些企业的信息，还要交审核费。所以也是腾讯挣钱的一种途径吧。

**Comment by celinalc** [comment]
@xinyi1989 哦哦，谢谢您啦

**Comment by 494155041** [comment]
@xinyi1989  我的插件为什么一直报1>Error : error : Please rebuild the solution. An unexpected plugin removal error occured: Object #<Object> has no method 'android_packageName'这是什么问题
