### ISSUE TITLE
android 下分享和支付的问题

### ISSUE THREAD

**Issue by dennyliua** [xu-li/cordova-plugin-wechat#256]
我的IOS 分享和支付都没有问题，但是 ANDROID 的 分享报  JSON error  支付报 “普通错误”  签名我用好几个手机核对了下没有错误，可能是什么原因？ 我需要从哪方便入手？

**Comment by dennyliua** [comment]
分享日志是这个样子的。
```
09-19 22:10:13.259 14186-15817/com.aa.starter D/Cordova.Plugin.Wechat: Start building message.
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: Failed to build sharing message.
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: org.json.JSONException: No value for description
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.get(JSONObject.java:389)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.getString(JSONObject.java:550)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat.buildSharingMessage(Wechat.java:324)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat$1.run(Wechat.java:189)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.lang.Thread.run(Thread.java:818)
09-19 22:10:13.260 14186-14186/com.aa.starter D/WebView: setNetworkAvailable=false
09-19 22:10:13.261 14186-15817/com.aa.starter I/Cordova.Plugin.Wechat: Message has been sent unsuccessfully.
09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Attempted to send a second callback for ID: Wechat*****
09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Result was: "发送请求失败"
```

**Comment by januslo** [comment]
Title 和description必填，写个空字符串进入吧

发自我的 iPhone

**Comment by dennyliua** [comment]
嗯 嗯，昨天找到这个问题了的原因了，谢谢。

发件人:  janus j k lu
答复:  xu-li/cordova-plugin-wechat
日期:  2016年9月19日 星期一 下午10:53
至:  xu-li/cordova-plugin-wechat
抄送:  刘强, State change
主题:  Re: [xu-li/cordova-plugin-wechat] android 下分享和支付的问题 (#256)

Title 和description必填，写个空字符串进入吧

发自我的 iPhone

> 在 2016年9月19日，下午10:12，dennyliua <notifications@github.com> 写道：
> 
> 分享日志是这个样子的。
> 
> 09-19 22:10:13.259 14186-15817/com.aa.starter D/Cordova.Plugin.Wechat: Start building message.
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: Failed to build sharing message.
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: org.json.JSONException: No value for description
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.get(JSONObject.java:389)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.getString(JSONObject.java:550)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat.buildSharingMessage(Wechat.java:324)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat$1.run(Wechat.java:189)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.lang.Thread.run(Thread.java:818)
> 09-19 22:10:13.260 14186-14186/com.aa.starter D/WebView: setNetworkAvailable=false
> 09-19 22:10:13.261 14186-15817/com.aa.starter I/Cordova.Plugin.Wechat: Message has been sent unsuccessfully.
> 09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Attempted to send a second callback for ID: Wechat*****
> 09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Result was: "发送请求失败"
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xu-li/cordova-plugin-wechat","title":"xu-li/cordova-plugin-wechat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xu-li/cordova-plugin-wechat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@januslo in #256: Title 和description必填，写个空字符串进入吧\n\n发自我的 iPhone\n\n\u003e 在 2016年9月19日，下午10:12，dennyliua \u003cnotifications@github.com\u003e 写道：\n\u003e \n\u003e 分享日志是这个样子的。\n\u003e \n\u003e 09-19 22:10:13.259 14186-15817/com.aa.starter D/Cordova.Plugin.Wechat: Start building message.\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: Failed to build sharing message.\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat: org.json.JSONException: No value for description\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.get(JSONObject.java:389)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at org.json.JSONObject.getString(JSONObject.java:550)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat.buildSharingMessage(Wechat.java:324)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at xu.li.cordova.wechat.Wechat$1.run(Wechat.java:189)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)\n\u003e 09-19 22:10:13.260 14186-15817/com.aa.starter E/Cordova.Plugin.Wechat:     at java.lang.Thread.run(Thread.java:818)\n\u003e 09-19 22:10:13.260 14186-14186/com.aa.starter D/WebView: setNetworkAvailable=false\n\u003e 09-19 22:10:13.261 14186-15817/com.aa.starter I/Cordova.Plugin.Wechat: Message has been sent unsuccessfully.\n\u003e 09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Attempted to send a second callback for ID: Wechat*****\n\u003e 09-19 22:10:13.261 14186-15817/com.aa.starter W/CordovaPlugin: Result was: \"发送请求失败\"\n\u003e —\n\u003e You are receiving this because you are subscribed to this thread.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/xu-li/cordova-plugin-wechat/issues/256#issuecomment-248016484"}}}
