### ISSUE TITLE
WeChat sharing not working for iOS?

### ISSUE THREAD

**Issue by charlieqf** [xu-li/cordova-plugin-wechat#26]
Hi Xu,

Thank you very much for this great plugin!

I am trying to use it in VisualStudio with Telerik AppBuilder.

I am mainly using it for sharing to WeChat. I was initially using Eddy's version from the Telerik Plugin Marketplace, it worked well for Android but on iOS I could only share a picture and nothing else. If I pass in multiple parameters, the WeChat option does not even appear in the share sheet.

Maybe WeChat has not enabled some interface for iOS? But why does the image work.

I wanted to troubleshoot this issue so I tried to use your package downloaded from GitHub instead of the Telerik Marketplace one. But then I could not get it working in VisualStudio at all. I tried to follow your install instructions but those steps are targeting XCode I think, I couldn't follow exactly in VisualStudio.

Can you shed some light on how I can use this GitHub downloaded plugin in VisualStudio? Or any idea why the plugin works on Android but not iOS.

Thank you very much!

Charlie

**Comment by xu-li** [comment]
Hi @charlieqf ,

This plugin is trying to port the whole set of Wechat API to be used in Javascript, so it uses Wechat SDK behind the scene. [Eddy's version](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) focuses on sharing, and it utilizes system accounts(and share sheet) behind the scene. 

Maybe you can try to play around other parameters when using Eddy's version. AFAIK, title and description differs across platforms. Sometime title will work, and sometime description will work.

Regarding installing this plugin in VisualStudio, I don't have any experience of VisualStudio or Telerik AppBuilder. Maybe [this link](http://blogs.telerik.com/appbuilder/posts/13-06-25/custom-cordova-plugins-with-icenium-and-more) could help.

Thanks,
Xu
