### ISSUE TITLE
同一订单第一次发起请求成功，取消后再次发起返回“普通错误”

### ISSUE THREAD

**Issue by train860** [xu-li/cordova-plugin-wechat#260]
第一次请求成功了，说明签名信息没有问题。第二次请求发送的数据跟第一次完全一样。
请问知道大概是什么原因吗？
谢谢

**Comment by gdmec07140540** [comment]
我也是，就提示一个普通错误，怎么解决

**Comment by elevensheep** [comment]
同问。。。

**Comment by gdmec07140540** [comment]
我之前是签名错误导致提示‘普通错误’，后面改了签名可以支付时，特意取消支付测试，发现再次支付就会再提示‘普通错误’，我就修改后台，每次请求支付时都生成一个新的商户本地订单号给微信，就可以了

**Comment by zurmokeeper** [comment]
我也是遇到了这个问题，不要再纠结为什么第一次可以，后面的不行了。

我的解决方法是：用个工具：链接 https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=8_5 参考安卓部分。
拿到你的app的应用签名，然后填到你的微信后台去，再次跑就可以了。

应用签名填写位置：https://github.com/xu-li/cordova-plugin-wechat/issues/380 参考这个链接的。

同时你的APP包名和微信后台设置的那个包名也要一样的。
