### ISSUE TITLE
安卓下签名后可以实现分享功能但支付报普通错误是什么原因

### ISSUE THREAD

**Issue by z448401921** [xu-li/cordova-plugin-wechat#263]

**Comment by shuhanxu** [comment]
我也遇到了同样的问题

**Comment by z448401921** [comment]
如果你安卓上分享没问题的话，那就是微信服务端生成签名的问题。我的已经解决了。

**Comment by shuhanxu** [comment]
感谢回复 我是用https://github.com/tvrcgo/weixin-pay 后端自动算的md5签名， 你是用php后端吗？

**Comment by shuhanxu** [comment]
你是不是说的这步
”统一下单接口返回正常的prepay_id，再按签名规范重新生成签名后，将数据传输给APP。参与签名的字段名为appId，partnerId，prepayId，nonceStr，timeStamp，package。注意：package的值格式为Sign=WXPay“

**Comment by z448401921** [comment]
是用的C#，如果分享功能没问题的话，就是服务端生成签名的问题。我的是后台字段没统一，发起支付的时候用的是'noncestr',但服务端签名用的是微信官方的'nonce_str'，这样在生成sign时就会不统一。
