### ISSUE TITLE
安卓下分享 JSON error

### ISSUE THREAD

**Issue by xpsp312** [xu-li/cordova-plugin-wechat#264]
如题，安卓下分享的时候，JSON error，检查app_id，签名、包名都一致，是不是我使用有问题？安装完插件之后，直接调用的分享，代码如下：
`Wechat.share({
          message: {
            title: "Hi, there",
            description: "This is description.",
            thumb: "http://paperInterface.zaixun.wang/logo.png",
            mediaTagName: "TEST-TAG-001",
            messageExt: "这是第三方带的测试字段",
            messageAction: "",
            media: "YOUR_MEDIA_OBJECT_HERE"
          },
          // scene: Wechat.Scene.TIMELINE   // 分享到朋友圈
          scene : Wechat.Scene.SESSION//分享到好友
        }, function () {
          alert("Success");
        }, function (reason) {
          alert("Failed: " + reason);
        });`

求解决~

**Comment by xu-li** [comment]
"YOUR_MEDIA_OBJECT_HERE"， 是需要你替换的啊。

比如
```
media: {
        type: Wechat.Type.WEBPAGE,
        webpageUrl: "http://tech.qq.com/zt2012/tmtdecode/252.htm"
}
```

**Comment by xpsp312** [comment]
多谢大神，一直没有留意这个参数~~问题完美解决，谢谢！
