### ISSUE TITLE
android分享一闪而过

### ISSUE THREAD

**Issue by aniy00** [xu-li/cordova-plugin-wechat#265]
Wechat.share({
        message: {
          title: "Hi, there",
          description: "This is description.",
          thumb: "www/img/ionic.png",
          mediaTagName: "TEST-TAG-001",
          messageExt: "这是第三方带的测试字段",
          messageAction: "<action>dotalist</action>",
          media: {
            type: Wechat.Type.WEBPAGE,
            webpageUrl: "https://www.baidu.com"
          }
        },
        scene: Wechat.Scene.TIMELINE   // share to Timeline
      }, function () {
        alert("Success");
      }, function (reason) {
        alert("Failed: " + reason);
      });

签名是打包安装后，用开发中心的
![image](https://cloud.githubusercontent.com/assets/20589767/18979767/73363d72-8700-11e6-9c38-f2646559e1ae.png)，在手机上获取的“cf72e4ff21344b38440c73a6f3909d95”，然后修改开发者中心应用设置应用签名：cf72e4ff21344b38440c73a6f3909d95，分享的时候还是会一闪，请问这是什么问题

**Comment by happen-zh** [comment]
<preference name="WECHATAPPID" value="YOUR_WECHAT_APP_ID_HERE" /> 
添加到config.xml
