### ISSUE TITLE
关于安卓混合应用的分享

### ISSUE THREAD

**Issue by zhurizhe** [xu-li/cordova-plugin-wechat#269]
我的安卓应用是用cordova打包的混合应用，遇到一个问题，我从微信分享完之后，返回自己的应用，整个应用等于是重新打开了，页面刷新了，这样我就相当于是从一个文章详情页进行分享，结果返回到了首页。

这个问题是否有办法解决呢？能否返回时不要刷新应用？

**Comment by xu-li** [comment]
默认不会刷新。除非你的内存不够，应用被自动关掉了。

**Comment by zhurizhe** [comment]
内存2G，清除内存之后有1G的空闲内存，红米手机，返回时会刷新应用，我再测试一下其他设备吧。
