### ISSUE TITLE
微信分享多张图片到朋友圈

### ISSUE THREAD

**Issue by zhengnz** [xu-li/cordova-plugin-wechat#27]
Xu，您好，请问这个插件能分享多张图片到微信朋友圈吗？如果能能麻烦您给一个示例吗？我尝试了很多次，总是无法分享图片，非常感谢您这个插件，帮了我很大的忙

**Comment by xu-li** [comment]
@zhengnz ,据我所知，SDK 不支持分享多张图片。你可以考虑合并成一张，然后分享。

在文档中, WXMediaMessage只有一个mediaObject。

**Comment by zhengnz** [comment]
@xu-li 您好，非常感谢您的回复，主要是我看到有一个叫微商易的app，里面是可以分享多张图片到微信的，难道他不是基于微信提供的SDK?

**Comment by xu-li** [comment]
应该没用SDK，你可以看看这个[[Android分享] 不使用官方SDK,实现微信分享（发送到朋友，发送到朋友圈）](http://www.eoeandroid.com/thread-288401-1-1.html).

具体微商易怎么实现的，我不是很清楚。

**Comment by zhengnz** [comment]
好的，谢谢您
