### ISSUE TITLE
插件无法安装报错

### ISSUE THREAD

**Issue by VictorYuan666** [xu-li/cordova-plugin-wechat#273]
Error: Failed to fetch plugin cordova-plugin-wechat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: shasum check failed for /var/folders/8x/w8xmmcsd4491fb44cgdh7c0r0000gn/T/npm-59880-369b33c0/registry.npmjs.org/cordova-plugin-wechat/-/cordova-plugin-wechat-1.3.0.tgz
Expected: 1787d27e447961d6dd934a22384738c2017c30c4
Actual:   7f495de3bb6ce640ada7c109f7561a5d8d683b4f
From:     https://registry.npmjs.org/cordova-plugin-wechat/-/cordova-plugin-wechat-1.3.0.tgz

**Comment by xu-li** [comment]
网络问题，再试试。
