### ISSUE TITLE
如果我只需要进行微信朋友圈分享，需要把微信开发者验证通过吗？

### ISSUE THREAD

**Issue by lukelee1124** [xu-li/cordova-plugin-wechat#274]
我用您的插件，安装在android上，但是在release apk上点击“分享到朋友圈”，结果没有任何反应，是不是我的开发者账号没有通过验证？按照微信的开发文档，分享朋友圈这个权限，应该不需要进行验证？

另外，请教一下，ionic在android上该怎么调试啊？

**Comment by xu-li** [comment]
android需要你的app通过审核，而且release的apk可能签名不一样。

ionic的调试指什么？前端JS，还是插件的问题，还是android其它东西？前端JS，简单的可以用console.log或者alert，或者chrome的web view。插件的问题，你就用adb的log。

**Comment by lukelee1124** [comment]
您好，我明白我的app需要通过审核，也明白release的apk签名可能不同。我想问的是，使用您的插件，是否需要我的微信开发者账号通过微信的验证？

**Comment by xu-li** [comment]
不需要的。

**Comment by xu-li** [comment]
不需要。
