### ISSUE TITLE
android微信登录获取用户信息返回40001错误,以及分享格式问题

### ISSUE THREAD

**Issue by cn-qiuhong** [xu-li/cordova-plugin-wechat#275]
之前用hbuilder的微信登录，已经确保签名、包名、appid、secret都没有问题。但是hbuilder的webview性能太差，功能也差，所以还是回来用cordova。之前因为签名的问题，一直调不出授权页面，现在能授权了，也获取到access_token了，但是用access_token去获取用户信息就出错了，希望大神帮帮忙。我测试了分享功能，可以成功分享。分享除了示例中的文本分享，网页分享，其他的没有测试成功，在此想一起问一下，我要分享我手机中的图片该怎么写？

**Comment by cn-qiuhong** [comment]
我2了，今天有时间好好研究了一下登录和分享功能，发现我忘记了一个问题，返回的是字符串，不是对象，要调用JSON.parse()对象化。至此登录功能已搞定。但是分享media还是要请教一下大神，我今天在之前的问题中找到一个分享canvas截屏的方法，我想问分享其他东西的格式是什么样的，比如我今天看到的那个分享canva截屏是这样的:
media: {
	type: Wechat.Type.IMAGE,
	image: canvas.toDataURL()
}
type我打印了有7种，除了image和webpage能请大神告诉我其他几种的格式吗？谢谢！

**Comment by xu-li** [comment]
这里: https://github.com/xu-li/cordova-plugin-wechat/blob/develop/www/wechat.js#L10
