### ISSUE TITLE
unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by phanthinh** [xu-li/cordova-plugin-wechat#276]
Hi @xu-li 

I saw error message when build with X-CODE. See attachment pls
![screen shot 2016-10-30 at 10 16 11](https://cloud.githubusercontent.com/assets/5910795/19834235/fa5a91c2-9e89-11e6-9f1d-baa00472858a.png)

**Comment by xu-li** [comment]
See http://stackoverflow.com/questions/25007755/unable-to-execute-command-segmentation-fault-11-swift-frontend-command-failed.

> After struggling for a long time, I disabled the Bitcode in Project's Target > Build Settings > Enable Bitcode. Now the project can be archived. Please check the following screenshot.

Good luck.

**Comment by phanthinh** [comment]
It's should be work fine now. Thanks 👍
