### ISSUE TITLE
ionic 微信登陆

### ISSUE THREAD

**Issue by wangwanttt** [xu-li/cordova-plugin-wechat#277]
我的步骤如下：
1、通过ionic 生成一个android apk包
 cordova run android --release
2、再将 生成的 android-armv7-release-unsigned.apk ，放到jdk/bin 下 生成签名
jarsigner -verbose -keystore tm51App.keystore -signedjar tm51app.apk tm51.apk tm51App.keystore 
正在签名: classes.dex
正在签名: lib/armeabi-v7a/libxwalkcore.so
正在签名: lib/armeabi-v7a/libxwalkdummy.so
jar 已签名。

3、再在ionic中
  //微信登陆
      $scope.weChatlogin=function()
      {
          var scope = "snsapi_userinfo",
            state = "_" + (+new Date());
          Wechat.auth(scope, state, function (response) {
            // you may use response.code to get the access token.
            alert(JSON.stringify(response));
          }, function (reason) {
            alert("Failed: " + reason);
          });

----------- 即不报正确 也不报错误，【签名应该正确的，我是先审核通过后，再用签名工具得到签名 然后修改了 应用签名保存到 微信开放平台的，因为申请时是瞎写的签名字符
Android平台
应用下载地址：未填写
应用签名：2e4d4f465232f579aafe377a4c63931a
包名：com.ionicframework.tm51】

**Comment by wangwanttt** [comment]
ionic plugin add cordova-plugin-wechat --variable wechatappid=微信appid
这个搞错了，我后来又  ionic plugin add cordova-plugin-wechat --variable wechatappid=正确的appid 一次 。还改了 
plugins下的  android.json 中的  wechatappid:改为正确的appid了
fetch.josn 中的  wechatappid:改为正确的appid了

**Comment by wangwanttt** [comment]
Wechat.isInstalled(function (_installed) {
        installed=_installed;
        alert("手机上安装微信: " + (installed ? "Yes" : "No"));  ----------- 但这个又能提示yes ，

**Comment by xu-li** [comment]
"但这个又能提示yes", 什么意思？

**Comment by JianGuo222** [comment]
我的android wechat.auth 也提示 Failed: 未知错误

**Comment by JianGuo222** [comment]
是不是因为我还没有缴费300元 拿到微信开发者资质认证？我看到在我的管理中心app里 微信登陆接口未获得， 点击申请 弹出错误窗口：未认证开发者无法申请开通微信登录

**Comment by yjb2020** [comment]
特别说明2：微信登录必须要正式打包签名才可以，直接通过Eclipse安装是无效的

估计和这个有关。

**Comment by funlake** [comment]
android wechat.auth提示 Failed: 未知错误，在部分手机上会有此问题，到底是什么原因呢？

**Comment by daileimail** [comment]
遇到坑，调用WeChat.auth() 不跳转微信 双击home才能跳转，我操了，什么鬼

**Comment by shinrun** [comment]
一直报未知错误-6
