### ISSUE TITLE
微信支付的参数问题

### ISSUE THREAD

**Issue by junhui75165** [xu-li/cordova-plugin-wechat#278]
`var params = {
          mch_id: '', // merchant id公众账号ID
          prepay_id: '', // prepay id预支付交易会话ID
          nonce: randomWord(32), // nonce随机字符串
          timestamp:new Date().getTime(), // timestamp时间戳
          //sign: '' // signed string签名
        };`
想问一下，这里mach_id是在审核通过支付功能的邮件上提供，nonce是自己生产的随机数，timestamp是自己生产的时间戳，还有一个prepay_id从哪里可以拿到？
还有一个，sign生产规则里是有appid和package，这里产生sign的时候是否要把这两个参数纳入进来生成sign

**Comment by gdmec07140540** [comment]
prepay_id是调用微信统一下单接口成功后返回的参数

**Comment by xu-li** [comment]
可以查看官方的文档。
