### ISSUE TITLE
微信支付，提示‘普通错误’

### ISSUE THREAD

**Issue by gdmec07140540** [xu-li/cordova-plugin-wechat#279]
后台调用统一下单接口没问题，用返回的数据调用微信支付方法时，每次都提示‘普通错误’，不知道这个提示是什么意思，找不到问题所在

**Comment by xu-li** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%E6%94%AF%E4%BB%98%20%E6%99%AE%E9%80%9A%E9%94%99%E8%AF%AF%20
