### ISSUE TITLE
[iOS] support weixin payment

### ISSUE THREAD

**Issue by aqingsao** [xu-li/cordova-plugin-wechat#28]
您好：
请问有没有计划支持微信支付？
与支付宝类似，在app中支持微信支付也很重要，现在微信已经提供了微信支付的API（需要申请开通），不知道有没有计划支持呢？

**Comment by xu-li** [comment]
See #23 .

**Comment by jackyon** [comment]
+1

**Comment by jackyon** [comment]
请问微信支付功能预期什么时候能够加入？目前很需要这个功能～谢谢

**Comment by xu-li** [comment]
暂时没计划，因为没有账号来做测试。

**Comment by vitohe** [comment]
@xu-li 
hi，我这边可以提供用于开发微信支付的测试账号，如果需要的话给我一个联系方式。

**Comment by clock157** [comment]
@xu-li 你好,我也获取了微信支付权限,如果需要可以联系我. 83113497

**Comment by xu-li** [comment]
多谢大家。能否发我的邮箱: AthenaLightenedMyPath@gmail.com。

**Comment by xu-li** [comment]
多谢 @vitohe, @clock157 提供测试帐号。

现在我把微信支付加上去了，见[develop分支](https://github.com/xu-li/cordova-plugin-wechat/tree/develop)。我在iOS上测试过，可以成功调用支付。Android上，需要你们的来测试一下，我没有你们的keystore。

安装方法:
```
cordova plugin add https://github.com/xu-li/cordova-plugin-wechat#develop --variable wechatappid=YOUR_WECHAT_APPID
```

如果有问题，欢迎发邮件或者留言。

**Comment by wangxiqiang** [comment]
android上经过测试，点击支付无任何反应

**Comment by xu-li** [comment]
@wangxiqiang 请问分享有作用么？支付的代码你是怎么写的？

**Comment by wangxiqiang** [comment]
分享，登录都有作用。均正常。先由服务器生成prepayid，nonce，timestamp，sign，然后组成数组抛给webchat.sendPaymentRequest。按理说，不管参数对不对，均可以调起微信端。但现在是没有任何的反应。

**Comment by ryanlin1986** [comment]
+1

**Comment by xu-li** [comment]
@wangxiqiang @ryanlin1986 搞错了app id和open id。现在应该好了。

真不好意思。

**Comment by wangxiqiang** [comment]
@xu-li 还是没有调起微信。我看了下微信官方demo，你这里还少了个package。
```java
signParams.add(new BasicNameValuePair("appid", req.appId));
		signParams.add(new BasicNameValuePair("noncestr", req.nonceStr));
		signParams.add(new BasicNameValuePair("package", req.packageValue));
		signParams.add(new BasicNameValuePair("partnerid", req.partnerId));
		signParams.add(new BasicNameValuePair("prepayid", req.prepayId));
		signParams.add(new BasicNameValuePair("timestamp", req.timeStamp));
```

**Comment by wangxiqiang** [comment]
@xu-li 还是无法调起微信。可能两边的生成签名的参数大小写的问题。待查实后再反馈

**Comment by goneaway1981** [comment]
你好，我尝试用VS2015+Cordova添加微信的分享插件，然后编译会报错，
错误		version not found: 0.8.0 : xu.li.cordova.wechat/0.8.0	AngularJSToDo	F:\00_Work1\05.Test\13-Cordova\AngularJSToDo\AngularJSToDo\MDAVSCLI	1
不知道这个错误是什么原因导致的？我完全是个新手，不胜感谢

**Comment by xu-li** [comment]
@goneaway1981 不好意思，没用过VS2015。

**Comment by zhougn** [comment]
android点支付无反应的估计是因为没有在微信开放平台绑定应用签名
http://fangjie.info/android微信支付/

@xu-li 虽然android能正常支付，但是完成后没有调用callback，这是个bug吗？iOS正常。

**Comment by xu-li** [comment]
@zhougn 应该是bug。请问：
1. 支付完成后，回到你的app了么？
2. 你调用其它API(比如分享)，callback正常么？

多谢测试。

**Comment by zhougn** [comment]
1. 支付完成能正常回到app
2. Wechat.auth的callback正常

**Comment by Huikit** [comment]
可以请问如何获取签名 统一下单的方法吗？

**Comment by ryanlin1986** [comment]
@xu-li  我也有和@zhougn同样的问题，支付成功以后点击完成， 微信管比可以正常回到app，但是callback并没有调用。

**Comment by ryanlin1986** [comment]
@xu-li  补充下， 进入微信支付页面以后，直接按返回键关闭微信支付界面回到app以后，失败callback也没被调用。

**Comment by ryanlin1986** [comment]
@xu-li  看了下微信sdk demo，目录下的请先阅读这里有这么一句：
要保证回调类WXPayEntryActivity.java文件必须位于包名的wxapi目录下，否则会导致无法回调的情况，注意：此条仅仅适用于android,ios有固定格式，请参考ios demo。

是否这是导致回掉不成功的原因？

**Comment by ryanlin1986** [comment]
android可以支付（虽然没回调），iOS启动微信以后，界面是空白，中间显示“确定”按钮，只能点确定，点击以后关闭微信回到原界面，取消回调有调用到。
环境：cordova 5.1.1.1， 需要做特殊处理吗？

**Comment by xu-li** [comment]
@ryanlin1986 不确定android的问题，我明天看一下。

ios界面空白，基本是你的参数错误，后台代码可以参照[这里](https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php)。

**Comment by xu-li** [comment]
@Huikit 参照[这里的PHP实现](https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php)，或者[官方文档](https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=9_1).

**Comment by Huikit** [comment]
@xu-li 感谢 已经成功 继续支持插件开发

**Comment by xu-li** [comment]
@ryanlin1986 你是对的。微信支付的回调竟然和分享的回调用的不是同一个Activity。

多谢 @zhougn 和 @ryanlin1986 提供测试。

**Comment by ryanlin1986** [comment]
@xu-li 经测试android版已经回调已经成功，非常感谢！

**Comment by ryanlin1986** [comment]
请问大家有在iOS上成功发起过支付的吗？ 
android下可以，iOS总是打开微信以后空白背景只有一个确定按钮。
确定用的参数是android iOS完全一样(服务端返回）。

**Comment by ryanlin1986** [comment]
不好意思问题已解决，
时间戳我弄成毫秒了，android上正常，实际上应该用秒，android，ios都OK了。

**Comment by BBPen** [comment]
https://api.mch.weixin.qq.com/pay/unifiedorder,这个接口我是在客户端请求的，这样会影响正常支付吗？
iOS总是打开微信以后空白背景只有一个确定按钮。因为没有服务端notify_url这个参数填随便填的“http://localhost”，不知道什么原因导致的不能支付请求帮助 @xu-li

**Comment by xu-li** [comment]
@BBPen **http://localhost**肯定是可以的，我的[DEMO](https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php)用的也是这个。具体是否可以在客户端请求unifiedorder API，这个你要问微信官方，在服务端请求肯定是可以的。

回到空白页面的问题，基本是参数问题。你可以参考这个帖子前面几个回复。

**Comment by BBPen** [comment]
微信还没给我回复，我的代码是这样的：
var url = "https://api.mch.weixin.qq.com/pay/unifiedorder";
                      var timestamp = Date.parse(new Date()) / 1000;
                      var ip = "120.35.43.34";
                      var stringA = 'appid=wx79485d7b9f5a8896&body=APP支付测试&mch_id=1330075601&nonce_str=' + timestamp + '&notify_url=http://localhost&out_trade_no=' + timestamp + 'pa&spbill_create_ip=' + ip + '&total_fee=1&trade_type=APP&key=YKQ1234567890yangkengqiang876543';
                      var sign = md5(stringA).toLocaleUpperCase();
                      $http({
                        method: 'post',
                        url: url,
                        headers: {
                          "Content-Type": 'application/xml',
                          "Accept": "application/json;charset=utf-8",
                          "Accept-Charset": "charset=utf-8"
                        },
                        data: "<xml>" +
                        "<appid>wx79485d7b9f5a8896</appid>" +
                        "<mch_id>1330075601</mch_id>" +
                        "<nonce_str>" + timestamp + "</nonce_str>" +
                        "<body>APP支付测试</body>" +
                        "<out_trade_no>" + timestamp + "pa</out_trade_no>" +
                        "<total_fee>1</total_fee>" +
                        "<spbill_create_ip>" + ip + "</spbill_create_ip>" +
                        "<notify_url>http://localhost</notify_url>" +
                        "<trade_type>APP</trade_type>" +
                        "<sign>" + sign + "</sign>" +
                        "</xml>"
                      }).success(function (data) {
                          console.log(data)
                          var prepay = data.slice(data.indexOf('<prepay_id><![CDATA[') + 20, data.indexOf(']]></prepay_id>'))
                          var params = {
                            partnerid: '1330075601', // merchant id
                            prepayid: prepay, // prepay id
                            noncestr: timestamp + 'pa', // nonce
                            timestamp: timestamp, // timestamp
                            sign: sign, // signed string
                          };
                          Wechat.sendPaymentRequest(params, function () {
                            alert("Success");
                          }, function (reason) {
                            console.log("失败")
                            console.log(reason)
                            //支付失败
                            //$scope.createTable();
                          });
                        }
                      )，
接口的返回值是：
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx79485d7b9f5a8896]]></appid>
<mch_id><![CDATA[1330075601]]></mch_id>
<nonce_str><![CDATA[Yo9LoCoLdeQAQ60J]]></nonce_str>
<sign><![CDATA[C27C6C3ED97FD0D0547105319BD1ECE8]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx2016041415272954ed46fac00626760315]]></prepay_id>
<trade_type><![CDATA[APP]]></trade_type>
</xml>，请帮我看一下哪块有传参错误  @xu-li

**Comment by BBPen** [comment]
微信还没回复我，我的代码是这样的：
`var url = "https://api.mch.weixin.qq.com/pay/unifiedorder";
                      var timestamp = Date.parse(new Date()) / 1000;
                      var ip = "120.35.43.34";
                      var stringA = 'appid=wx79485d7b9f5a9996&body=APP支付测试&mch_id=1330075661&nonce_str=' + timestamp + '&notify_url=http://localhost&out_trade_no=' + timestamp + 'pa&spbill_create_ip=' + ip + '&total_fee=1&trade_type=APP&key=123456789012343432dfsd';
                      var sign = md5(stringA).toLocaleUpperCase();
                      $http({
                        method: 'post',
                        url: url,
                        headers: {
                          "Content-Type": 'application/xml',
                          "Accept": "application/json;charset=utf-8",
                          "Accept-Charset": "charset=utf-8"
                        },
                        data: "<xml>" +
                        "<appid>wx79485d7b9f5a8896</appid>" +
                        "<mch_id>1330075601</mch_id>" +
                        "<nonce_str>" + timestamp + "</nonce_str>" +
                        "<body>APP支付测试</body>" +
                        "<out_trade_no>" + timestamp + "pa</out_trade_no>" +
                        "<total_fee>1</total_fee>" +
                        "<spbill_create_ip>" + ip + "</spbill_create_ip>" +
                        "<notify_url>http://localhost</notify_url>" +
                        "<trade_type>APP</trade_type>" +
                        "<sign>" + sign + "</sign>" +
                        "</xml>"
                      }).success(function (data) {
                          console.log(data)
                          var prepay = data.slice(data.indexOf('<prepay_id><![CDATA[') + 20, data.indexOf(']]></prepay_id>'))
                          var params = {
                            partnerid: '1330075601', // merchant id
                            prepayid: prepay, // prepay id
                            noncestr: timestamp + 'pa', // nonce
                            timestamp: timestamp, // timestamp
                            sign: sign, // signed string
                          };
                          Wechat.sendPaymentRequest(params, function () {
                            alert("Success");
                          }, function (reason) {
                            console.log("失败")
                            console.log(reason)
                            //支付失败
                            //$scope.createTable();
                          });
                        }
                      )`
接口返回值是：
`<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx79485d7b9f5a9996]]></appid>
<mch_id><![CDATA[1330075661]]></mch_id>
<nonce_str><![CDATA[Yo9LoCoLdeQAQ60J]]></nonce_str>
<sign><![CDATA[C27C6C3ED97FD0D0547105319BD1ECE8]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx2016041415272954ed46fac00626760315]]></prepay_id>
<trade_type><![CDATA[APP]]></trade_type>
</xml>`请问这样有没有传参错误 @xu-li

**Comment by BBPen** [comment]
var url = "https://api.mch.weixin.qq.com/pay/unifiedorder";
                      var timestamp = Date.parse(new Date()) / 1000;
                      var ip = "120.35.43.34";
                      var stringA = 'appid=wx79485d7b9f5a8896&body=APP支付测试&mch_id=1330075661&nonce_str=' + timestamp + '&notify_url=http://localhost&out_trade_no=' + timestamp + 'pa&spbill_create_ip=' + ip + '&total_fee=1&trade_type=APP&key=有正确的key';
                      var sign = md5(stringA).toLocaleUpperCase();     
$http({
                        method: 'post',
                        url: url,
                        headers: {
                          "Content-Type": 'application/xml',
                          "Accept": "application/json;charset=utf-8",
                          "Accept-Charset": "charset=utf-8"
                        },
                        data: "<xml>" +
                        "<appid>wx79485d7b9f5a9996</appid>" +
                        "<mch_id>1330075661</mch_id>" +
                        "<nonce_str>" + timestamp + "</nonce_str>" +
                        "<body>APP支付测试</body>" +
                        "<out_trade_no>" + timestamp + "pa</out_trade_no>" +
                        "<total_fee>1</total_fee>" +
                        "<spbill_create_ip>" + ip + "</spbill_create_ip>" +
                        "<notify_url>http://localhost</notify_url>" +
                        "<trade_type>APP</trade_type>" +
                        "<sign>" + sign + "</sign>" +
                        "</xml>"
                      }).success(function (data) {
                          console.log(data)
                          var prepay = data.slice(data.indexOf('<prepay_id><![CDATA[') + 20, data.indexOf(']]></prepay_id>'))
                          var params = {
                            partnerid: '1330075661', // merchant id
                            prepayid: prepay, // prepay id
                            noncestr: timestamp + 'pa', // nonce
                            timestamp: timestamp, // timestamp
                            sign: sign, // signed string
                          };
                          Wechat.sendPaymentRequest(params, function () {
                            alert("Success");
                          }, function (reason) {
                            console.log("失败")
                            console.log(reason)
                            //支付失败
                            //$scope.createTable();
                          });
                        }
                      )
接口返回值：
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx79485d7b9f5a8896]]></appid>
<mch_id><![CDATA[1330075601]]></mch_id>
<nonce_str><![CDATA[Yo9LoCoLdeQAQ60J]]></nonce_str>
<sign><![CDATA[C27C6C3ED97FD0D0547105319BD1ECE8]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx2016041415272954ed46fac00626760315]]></prepay_id>
<trade_type><![CDATA[APP]]></trade_type>
</xml>
请问有传参错误吗？ @xu-li

**Comment by xu-li** [comment]
@BBPen 你的sign重复用了？sign要生成两次，第一次是调用unified api之前，第二次是对有prepayid的map。你可以看我的[demo](https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/server/payment_demo.php)。

**Comment by BBPen** [comment]
问题解决了 @xu-li

**Comment by BBPen** [comment]
cordova run android --release --device的时候，手机上弹出包解析错误。
控制台：Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
ant文件内容：
key.store=/Users/chenpl/papadianyingyuan.keystore
key.alias=papadianyingyuan
key.store.password=zichuangdepapa
key.alias.password=zichuangdepapa
 @xu-li 请帮忙看下是签名错了吗？

**Comment by xu-li** [comment]
@BBPen 不知道，你可以google一下，比如[这个结果](http://stackoverflow.com/questions/2914105/android-what-is-install-parse-failed-no-certificates-error)。
