### ISSUE TITLE
ios ad-hoc版本报错

### ISSUE THREAD

**Issue by JackyWolf008** [xu-li/cordova-plugin-wechat#284]
我看到你的ios sdk换了，重新实装到项目中，ios报错
“scope参数错误或没有scope权限”
另外第一次分享成功，但是之后分享就报上面的错误，即使重启app

后来我看了下Wechat.auth(scope, state, function (response)，这个如果第一次认证完毕，是不是有session或token的，再次认证就提示上面的信息停留在微信页面，而且也无法返回js画面。

如果用户点击选择分享，这一步认证是不是必须的？如果是必须的，那重复认证的话，现在该怎么处理？

**Comment by xu-li** [comment]
1. 分享不需要auth。
2. auth的回调函数里面的response，有对应的token。
3. 你可以把第二步的token，换成access token，然后记下来。
