### ISSUE TITLE
调用微信支付接口后在微信中弹出“支付验证签名失败”

### ISSUE THREAD

**Issue by OldYoung** [xu-li/cordova-plugin-wechat#285]
使用另一个微信支付
https://github.com/ijry/cordova-plugin-wxpay.git
支付可以正常完成

但是同样的参数在这个sdk里面缺返回支付验证签名失败的错误提示，调试后看到所有发送的信息也都是一样的，唯一不同的是这个是1.7.4的版本，https://github.com/ijry/cordova-plugin-wxpay.git 用的是1.5版本
    PayReq *req = [[PayReq alloc] init];
    req.partnerId = [params objectForKey:requiredParams[0]];
    req.prepayId = [params objectForKey:requiredParams[1]];
    req.timeStamp = [[params objectForKey:requiredParams[2]] intValue];
    req.nonceStr = [params objectForKey:requiredParams[3]];
    req.package = @"Sign=WXPay";
    req.sign = [params objectForKey:requiredParams[4]];
    NSLog(@"\nappid=%@\npartid=%@\nprepayid=%@\nnoncestr=%@\ntimestamp=%ld\npackage=%@\nsign=%@",appid,req.partnerId,req.prepayId,req.nonceStr,(long)req.timeStamp,req.package,req.sign );
    if ([WXApi sendReq:req])

**Comment by xu-li** [comment]
是不是用的同一个APP_ID？签名失败就是签名失败，跟传的参数一不一样没啥关系。
