### ISSUE TITLE
插件在ionic2+NG2下无法使用

### ISSUE THREAD

**Issue by Asher-Wall** [xu-li/cordova-plugin-wechat#286]
你好，我按步骤安装wechat插件时报错了：
fetching plugin  "cordova-plugin-wechat" via npm
Installing "cordova-plugin-wechat" for android
Failed to install "cordova-plugin-wechat":CordovaError:Failed to find "ANDROID_HOME" environment variable.Try setting setting it manually.
.......
但是在plugins下面已经存在cordova-plugin-wechat这个插件包
然后ionic serve 启动app报错，APP空白，提示GET http://192.168.x.xxx:8100/build/main.css 
(index):69 GET http://192.168.x.xxx:8100/build/main.js 报错
请问这是怎么回事，求指点

**Comment by xu-li** [comment]
没下载android的sdk。跟插件没关系。

**Comment by Asher-Wall** [comment]
大牛，感谢你的回复，我配置好了JDK和安卓SDK的：
命令行执行adb是的信息：
Android Debug Bridge version 1.0.36
Revision 84e3321d5b3-android

JDK提示信息：
java version "1.8.0_111"
请指点下，本人是混合app开发（ionic2+angular2），要用到微信分享的功能，没接触过安卓的开发，看到大牛的插件的，结果遇到问题的

**Comment by xu-li** [comment]
网上搜一下吧。基本就是设置一个环境变量。

**Comment by Asher-Wall** [comment]
好的，多谢，我在看看环境变量的配置，之前的配置就是按照网上来配置的呢

**Comment by Asher-Wall** [comment]
大牛我还是调不出来，可以加个联系方式指导下吗？我QQ419604658

**Comment by xu-li** [comment]
http://spring.io/guides/gs/android/

**Comment by Asher-Wall** [comment]
收到，一样的环境变量配置，唉，这种问题不科学啊~。~，懵了，不知咋办了

**Comment by Asher-Wall** [comment]
@xu-li 你好，我的导入语法没问题吧，启动ionic serve时提示找不到插件包，ts文件
import { Component } from '@angular/core';

import { NavController ,App } from 'ionic-angular';

import { wechat} from 'cordova-plugin-wechat';

@Component({
  selector: 'page-share',
  templateUrl: 'share.html'
})


export class SharePage {
  constructor(public navCtrl: NavController,private app:App) {

  }
  immediatelyShare(){
    console.log("555555555555");
    wechat.isInstalled(function (installed) {
      alert("Wechat installed: " + (installed ? "Yes" : "No"));
    }, function (reason) {
      alert("Failed: " + reason);
    });
  }
}

**Comment by Asher-Wall** [comment]
![qq 20161118095703](https://cloud.githubusercontent.com/assets/18204892/20424984/7572205e-adb3-11e6-9f14-043b1af0a730.png)

**Comment by Asher-Wall** [comment]
这是签名时的提示
![qq 20161118201743](https://cloud.githubusercontent.com/assets/18204892/20429907/56f55a6a-adcc-11e6-9cb2-b5bd7364f296.jpg)
![qq 20161118201743](https://cloud.githubusercontent.com/assets/18204892/20429961/aae44db6-adcc-11e6-949c-ec6291e7bad2.jpg)

这种导入方式正确吗？
import { Wechat} from  'cordova-plugin-wechat';

**Comment by Asher-Wall** [comment]
这是编译时的错误提示
![qq 20161118201743](https://cloud.githubusercontent.com/assets/18204892/20430090/5172ff2e-adcd-11e6-8881-0ce60b7c602b.jpg)
![qq 20161118202142](https://cloud.githubusercontent.com/assets/18204892/20430091/519b2102-adcd-11e6-966e-e70e1552786f.png)

请问这种导入方式正确吗？
import { Wechat} from 'cordova-plugin-wechat';
研究一整天没实现~.~

**Comment by xu-li** [comment]
没用过es6, typescript。

**Comment by Asher-Wall** [comment]
哦，明白了

**Comment by Asher-Wall** [comment]
我这儿也用的是IONIC的，调用这个插件无效的
