### ISSUE TITLE
分享图片时的对象格式是什么？

### ISSUE THREAD

**Issue by kongkang** [xu-li/cordova-plugin-wechat#289]
查了文档，好像都没有诶

网页是这样：
`        media: {
            type: Wechat.Type.WEBPAGE,
            webpageUrl: "http://tech.qq.com/zt2012/tmtdecode/252.htm"
        }`

图片呢？
`media: "YOUR_MEDIA_OBJECT_HERE"`

这到底是什么格式？

**Comment by kongkang** [comment]
忘记跪谢作者了，

Orz，先磕头……

然后求回复。

**Comment by xu-li** [comment]
https://github.com/xu-li/cordova-plugin-wechat-example/blob/master/ionic/www/js/share.js

**Comment by kongkang** [comment]
对不起，我是个智障……
感谢作者耐心解释……
