### ISSUE TITLE
小米微信无法分享

### ISSUE THREAD

**Issue by YunaiV** [xu-li/cordova-plugin-wechat#291]
感谢作者提供该插件。

iOS接入该插件，朋友、朋友圈可以分享

接入android后，报
`
I20161204-22:00:09.568(8)? E/chromium(31025): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20161204-22:00:09.582(8) (android:http://localhost:12880/app/app.js:26954) [object Object]
I20161204-22:00:16.224(8)? I/MeteorWebApp(31025): Serving asset bundle with version: 3de2f8096c853395b9434d78b25ecd0917b861d2
I20161204-22:00:16.302(8)? E/chromium(31025): [ERROR:runtime_javascript_dialog_manager.cc(65)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::CancelActiveAndPendingDialogs(content::WebContents*)
`
屏幕显示：跳出一个白屏，然后“请稍后”，后面不显示。

系统信息：
红米2S 4.4.4

**Comment by ludaima** [comment]
现在把应用包名改过来了。（原来是错的）

现在报：I20161205-00:12:58.481(8)? E/chromium(15489): [ERROR:layer_tree_host_impl.cc(2206)] Forcing zero-copy tile initialization as worker context is missing
