### ISSUE TITLE
微信授权画面无法跳转

### ISSUE THREAD

**Issue by Mirs-yu** [xu-li/cordova-plugin-wechat#294]
在微信未登陆的情况下，微信画面能够正常跳转出来（显示为微信登陆画面），
但一旦登陆成功，微信的授权画面就无法跳转出来了。

请问有哪些可能会造成这个问题？

**Comment by wilhantian** [comment]
很多应用都有这个问题，并非插件导致

**Comment by din1030** [comment]
一樣的問題，還沒找到解法....

**Comment by dhunter221** [comment]
同样遇到这样的问题。请问楼上，怎么设定应用签名和包名？
