### ISSUE TITLE
when i archive to the appstore , i get an error message

### ISSUE THREAD

**Issue by xroom** [xu-li/cordova-plugin-wechat#30]
ERROR ITMS-90158:"The following URL schemes found in your app are not in the correct format:[YOUR_WECHAT_APP_ID]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only.

i had add the <preference name="wechatappid" value="wxf693d8dxxxxxxx" /> in config.xml

and when i use the device to test wechat share, it's ok.

**Comment by xroom** [comment]
i had soloved it.
i edit the plist file, in the URL TYPE find wechat ,replace [YOUR_WECHAT_APP_ID] to my appid.

**Comment by xu-li** [comment]
That's great.

**Comment by 1791422018** [comment]
can you shot a screen to me？？

**Comment by Yatko** [comment]
Getting the same error for the Google client ID, that worked before: 

> ERROR ITMS-90158: "The following URL schemes found in your app are not in the correct format: [012345678910-kn4fsmu9sql2rtq6juun2dehji3h0pkr]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail."

- where 012345678910-kn4fsmu9sql2rtq6juun2dehji3h0pkr is the Google client ID (012345678910-kn4fsmu9sql2rtq6juun2dehji3h0pkr.apps.googleusercontent.com)
- http://apple.stackexchange.com/questions/254405/error-itms-90158-url-schemes-need-to-begin-with-an-alphabetic-character-googl
