### ISSUE TITLE
微信不能直接唤出，非得下拉一次通知栏

### ISSUE THREAD

**Issue by lvdou** [xu-li/cordova-plugin-wechat#300]
升级到xcode8后，在ios10出现一个问题：比如分享朋友圈，微信不能直接唤出，非得下拉一次通知栏，才能唤出微信。感觉是哪里堵塞了，不知你这边有没有碰到过这种情况？

**Comment by januslo** [comment]
真机一直跟住版本上，没有遇到过

发自我的 iPhone

**Comment by whlhl2010** [comment]
我也碰到这个，有解决吗？

**Comment by whlhl2010** [comment]
@xu-li @lvdou 有解决这个问提？

**Comment by daileimail** [comment]
同样，有没有解决方案。。想哭难受

**Comment by andymazhuo** [comment]
我也有同样的问题...谁能提供一下帮助

**Comment by whlhl2010** [comment]
@andymazhuo @daileimail ,我的这个问题已经解决，原因是在html中<meta http-equiv="Content-Security-Policy" content="default-src *; frame-src *; style-src * 'self' 'unsafe-inline' 'unsafe-eval'; 
这句造成的，供大家参考！！！

**Comment by andymazhuo** [comment]
多谢多谢 @whlhl2010  真的是那句...原来如security policy的事情！

**Comment by lvdou** [comment]
多谢多谢，我也试试
