### ISSUE TITLE
微信支付弹出“普通错误”是什么原因造成的？

### ISSUE THREAD

**Issue by andyzhao85** [xu-li/cordova-plugin-wechat#301]
微信支付弹出“普通错误”是什么原因造成的？

**Comment by xu-li** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%E6%94%AF%E4%BB%98%20%E6%99%AE%E9%80%9A%E9%94%99%E8%AF%AF%20
