### ISSUE TITLE
弱弱的问一句：如何获取微信appID?

### ISSUE THREAD

**Issue by JianGuo222** [xu-li/cordova-plugin-wechat#304]
目前我的app还在开发初期，正在添加登陆功能，请问如何可以获取微信appID?

我试过在微信开放平台上创建新的移动应用，但是貌似需要填写我的app在app store和google play的链接。但是我的app还没开发完成啊！

微信开放平台没有沙盒么？开发阶段应该在哪里获取appID呢？

**Comment by xu-li** [comment]
创建的时候就会给你，自己看一下你的微信平台上的信息。
