### ISSUE TITLE
android 分享报 json错误

### ISSUE THREAD

**Issue by chiaochiao** [xu-li/cordova-plugin-wechat#308]
代码如下 Wechat.share({
                        message: {
                            title: "我的优惠码是" + code[0].code + "，快来下载app享受折扣吧～",
                            thumb: "http://xfinger-wisdom.oss-cn-shenzhen.aliyuncs.com/icon-108x108.png",
                            media: {
                                type: Wechat.Type.WEBPAGE,
                                webpageUrl: "http://app.xfinger.me:3000/weixinshare.html?codeId=" + code[0].code
                                //webpageUrl: "http://app.xfinger.me:3000"
                            }
                        },
                        scene: Wechat.Scene.TIMELINE   // share to Timeline
                    }, function () {
                        alert("分享成功");
                    }, function (reason) {
                        console.log("--err--",reason);
                    });

**Comment by xu-li** [comment]
加个description试试，比如:
`
{
    title: "我的优惠码是" + code[0].code + "，快来下载app享受折扣吧～",
    description: '',
    ...
}
`

**Comment by chiaochiao** [comment]
我加了，现在可以调用，但是就会闪退 报 未知错误了

**Comment by xu-li** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%E6%9C%AA%E7%9F%A5%E9%94%99%E8%AF%AF%20android
