### ISSUE TITLE
Debug and Development Mode 

### ISSUE THREAD

**Issue by deeeed** [xu-li/cordova-plugin-wechat#310]
Hi,

First of all, thanks for the plugin :)
I am facing an issue with my app, **how can I test the package during development?** 
It seems that I can only try the API with a signed apk validated from weixin. I do have an approved appid but it seems very unproductive **to release an app, test, make a change, release an app, etc...**
Is there a way I could directly test the weixin api within a development version of my app?
My written Chinese is very limited so I am not sure how to search for this info in Chinese.

Thanks

**Comment by januslo** [comment]
It is nothing to do with this plugin, you may to ask Weixin about this officially . Go to Weixin and check the documents. 

发自我的 iPhone

**Comment by deeeed** [comment]
True, sorry about the confusiong.
And to asnwer myself, I just add to create debug-signing.properties file in platforms/android/
