### ISSUE TITLE
ios分享完，打开链接 弹出{"errorMsg"："config:ok"} 怎么解决，在线等，急！！！

### ISSUE THREAD

**Issue by MyNameIsInherit** [xu-li/cordova-plugin-wechat#314]

**Comment by MyNameIsInherit** [comment]
微信官网文档说是开启了debug模式
wx.config({
    debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
    appId: '', // 必填，公众号的唯一标识
    timestamp: , // 必填，生成签名的时间戳
    nonceStr: '', // 必填，生成签名的随机串
    signature: '',// 必填，签名，见附录1
    jsApiList: [] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
});
插件中中哪里可以设置debug为false??

**Comment by xu-li** [comment]
这不是插件的问题，是你页面的问题。

**Comment by MyNameIsInherit** [comment]
@xu-li  主要是什么问题？

**Comment by MyNameIsInherit** [comment]
@xu-li  URL传参的问题吗？

**Comment by xu-li** [comment]
帮你搜索了一下: http://bbs.csdn.net/topics/390981338。

你自己搜一下吧。

**Comment by MyNameIsInherit** [comment]
var scope = "snsapi_userinfo",
state = "_" + (+new Date());
Wechat.auth(scope, state, function (response) {
// you may use response.code to get the access token.
alert(JSON.stringify(response));
}, function (reason) {
alert("Failed: " + reason);
});

这个认证必须要加？还有scope传的是什么？不太明白

在 2017-03-02 11:57:44，"lixu" <notifications@github.com> 写道：


Closed #314.
