### ISSUE TITLE
Wechat.auth 拉起微信授权后，没返回 response

### ISSUE THREAD

**Issue by leoyfm** [xu-li/cordova-plugin-wechat#316]
之前微信授权成功过，能接受到授权后返回的code， 现在不知道怎么回事，接受不到返回的response。

代码如下
```javascript
var scope = "snsapi_userinfo",
              state = "_" + (+new Date());
          Wechat.auth(scope, state, function (response) {
              // you may use response.code to get the access token.
              console.log('SocailService#wechatAuth response', response);
              console.log('SocailService#wechatAuth response', JSON.stringify(response) );
              alert(JSON.stringify(response));
          }, function (reason) {
            alert(JSON.stringify(reason));

            console.log('SocailService#wechatAuth failed', JSON.stringify(reason));
          });
```
授权成功后，返回app，但是两个回调函数都没有运行。
这个怎么检查？不知道出什么问题了，测试用的是ios 平台

**Comment by lawliet467** [comment]
我也是有这个问题,@leoyfm 有没有解决?

**Comment by leoyfm** [comment]
没有,我发现只有第一授权成功以后才有回调,之后就没有了.这样不和逻辑啊,如果是要存accesstoken的话,也得获取到授权成功后返回的code才能换取accesstoken啊.第二次授权成功后,不反悔code,我也得不到openid,也就找不到之前存的accesstoken.所以不知道怎么解决.我现在用的是测试号,等换正式号的时候试试

**Comment by lawliet467** [comment]
我是一直没有任何回调,偶尔点击速度快,会调用错误的回调说发送请求错误.但正确的回调一直没有

**Comment by leoyfm** [comment]
我专门看了ios的代码,按文档说的,请求发出去后,都应该又回调,但是,我打断点看了,没有触发,所以我估计可能是微信sdk的问题.我打算自己动手更新一下sdk试试

**Comment by lawliet467** [comment]
我已经解决了,原来是项目中已经有另外一个支付插件,然后回调方法跳到那边去了,所以没有正确跳到回调上.然后我把它判断一下,强制跳到对的地方去了

**Comment by krunalm1992** [comment]
I'm facing same problem in android.. Did anyone have solved this problem?

**Comment by leoyfm** [comment]
@xu-li 你是从哪发现的回调调错了,我也检查一下,我支付用的是ping++,估计也是这个问题

**Comment by lawliet467** [comment]
我用xcode打断点,发现没有走微信插件的回调,反而去了支付那边的

**Comment by leoyfm** [comment]
ok,我试试,估计也是走支付了

**Comment by BrotherPeng** [comment]
@lawliet467 请问能贴下代码吗。怎么解决的

**Comment by zjhiphop** [comment]
安卓SDK遇到同样的问题， 求解

**Comment by xandeer** [comment]
ios 遇到同样问题，后来发现在 AppDelegate 中已经实现了
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
```

所以插件捕获不到通知。解决方案类似如下：

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
    CDVWechat* wechat = [self.viewController getCommandInstance:@"Wechat"];
    
    if ([url.scheme isEqualToString:wechat.appId]) {
        return [WXApi handleOpenURL:url delegate:wechat];
    } 
}
```

**Comment by liuxzzz** [comment]
Property 'appId' not found on object of type 'CDVWechat *'

**Comment by liuxzzz** [comment]
> ios 遇到同样问题，后来发现在 AppDelegate 中已经实现了
> 
> ```
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
> ```
> 
> 所以插件捕获不到通知。解决方案类似如下：
> 
> ```
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
> {
>     CDVWechat* wechat = [self.viewController getCommandInstance:@"Wechat"];
>     
>     if ([url.scheme isEqualToString:wechat.appId]) {
>         return [WXApi handleOpenURL:url delegate:wechat];
>     } 
> }
> ```

Property 'appId' not found on object of type 'CDVWechat *'
报了这个错误，请教下该如何解决，方便的话可以贴下代码
