### ISSUE TITLE
关于Android libammsdk版本

### ISSUE THREAD

**Issue by TE-ShiYunni** [xu-li/cordova-plugin-wechat#325]
你好！xu-li

首先非常感谢你提供的这个插件，为非常多的人提供了交流分享的平台。
现在我参与的项目需要使用微信的cordova插件，于是我找到了这里。

我看到你的CHANGELOG.md中Android libammsdk的版本是3.1.1。
而在微信开放平台的[Android资源下载](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN)页面，通过[Android开发工具包](https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Android_SDK_5.0.2.rar)下载的SDK是5.0.2。

两个版本相差甚远，请问该插件可以升级最新SDK吗？
如果不行还请告诉我理由。

谢谢！

**Comment by xu-li** [comment]
应该是可以升级到最新SDK的，最近比较忙，没时间打理而已。

多谢你的关注。

**Comment by TE-ShiYunni** [comment]
明白了。
谢谢你抽空回答我的问题！
