### ISSUE TITLE
微信登录没有回调。

### ISSUE THREAD

**Issue by jimmyYSY** [xu-li/cordova-plugin-wechat#328]
使用插件进行微信登录，没有回调返回数据。
其中 微信登录需要的参数都有了  code   时间戳  都是有的，但是没有返回的回调怎么解？？？

**Comment by tallprince** [comment]
How can I use the [gensignature tool](https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Gen_Signature_Android1f09c7.apk)?

**Comment by jimmyYSY** [comment]
@tallprince what's this???

**Comment by liangqiangkun** [comment]
@tallprince   你直接下载这个签名工具app，然后装到手机上，然后打一个安卓的apk，在签名工具app中输入你的应用包名，就会得到一串字母，然后将它填到微信开发者后台就行了。
If you don't understand, I 'll explain it in English, but  in my opinion,  you  must be Chinese.

**Comment by tallprince** [comment]
Thanks for your reply.
I registered my app and Weixin approved it after 5 days, but they asked me to upload developer certification again When I wanted an email permission. So I skipped this part.
