### ISSUE TITLE
Wechat.auth doesn't work

### ISSUE THREAD

**Issue by tallprince** [xu-li/cordova-plugin-wechat#329]
I'm implementing WeChat authentication on Ionic framework.
But I get no response after calling WeChat.auth function.
Here are my codes:
`Wechat.isInstalled(function(installed) {

            if (installed === 'false' || installed === false || installed === 0 || installed === '0') {
                errorPopup.toast('Please install we chat app');
                return false;
            }

            var scope = "snsapi_userinfo",
                state = "_" + (+new Date());

            Wechat.auth(scope, state, function(response) {
                errorPopup.toast('success-123');                
            }, function(error) {
                errorPopup.toast('eror-2' + error);
            });
        }, function(reason) {
            errorPopup.toast('eror-1' + reason);
        });`

I can't see any messages after running above codes.
Please teach me if you have any idea.

**Comment by tallprince** [comment]
I tried to run the example code, but it also didn't work.

**Comment by ZAZA316** [comment]
Hello.
I am a WeChat professional.
I can help you anytime and I trust you with your photo.
My ID is "ZAZA" or "mch316".
Anytime you can contact me.
My email address: zaza316614@hotmail.com

**Comment by leoiqr** [comment]
me too
