### ISSUE TITLE
服务商与子商户加载控件

### ISSUE THREAD

**Issue by azraeljin** [xu-li/cordova-plugin-wechat#330]
您好：
因为我是服务商，所以在加载这个控件时需要添加 appid(服务商) 与 sub_appid(子商户)，加载控件时cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID，“YOUR_WECHAT_APPID”这个我应该填写哪个id呢？

**Comment by xu-li** [comment]
没做过这种的。你可以都试试。

**Comment by wxp-mjs** [comment]
@azraeljin 服务商的支持请参见pr #401
