### ISSUE TITLE
ios微信授权回调没有执行

### ISSUE THREAD

**Issue by ilovetochangetheworld** [xu-li/cordova-plugin-wechat#331]
debug后 sendAuthRequest 可以正常执行，
![image](https://cloud.githubusercontent.com/assets/13465460/25219105/d3f9ab02-25df-11e7-830a-fde041a9c5a1.png)
点击确认登录按钮后返回到app，没有执行到回调里面。
debug显示 没有执行到(void)handleOpenURL:(NSNotification *)notification。
版本是ios 10.3.1 使用的是ionic3.0，回退到ionic2.3后授权是正常的，升级到3.0后授权没有回调

**Comment by liangqiangkun** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by hiyali** [comment]
同问

**Comment by TomYiCL** [comment]
同问，qq登录和微信登录好像是同样的问题，onRes、onResq方法未调用

**Comment by bashlin** [comment]
[https://github.com/xu-li/cordova-plugin-wechat/issues/316](url)

**Comment by carson33459** [comment]
@TomYiCL 你的问题解决了吗？怎么解决的

**Comment by TomYiCL** [comment]
解决了，自己改的代码 在AppDelegate.m加的代码，在微信CDVWechat.m 通过通知调的onResp 方法@carson33459 
#pragma mark--解决微信、QQ登录问题

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    
//    NSLog(@"%@",url);
//    NSLog(@"%@",sourceApplication);
    //    com.tencent.mqq
    //    com.tencent.xin
    if ([sourceApplication isEqualToString:@"com.tencent.xin"]) {
              return [WXApi handleOpenURL:url delegate:self];
    }else if ([sourceApplication isEqualToString:@"com.tencent.mqq"]){
        return [TencentOAuth HandleOpenURL:url];
    }
    return false;
}

- (void)onResp:(BaseResp *)resp
{
    [[NSNotificationCenter defaultCenter] postNotificationName:@"WechatBackToApp" object:resp];
    
}

**Comment by carson33459** [comment]
@TomYiCL 谢谢。我发现这么改没有用，但是找到了思路。查了一下，主要是ios的处理回调冲突
我的主要修改 AppDelegate.m

#import "CDVWechat.h"
#import "YCQQ.h"

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
    CDVWechat* wechat = [self.viewController getCommandInstance:@"Wechat"];
    YCQQ* ycqq = [self.viewController getCommandInstance:@"YCQQ"];
    
    NSString *qqScheme = [NSString stringWithFormat:@"tencent%@", ycqq.qq_app_id];

    if ([url.scheme isEqualToString: wechat.wechatAppId]) {
        return [WXApi handleOpenURL:url delegate:wechat];
    }else if([url.scheme isEqualToString: qqScheme]){
        return [TencentOAuth HandleOpenURL:url];
    } else {
        
    }
}
