### ISSUE TITLE
微信分享 未成功调出微信, 提示: Failed:未知错误

### ISSUE THREAD

**Issue by zhengfugen** [xu-li/cordova-plugin-wechat#336]
微信分享 未成功调出微信, 提示: Failed:未知错误

已根据前面的Issue确认应用签名, 微信认证APPID正确.
            Wechat.share({
                text: $scope.shareText,
                scene: Wechat.Scene.SESSION   // share to 
            }, function () {
                alert("Success");
            }, function (reason) {
                alert("Failed: " + reason);
            });

已重新移除插件再加载仍是相同错误.

**Comment by dingcumt** [comment]
你好，我也遇到了同样的问题，请问你解决了吗？是如何解决的？

**Comment by zhengfugen** [comment]
暂未解决

**Comment by Skye27yang** [comment]
Wechat.share({
        message: {
          title:$rootScope.share_title,
          description: $rootScope.share_description,
          thumb: $rootScope.share_img_url,
          media: {
            type: Wechat.Type.WEBPAGE,
            webpageUrl: $rootScope.share_page_url
          }
        },
        scene: Wechat.Scene.TIMELINE
      }, function () {
        alert('success')
      }, function (reason) {
        alert(reason)
      });
我也是，不知道哪里错了，会调一下系统的微信，闪一下，然后就是“未知错误”，你们解决了吗？

**Comment by kinglionsoft** [comment]
+1, android

**Comment by Skye27yang** [comment]
@zhengfugen 你好，你是怎么确认应用签名, 微信认证APPID正确的？

**Comment by rollo-zhou** [comment]
Android 不仅需要审核通过, 还需要签名吻合, 所以得要 release 的 keystore 来签名.  Android 搞不定的可以看看 Android 微信 SDK 签名问题.https://github.com/vilic/cordova-plugin-wechat/wiki/Android-%E5%BE%AE%E4%BF%A1-SDK-%E7%AD%BE%E5%90%8D%E9%97%AE%E9%A2%98

**Comment by xudihui** [comment]
+1, android，debug版本可以正常分享，release+sigin版本无法分享

**Comment by Skye27yang** [comment]
@xudihui 这两个版本不能同时成功的，你的情况可能是微信官网上面认证时候填写的是debug版本的md5签名，登录改成正式的keystore签名就行了

**Comment by xudihui** [comment]
@Skye27yang 您好，我可能对debug不是很理解，我只要执行cordova run android 然后再真机上调试，这时候是可以分享的，我不知道这个属不属于debug版本。但是我执行cordova build android 生成的包或者cordova build android --release 再签名的包就不能分享了。

**Comment by xudihui** [comment]
@Skye27yang 感谢大神，我已经成功解决了，我之前在公众号上填的是正确的md5签名，但是后来更新了证书但是没去微信开发平台更新，今天重新申请的应用通过后，我remove插件重新安装后就能成功分享了，非常感谢。@所有人，大家遇到这个错误的时候，最好是重新去微信开放平台申请一个app应用，填写正确的应用签名。
查看应用签名指令：
keytool -list -v -keystore [you key name].keystore
里面输出md5的后面那串，然后把冒号去掉就是应用签名了。

best wishs ！
