### ISSUE TITLE
APP唤起微信闪动一下，无法唤起

### ISSUE THREAD

**Issue by HarlanGitHub** [xu-li/cordova-plugin-wechat#337]
之前在cordova 低版本上的上的时候所有功能都是正常的，今天升级到cordova 7.0.1中发现该插件调微信出现闪一下，然后恢复原页，微信没有被唤醒。已经重新安装了两次该插件.都是相同的结果。
我当前的系统信息:
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10

**Comment by HarlanGitHub** [comment]
该问题，我刚已经找到问题，解决了，android下cordova 高版本没有任何问题

**Comment by iyibo** [comment]
@HarlanGitHub   请问你是怎么解决的，我也碰到了类似的问题
