### ISSUE TITLE
macOS环境下编译出来的android apk 微信登录总是 未知错误

### ISSUE THREAD

**Issue by mchenx** [xu-li/cordova-plugin-wechat#339]
如题……
同样的项目，在windows下编译出来的android apk 确是好的
一直都是未知错误，没什么具体的信息

**Comment by liangqiangkun** [comment]
哥们儿 应该是你的签名出问题了。 你看看你微信后台配置的那个签名 与你打包时候用的签名是否是一致的。

**Comment by Skye27yang** [comment]
@liangqiangkun 怎样确切的验证微信开发申请时的签名和打包时候的签名一致？

**Comment by flyingalex** [comment]
@Skye27yang 可以用 `https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=79426701880e79ecc37e5824eb4f32049201c043&lang=zh_CN` 最后那个工具

**Comment by mchenx** [comment]
更正一下，windows环境中没有问题的是debug，用了debug默认签名的。
如果使用release然后用自己的keystore签名，也会出现这个问题

**Comment by mchenx** [comment]
@Skye27yang 打包是用我自己生成的keystore来签名的，没有用微信后台配置的那串字符串
