### ISSUE TITLE
How to - Go out to Wechat Store, make purchase, then rerun to App

### ISSUE THREAD

**Issue by acylum** [xu-li/cordova-plugin-wechat#34]
In my Cordova app, I want to allow someone to buy a vote (not virtual item) - this Vote is on our weChat Store.  After they buy the vote, then return to the Cordova app.  Is there a way to do this?

Currently, I use  window.open(we chat store url) to take the user to the store, but after they purchase, i can't bring them back to the app.   Is there a way to take the user to the Wechat app, make the purchase at the we chat store, then return to the app?

**Comment by xu-li** [comment]
@acylum See [latest develop branch](https://github.com/xu-li/cordova-plugin-wechat/tree/develop).
