### ISSUE TITLE
android 调起微信后，授权成功，回跳回app时，app会重新启动

### ISSUE THREAD

**Issue by flyingalex** [xu-li/cordova-plugin-wechat#340]
如题，不知道是否有人遇到过这种情况？还望分享一二

**Comment by flyingalex** [comment]
remove platform, then reinstall it, okay now

**Comment by flyingalex** [comment]
现在即使删除也不能解决这个问题，感觉时好时坏，疼～

**Comment by 1981cxp** [comment]
感觉是跳转到第1个页面，然后再跳回来，会闪一下

**Comment by clyquan** [comment]
同问，分享功能也是这样。

**Comment by iamnotstone** [comment]
这是cordova版本太高，不兼容这个插件所导致的。解决方案是修改$your_project/plugins/cordova-plugin-wechat/scripts/android-install.js中的
`var targetDir  = path.join(projectRoot, "platforms", "android", "src", packageName.replace(/\./g, path.sep), "wxapi");`

修改为
`var targetDir  = path.join(projectRoot, "platforms", "android", "app","src","main","java", packageName.replace(/\./g, path.sep), "wxapi");`

修改后，重新装一下平台
cordova platform remove android
cordova platform add android

这样同样能达到 @clyquan 所提到的修改效果，就是让插件把那三个类复制到正确的位置。

**Comment by cyy199298** [comment]
我根据var targetDir = path.join(projectRoot, "platforms", "android", "app","src","main","java", packageName.replace(/\./g, path.sep), "wxapi");这个方案重新装了android 还是支付成功之后会重启app，我的微信支付的插件版本是2.1.3的，android的版本是6.3.0的，找了好多天的资料，无法解决，请求能解答一下，谢谢
