### ISSUE TITLE
android分享缩略图问题

### ISSUE THREAD

**Issue by Dawn2Yuan** [xu-li/cordova-plugin-wechat#346]
同样代码 同样图片
①在IOS上分享是没有问题的
②在ANDROID上分享就报 ## **发送请求失败**

如果换成小的缩略图就可以分享

想知道一下  android上分享对缩略图大小有要求吗？

**Comment by xu-li** [comment]
有的，程序会自动裁剪图片到300x300，但是还是有可能图片文件大小超标。
