### ISSUE TITLE
Could not find any matches for com.tencent.mm.opensdk:wechat-sdk-android-with-mta:+

### ISSUE THREAD

**Issue by flyingalex** [xu-li/cordova-plugin-wechat#347]
奇葩问题
```
Error: /home/hulin/Sites/ladcohome/src-cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any matches for com.tencent.mm.opensdk:wechat-sdk-android-with-mta:+ as no versions of com.tencent.mm.opensdk:wechat-sdk-android-with-mta are available.
     Required by:
         project :
```
cordova 7.0.1
node 6.9.5
npm 3.10.10

**Comment by Dawn2Yuan** [comment]
你是啥时候使用这个插件时 出现的这个问题

**Comment by flyingalex** [comment]
@Dawn2Yuan 　今天，有撒想法吗？

**Comment by Dawn2Yuan** [comment]
我明天用这个插件都还好着 
今天打包的时候也有问题了   
好像是在下载的相关sdk的时候  访问不到资源引起的

**Comment by flyingalex** [comment]
嗯，就是依赖下载不了，蛋疼．．

**Comment by Dawn2Yuan** [comment]
@flyingalex @xu-li 
得让作者出来  解决了

**Comment by flyingalex** [comment]
@xu-li ios　麻烦看一下， ios没有问题，android有问题．谢谢

**Comment by zjw1918** [comment]
+1
今早打包还行。吃了个午饭就不行了，strange

**Comment by Dawn2Yuan** [comment]
@zjw1918 我早上打包一直就没好

**Comment by XueChenChen** [comment]
+1

**Comment by zjw1918** [comment]
我昨晚测试空项目就出现这问题了。 @Dawn2Yuan

**Comment by xiyezifeng** [comment]
下午就不行了，依赖没了？

**Comment by flyhuang** [comment]
同样的问题, 依赖找不到了

**Comment by Dawn2Yuan** [comment]
不知道   是腾讯官方的问题  
还是这个插件的问题
理论上来说  依赖下载不下来   应该是腾讯官方的问题


使用微信分享、登录、收藏、支付等功能需要的库以及文件
Android Studio环境下：已改用gradle形式，发布到jcenter（ http://jcenter.bintray.com/），请开发者使用gradle来编译、更新微信SDK。
在build.gradle文件中，添加如下依赖即可：
dependencies {
   compile 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:+'
}
或
dependencies {
   compile 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+'
}
（其中，前者包含统计功能）
eclipse环境下：点击下载 Android开发工具包
## **注意：因为微信SDK从4.0.2版本开始已改用gradle形式，后续Android开发工具包将不再更新，请开发者尽快改用gradle方式编译、更新微信SDK。**

**Comment by flyhuang** [comment]
先hack一个版本..把jar包手动加进去了.

**Comment by zjw1918** [comment]
不是插件的问题。原生也一样报错。

**Comment by flyingalex** [comment]
腾讯今天有更新那个包．估计是那里的问题，切到旧版本就可以了，一起做事的同事发现的．
```

**Comment by zjw1918** [comment]
嗯，或者注释掉此插件里的
dependencies {
    // compile 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:+'
}
重新添加android平台；
下载开放平台里的jia包，丢到android目录下的libs里
https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Android_SDK_5.0.6.rar

再编译即可。

**Comment by cooleone** [comment]
将gradle的源切换到阿里的镜像源上就可以了

**Comment by alzee** [comment]
今天也遇到这个问题了，把 + 替换成 最新的版本号(5.4.0)就 OK 了。
```
dependencies {
    compile 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:5.4.0'
}
```
