### ISSUE TITLE
由于不支持的分享类型 无法分享到微信

### ISSUE THREAD

**Issue by ryangsun** [xu-li/cordova-plugin-wechat#349]
这是插件过时了还是我的配置问题？

**Comment by hiyali** [comment]
同问

**Comment by hiyali** [comment]
@ryangsun 我这边是解决了，排查所有问题后，发现 config.xml 更新的 appid 不会在 xcode 编译时更新，需要在 xcode 里更新 或者 需要 cordova platform rm ios  然后在 add。
