### ISSUE TITLE
Is there a way to send a we chat store item message?  Would I use message.type.app?

### ISSUE THREAD

**Issue by acylum** [xu-li/cordova-plugin-wechat#35]
Is there a way to send a we chat store item message?  Would I use message.type.app?

![img_5426](https://cloud.githubusercontent.com/assets/1613809/8028774/d05dd4c8-0d68-11e5-8552-c5e21bca8e28.jpg)

Also, how would I be able to open a store message with the plugin?
document.querySelector('#openProductSpecificView').onclick = function () {
    wx.openProductSpecificView({
      productId: 'pDF3iY0ptap-mIIPYnsM5n8VtCR0'
    });
  };

**Comment by xu-li** [comment]
Sorry, what do you mean by _store_ and _store message_?

**Comment by acylum** [comment]
For wechat, you can setup a wechat store to sell items.   What I would like to do is for my cordova app to post a message to my moments.  When someone clicks this message on my moments, it will take them to the item in my wechat store.

Currently, I am not sure how to accomplish this.  Would I be sending a message.type.App with ext data?  Or is there another way?

Here is a picture to illustrate:  basically, I would want my cordova app to post a message to my moments.  Then someone can tap the message which would take them to my item in my we chat store.
![sample](https://cloud.githubusercontent.com/assets/1613809/8039780/e40b1f14-0dc0-11e5-841e-60d5c4d5b3d9.jpg)

**Comment by xu-li** [comment]
You may try sharing a wechat payment url. e.g. weixin://wxpay/bizpayurl?appid=...
