### ISSUE TITLE
安卓下面集成已经成功，但是付款后返回APP，会出现应用重新启动

### ISSUE THREAD

**Issue by zhanyingfeng** [xu-li/cordova-plugin-wechat#351]
安卓下面集成已经成功，但是付款后返回APP，会出现应用重新启动，请问有人知道怎么解决吗？试了好几个手机，都 一样有这个问题。

**Comment by clyquan** [comment]
https://github.com/xu-li/cordova-plugin-wechat/issues/340  
参考我的解决办法。
