### ISSUE TITLE
微信支付在windows系统打包的app支付返回app时会重启，在mac系统下打包的app不会重启。但是回调函数不执行。

### ISSUE THREAD

**Issue by hhafeng** [xu-li/cordova-plugin-wechat#352]
Wechat.sendPaymentRequest(params,function(){
          alert('支付成功');
        },function(error){
          alert('支付失败');
        })
这两个回调函数怎么样都不会执行。

**Comment by hiyali** [comment]
@hhafeng 回调函数不执行的错误，解决了？

**Comment by hhafeng** [comment]
嗯，所有问题都解决了，插件没有问题。原来在WINDOWS下面编译的APK，返回时是重启APP，后来换了MAC下打包APK，就不会了。回调函数中的会执行,ionic2下面最好是用箭头函数，不然会丢失this。

**Comment by hhafeng** [comment]
@hiyali 嗯，所有问题都解决了，插件没有问题。原来在WINDOWS下面编译的APK，返回时是重启APP，后来换了MAC下打包APK，就不会了。回调函数中的会执行,ionic2下面最好是用箭头函数，不然会丢失this。

**Comment by hiyali** [comment]
@hhafeng cordova 是什么版本？我们好几个人在 Mac 用 dev 或 prod 模式编译，都没有执行回调。
