### ISSUE TITLE
支付出现“普通错误”提示

### ISSUE THREAD

**Issue by bing086** [xu-li/cordova-plugin-wechat#353]
拉起支付的时候出现 ：普通错误
排查以下原因：包名 签名 appid都设置没问题。求解？
以下记录

`08-01 23:20:11.110 21263-21416/com.youme.app I/Cordova.Plugin.Wechat: Payment request has been sent successfully.
08-01 23:20:11.110 21263-21416/com.youme.app W/PluginManager: THREAD WARNING: exec() call to Wechat.sendPaymentRequest blocked the main thread for 110ms. Plugin should use CordovaInterface.getThreadPool().
08-01 23:20:11.404 21263-22664/com.youme.app I/MID: read mid from InternalStorage
08-01 23:20:11.421 21263-22664/com.youme.app I/MID: read mid from InternalStorage:xjgD6zAYj0472xOA1JxF6XKTI5Z5+neyBX5IvE6F2vBocUpsi+Hdgrw+HzzxT2MHTwxwyqFOUVdvECRJ+l7WNlcAz6Rq4ZnEUeKvSyf8te1w8K5BcIdkWBcz93JOQ0k7Lgg+wLWaxrtRNl09zEmKYGqqMQo=
08-01 23:20:11.551 21263-22692/com.youme.app D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-01 23:20:11.671 21263-21263/com.youme.app I/MicroMsg.SDK.WXApiImplV10: handleIntent, cmd = 5
08-01 23:20:11.672 21263-21263/com.youme.app D/Cordova.Plugin.Wechat: com.tencent.mm.opensdk.modelpay.PayResp@e460719
08-01 23:20:11.698 21263-21263/com.youme.app V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f26fbd5
08-01 23:20:11.698 21263-21263/com.youme.app V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@124fea
08-01 23:20:11.726 21263-21263/com.youme.app D/ActivityThreadInjector: clearCachedDrawables.
08-01 23:20:11.731 21263-21263/com.youme.app D/CordovaActivity: Stopped the activity.
08-01 23:20:11.740 21263-21263/com.youme.app D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 60802 : weixin pay fail:普通错误
08-01 23:20:11.741 21263-21263/com.youme.app I/chromium: [INFO:CONSOLE(60802)] "weixin pay fail:error:null", source: file:///android_asset/www/build/main.js (60802)`

**Comment by Bjkb** [comment]
刚解决
服务端签名问题

**Comment by yangguangpeng** [comment]
服务端请求https://api.mch.weixin.qq.com/pay/unifiedorder后的结果是这样：状态码是成功的，为什么我的还报普通错误呢？？
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx7a*****a6874f3c9]]></appid>
<mch_id><![CDATA[1483***5622]]></mch_id>
<nonce_str><![CDATA[NcnnKAjn6qcuTCsb]]></nonce_str>
<sign><![CDATA[09F9C**********657BE04A5AE154F]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx20171***********4150463852822]]></prepay_id>
<trade_type><![CDATA[APP]]></trade_type>
</xml>

**Comment by yangguangpeng** [comment]
@Bjkb 服务端请求https://api.mch.weixin.qq.com/pay/unifiedorder后的结果是这样：状态码是成功的，为什么我的还报普通错误呢？？

**Comment by yangguangpeng** [comment]
狗日的，竟然提供的demo是错的，还要传入"appid"和package这两个参数，害我搞了好多天。。。。。

**Comment by SirYuye** [comment]
@yangguangpeng packafe传入“Sign=WXPay”是对的吗，我也遇到你这个问题了

**Comment by SirYuye** [comment]
解决了，安卓上的keystore证书有问题，没做过安卓开发，这是个坑

**Comment by china17qin** [comment]
@SirYuye 请问下调起支付传的params到底需要哪些参数，能发一个params例子吗？安卓上面在开发环节必须要加入kerstore证书才能调用支付吗？我现在这里一直报普通错误，params参数随便写是普通错误，从后台获取也是普通错误，现在我都不清楚问题出在哪里。

**Comment by zzhua2007** [comment]
@SirYuye  我是android debug模式，其它如appid,应用签名，包名等信息都确认正确，分享也是成功的，但就是支付一直报普通错误，请问下你是怎么解决的？

**Comment by zurmokeeper** [comment]
可以参考写这个链接https://github.com/xu-li/cordova-plugin-wechat/issues/420
