### ISSUE TITLE
我用ionic build android命令打包的分享是OK的，但是ionic build android -release打包之后用keystore文件文件

### ISSUE THREAD

**Issue by Skye27yang** [xu-li/cordova-plugin-wechat#354]
我用ionic build android命令打包的分享是OK的，但是ionic build android -release打包之后用keystore签名之后的包分享不了，同样的QQ分享没问题

**Comment by xu-li** [comment]
release和debug的keystore是不一样的。https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN
