### ISSUE TITLE
ionic3下微信登陆

### ISSUE THREAD

**Issue by jerrytang67** [xu-li/cordova-plugin-wechat#357]
window.Wechat.auth("snsapi_userinfo",  function (response) {
      alert(response);
以下都不执行.
let _res = response;
console.log(_res);

只执行了alert,别的不管什么都不执行,怎么解决?
环境是是最新版ionic cli 3.7 ,cordova 7.0.1

**Comment by 18012728118** [comment]
reponse能成功登陆拿到code等

**Comment by flyingalex** [comment]
```
