### ISSUE TITLE
debug版本是成功的，但是release版本报错

### ISSUE THREAD

**Issue by baixiaoyu2997** [xu-li/cordova-plugin-wechat#358]
调用微信登录时会报错，release版本提示Failed:未知异常，但是debug版本可以使用。我用的是as，签名都是之前签好的，微信appid这些都在签名的时候弄好了。

**Comment by xudihui** [comment]
在使用分享的时候遇到类似问题，debug版本可以正常分享，release版本会跳出去一下然后直接跳回来，提示未知错误。
请问下签名是要自己签的吗？，我看到开放平台在每一个申请好的安卓app中，直接显示应用签名，请问下这个签名你是怎么使用的？

**Comment by taixiangfei2016** [comment]
@baixiaoyu2997 @xudihui 两位朋友，你们问题解决了，怎么处理的，我的问题跟你们差不多
