### ISSUE TITLE
WeChat.auth 方法没有找到

### ISSUE THREAD

**Issue by ayonge20** [xu-li/cordova-plugin-wechat#36]
通过 cordova plugin add com.wordsbaking.cordova.wechat 安装后的插件，发现没有auth() 与 isInstalled（）等方法，wechat.js中只有share方法，请问怎么样可以安装带有auth 与 isInstalled的插件。

**Comment by xu-li** [comment]
@ayonge20 com.wordsbaking.cordova.wechat 这个插件不是我做的，你可以问问他们。

如果要安装我这个微信插件，请使用```cordova plugin add https://github.com/xu-li/cordova-plugin-wechat```.

**Comment by ayonge20** [comment]
@xu-li  https://github.com/xu-li/cordova-plugin-wechat 这个插件用ionic好像安装不了，我才选择了com.wordsbaking.cordova.wechat

**Comment by ayonge20** [comment]
@xu-li 安装 https://github.com/xu-li/cordova-plugin-wechat 时会出现错误：   Fetching plugin "https://github.com/xu-li/cordova-plugin-wechat" via git clone
Error: "git" command line tool is not installed: make sure it is accessible on your PATH.

**Comment by xu-li** [comment]
你需要安装 [git command line tool](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

**Comment by ayonge20** [comment]
@xu-li  你好，这个问题已经解决了，我在 www/config.xml中已经添加了WechatAppId的值（plugin.xml也有添加），但是在用调用isInstalled的时候，报错：  Attempted to send a second callback for ID: Wechat1635618540以及 Result was: "Invalid action"
请问这个方法该如何解决

**Comment by xu-li** [comment]
你可以试试[cordova-plugin-wechat-example](https://github.com/xu-li/cordova-plugin-wechat-example), 按照那个来调用。

**Comment by ayonge20** [comment]
@xu-li  你好,我在cordova-plugin-wechat-example 这个项目中，添加android平台以及您的微信插件，模拟器没有安装微信，发现仍然报错误 CordovaPlugin: Attempted to send a second callback for ID: Wechat45529617 以及 错误CordovaPlugin: Result was: "Invalid action"。

**Comment by xu-li** [comment]
@ayonge20 我更新了新的版本，主要针对android，你可以试试。
