### ISSUE TITLE
求助，可以使用微信登录，但是微信分享提示权限错误

### ISSUE THREAD

**Issue by siwei0729** [xu-li/cordova-plugin-wechat#364]
点击分享可以正常唤起微信，但是微信提示该应用未获得分享权限。 问题是在开放平台，显示我们的移动app 是 有分享权限的。 应该也不是appId 问题因为我们的 微信登录可以正常使用。
代码是用的是demo 的代码
```
Wechat.share({
    text: "This is just a plain string",
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});
```

**Comment by jyouli** [comment]
请问解决了么？我也遇到同样问题了😭

**Comment by siwei0729** [comment]
噢，我后来微信分享就没有用这个plugin 了， 只是用这个plugin 作为微信登录。 我直接用了ionic 原生的 那个系统级别的 share plugin， 不单单是微信 可以 分享到很多个软件

**Comment by jyouli** [comment]
好的，谢谢你！看样子我还得和微信开放平台的客服死磕了，我定位到是微信生成的appid的问题！因为我把这个appid和appSecret放在一个正常可以分享的项目中也是这个无分享权限提示。

**Comment by jyouli** [comment]
跟进一下吧，和微信开放平台客服咨询了一周，最终原因是“您好，请问是否海外帐号，海外分享目前只支持网页链接。”，气炸了，老板白花了120美元，最后又得找淘宝整了个国内企业资质的微信开放平台账户😭

**Comment by DeliveLee** [comment]
@jyouli 哈哈哈哈哈哈哈哈， 哥们儿我和你的情况一模一样， 今天我刚给WeChat发了第三封邮件， 他们还没有回复我， 看到终于有人和我一样情况了， 十分感谢！如果没有你的信息，可能我们还在焦急的等待回复并且被deadline拖死， 十分感谢！ 你要是在青岛的话，我请你吃饭！哈哈！自此感谢！！！

**Comment by jyouli** [comment]
@DeliveLee   我去，我刚发一个小时，就被你看到了，我被折腾了一周多了，微信那边客服一直说我的项目有问题，气的吐血！

**Comment by DeliveLee** [comment]
@jyouli 是的！我们已经被折磨了一个月了，因为是国外公司资质认证， 从认证开始就出现各种问题，WeChat的开发者中心也并不提供除了邮件之外的其他沟通方式， 从收钱开始就一直出问题， 到周初的时候好不容易认证通过了， 结果就和你一模一样， 他们的回复也是一样， 复制粘贴没脑子。WeChat Sucks！
总而言之， 感谢！

**Comment by cslxxwilliam** [comment]
@jyouli 我们用海外帐号尝试分享链接也不成功。你们链接分享成功吗？

**Comment by jyouli** [comment]
@cslxxwilliam 分享链接指的是通过手机系统的分享列表然后用户选择微信去分享，这种情况不可能不能分享的，这个和账号没关系了，哪怕app内没有集成微信sdk都可以分享的，是手机系统分享
