### ISSUE TITLE
 cordova-plugin-wechat  不能和cordova-hot-code-push 同时使用

### ISSUE THREAD

**Issue by aiooo3838** [xu-li/cordova-plugin-wechat#365]
如果是用了热更新 的话。一直提示没有安装。js中 Wechant 对象没有。感谢作者提供源码。这个问题一直没有解决。

**Comment by duanwenjian** [comment]
我们项目使用了cordova-plugin-wechat  和 cordova-hot-code-push 插件，能够正常使用，需要注意的是 如果中途添加的 cordova-plugin-wechat 插件，那么你需要一个全量更新更新native的代码。然后你需要保证 wechat.js 在 cordova_plugin.js 中
