### ISSUE TITLE
缩略图在IOS上，分享出去，显示的是微信默认那个链接图标，在Android上显示的是正确

### ISSUE THREAD

**Issue by Skye27yang** [xu-li/cordova-plugin-wechat#366]
在IOS上，分享出去，显示的是微信默认那个链接图标，在Android上显示的是正确。
在安卓分享给微信好友，微信好友在iOS下看显示的是微信默认那个链接图标，安卓好友在手机上看是正确的。

**Comment by siwei0729** [comment]
想问一下，微信分享是怎么做的，我可以使用微信登录，但是微信分享却提示分享的app 未获得权限，这个好尴尬。 开放平台显示已获得权限

**Comment by LiangS** [comment]
我也遇到同样问题：在IOS上分享出去，显示的是微信默认那个链接图标，在Android上显示的是正确。

**Comment by zhaoxu666** [comment]
我也遇到了这个问题，你们已经解决了么？
