### ISSUE TITLE
提交地址怎么定义

### ISSUE THREAD

**Issue by rowbone** [xu-li/cordova-plugin-wechat#369]
var params = {
    partnerid: '10000100', // merchant id
    prepayid: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
    noncestr: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
    timestamp: '1439531364', // timestamp
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
};

这里的demo没有提交地址，应该怎么定义提交地址。这里不应该是有个提交地址吗，不然demo里的php部署后怎么用

**Comment by xu-li** [comment]
这是返回的内容，提交地址你自己定义，用ajax调用啊。
