### ISSUE TITLE
如何快速测试？

### ISSUE THREAD

**Issue by jackyon** [xu-li/cordova-plugin-wechat#37]
我使用的是ionic，然后在ios simulator 下进行测试，但是貌似连接不上微信，提示未安装微信，但是网上搜索了下，貌似ios simulator不允许装app store上的软件，请问这种情况下，我应该如何快速测试？

谢谢

**Comment by xu-li** [comment]
可以用真机测试啊。真机比Simulator还快。

**Comment by jackyon** [comment]
请问具体的步骤是？我平时在真机上测试都是用ionic view然后连接他们远程测试的

**Comment by xu-li** [comment]
不用啊。

1. 所有除微信的功能
  * ```ionic serve```，直接在浏览器里面调试。
2. 微信相关的功能
  * ```ionic run ios --device```，直接跑在真机上。
  * ```ionic build ios```，然后XCode打开，按照一般的iOS应用改。

**Comment by jackyon** [comment]
@xu-li ， 刚才误解你的意思了，我以为你说的真机是实际的机子 ;)

是的我用的就是xcode打开，然后配置了url type之后，运行打开真机，然后发现点击任何地方都是提示微信未安装。
![screen shot 2015-06-11 at 5 40 59 pm](https://cloud.githubusercontent.com/assets/1758938/8104199/764317c2-1061-11e5-86e5-5146efafb724.png)

请问怎么解决？因为我想看看具体的实际效果。谢谢

**Comment by jackyon** [comment]
oops.. 原来xcode  有个真机测试的功能，sorry! 我查看下文档，看看能不能正常运行，然后再关闭此帖，谢谢了！
