### ISSUE TITLE
小程序分享功能

### ISSUE THREAD

**Issue by realfly08** [xu-li/cordova-plugin-wechat#370]
如果想分享小程序， 大神有没有计划支持？

**Comment by xu-li** [comment]
小程序跟这个不一样。不能分享过去。

**Comment by realfly08** [comment]
我已经实现了 从app分享至微信的功能，只是在微信里面打开测试版的小程序会有问题

**Comment by mchenx** [comment]
这个是可以的，微信官网就有说明

![image](https://user-images.githubusercontent.com/1550186/40464262-ca5e2e4a-5f4c-11e8-9c2b-dcae2498f1b3.png)

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317340&token=&lang=zh_CN
