### ISSUE TITLE
IOS分享成功 安卓无法分享

### ISSUE THREAD

**Issue by YuyangHYY** [xu-li/cordova-plugin-wechat#371]
安卓分享给朋友和朋友圈都是点击后进入微信， 然后直接闪退回到自己的手机应用，无法分享。
但是IOS分享正常，朋友和朋友圈都没有问题，所以应该不是appID等问题

**Comment by YuyangHYY** [comment]
我大概浏览了下你的回复 基本都是说**android的签名问题**
我签名都是通过而且可以上架google play store也是需要改动是么？
还有我是用的ionic3，全部签名方式都是跟着[https://ionicframework.com/docs/intro/deploying/](ionic官方文档)的方式进行的，这样可以么？

**Comment by xu-li** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN
