### ISSUE TITLE
由于不支持的分享类型，无法分享到微信

### ISSUE THREAD

**Issue by lq4593** [xu-li/cordova-plugin-wechat#375]
Wechat.share({
		  text: "This is just a plain string",
		  scene: Wechat.Scene.TIMELINE   // share to Timeline
		}, function () {
		  alert("Success");
		}, function (reason) {
		  alert("Failed: " + reason);
		});
---最简单的都不行
		Wechat.share({
		  message: {
			title: '1',
			description: '1',
			thumb: 'http://tech.qq.com/zt2012/tmtdecode/252.htm',
			mediaTagName: "TEST-TAG-001",
			messageExt: "这是第三方带的测试字段",
			messageAction: "<action>dotalist</action>",
			media: {
			  type: Wechat.Type.WEBPAGE,
			  webpageUrl:link
			}
		  },
		  scene: Wechat.Scene.TIMELINE // share to SESSION
		}, function() {
		  alert("Success");
		}, function(reason) {
		  alert("Failed: " + reason);
		});
--- 两个都是一样问题

**Comment by hiyali** [comment]
目测是 app_id 不对，可以检查xcode里 或 android studio 里的 Info > URL Types > URL schemes 中关于微信的部分
