### ISSUE TITLE
cordova-plugin-wechat添加后Wechat 是全局变量吗？

### ISSUE THREAD

**Issue by iwen-pengh** [xu-li/cordova-plugin-wechat#376]
ionic plugin add cordova-plugin-wechat --variable wechatappid=wx4a525790c75c494f

后使用
Wechat.isInstalled(function (installed) {
    alert("Wechat installed: " + (installed ? "Yes" : "No"));
}, function (reason) {
    alert("Failed: " + reason);
});

提示wechat 不存在

**Comment by xu-li** [comment]
是全局变量。

**Comment by y13818463245** [comment]
我也是这个问题，提示Wechat undefind

**Comment by y13818463245** [comment]
我知道原因了，你是不是在首页调试的，首页调试不行，其他页面没问题
你试试首页用 $timeout 执行

**Comment by xu-li** [comment]
device ready了么？
