### ISSUE TITLE
不兼容 小米6一闪而过

### ISSUE THREAD

**Issue by 15228554610** [xu-li/cordova-plugin-wechat#378]
调用后小米6手机一闪而过其他手机可以

**Comment by 15228554610** [comment]
调用后小米6手机一闪而过其他手机可以

**Comment by tobyforever** [comment]
我也是

**Comment by tobyforever** [comment]
小米5s miui9 7.10.19 android7.0 可以成功。  小米6 miui9 7.11.2 android7.1.1 失败一闪而过提示“未知错误”。华为荣耀8 EMUI4.1 android6.0可以成功。

**Comment by jerrytang67** [comment]
小米6 miui9表示 完全 没有问题

**Comment by a81584944** [comment]
....多检查签名
