### ISSUE TITLE
记录一下支付返回“普通错误”的问题解决方法

### ISSUE THREAD

**Issue by coxapp** [xu-li/cordova-plugin-wechat#380]
我在调试Android支付时遇到的“普通错误”：
1.调用支付返回普通错误，logcat里边有错误日志：appkey invalid，说明appid不正确，我安装插件时appid还没有下来，后面覆盖安装，有的地方appid没有覆盖，修改过后可以正常支付了；
2.logcat没有错误日志，返回普通错误，把应用签名配置到微信开发平台里面就可以了；
![qq 20171104141634](https://user-images.githubusercontent.com/5440550/32402983-d13fd8ec-c16a-11e7-8766-87f72169483a.png)

**Comment by zzhua2007** [comment]
你好，请问"把应用签名配置到微信开发平台里面"是什么步骤，是增加插件是加入后面的变量参数吗？ --variable wechatappid=YOUR_WECHAT_APPID

**Comment by zurmokeeper** [comment]
不是，这个是你的appid，题主的意思是当你把整个apk打包出来了，然后用工具拿到这个app的应用签名，然后再填到到你的微信后台的照片位置上。就可以了
