### ISSUE TITLE
用Wechat.auth如何提取用户资料，完成第三方登录...How to get userid, user name after using Wechat.auth

### ISSUE THREAD

**Issue by YuyangHYY** [xu-li/cordova-plugin-wechat#384]
我用了你的方法
```
// Not tested.
Wechat.auth(scope, function (response) {
    // $ = jQuery
    var appId = "YOUR_APP_ID";
    var appSecret = "YOUR_APP_SECRET";
    $.get('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appId + '&secret=' + appSecret + '&code=' + response.code + '&grant_type=authorization_code', function (accessTokenResponse) {
        // you should save access token response somewhere, e.g. cookies, local storage, etc.
        var accessToken = accessTokenResponse.access_token;
        var openId = accessTokenResponse.openid;

        // get user information
        $.get("https://api.weixin.qq.com/sns/userinfo?access_token=' + accessToken + '&openid=' + openId + '&lang=zh_CN", function (userInfoResponse) {
            console.log(userInfoResponse);
        });
    });
});
```
但是我这出现了一个问题，所有信息都测试过，全部都提取成功在电脑上，但是在手机上登录后显示
微信登录失败
此公众号并没有这些scope的权限，
错误码：10005
下面是截图
![1d8b06c86f9cd02cc974406a033de502](https://user-images.githubusercontent.com/19391002/33163894-7c40c6ca-d06b-11e7-8432-b3e34c8bc2c7.jpg)

如果我用这个登录的话，可以成功提取code等第一步所需信息
![2017-11-23 16 31 58](https://user-images.githubusercontent.com/19391002/33164004-e7374ada-d06b-11e7-9788-74f74a1570c2.png)

**Comment by YuyangHYY** [comment]
但是用response.code一直没有测试出来是否可以提取成功
因为一直显示没有scropt权限

**Comment by YuyangHYY** [comment]
可是我用的就是微信开放平台阿 为什么会出现公众号呢？

**Comment by YuyangHYY** [comment]
我用的就是微信开放平台 我就是奇怪为什么会出现提示“公众号的问题”
是我注册应用的问题么 我注册的是“移动应用”，我需要的是在手机应用里面的第三方登录。
我发现里面还有一个叫“第三方平台”
![2017-11-24 09 21 20](https://user-images.githubusercontent.com/19391002/33191915-3058062c-d0f9-11e7-97eb-b07c068754e8.png)

**Comment by YuyangHYY** [comment]
你的$ = jQuery，我写的Wechat.auth是不是这个的问题呢？

Wechat.auth('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appId + '&secret=' + appSecret + '&code=' + code + '&grant_type=authorization_code', function (accessTokenResponse)

Wechat.auth('https://api.weixin.qq.com/sns/userinfo?access_token=' + accessToken + '&openid=' + openId + '&lang=zh_CN', function (userInfoResponse)

**Comment by xu-li** [comment]
你这是干嘛？看一下文档，不是这么调用的。

https://github.com/xu-li/cordova-plugin-wechat#authenticate-using-wechat

**Comment by YuyangHYY** [comment]
亲，我就是根据您说的那个做的
```
wechatLogin(){
    let scope = "snsapi_userinfo",
    state = "_" + (+new Date());
    Wechat.auth(scope, state, function (response) {
      //alert(JSON.stringify(response));
      var appId = "我的appID";
      var appSecret = "我的appSecret";
      //var code = JSON.stringify(response.code);
      Wechat.auth('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appId + '&secret=' + appSecret + '&code=' + response.code + '&grant_type=authorization_code', function (accessTokenResponse) {
        alert(JSON.stringify(accessTokenResponse));
          // you should save access token response somewhere, e.g. cookies, local storage, etc.
          var accessToken = accessTokenResponse.access_token;
          var openId = accessTokenResponse.openid;
          // get user information
          Wechat.auth('https://api.weixin.qq.com/sns/userinfo?access_token=' + accessToken + '&openid=' + openId + '&lang=zh_CN', function (userInfoResponse) {
              console.log(userInfoResponse);
          });
      });
    });
  }
```

**Comment by xu-li** [comment]
你看一下什么是OAuth，和微信的文档吧。

我的那个Auth方法，只是用来获取code，用这个code，再去获取access token的时候，你要自己写(可以用服务器端，可以前端)。

-Xu

**Comment by YuyangHYY** [comment]
这个是我在issue那边看到您的回复：
```
// Not tested.
Wechat.auth(scope, function (response) {
    // $ = jQuery
    var appId = "YOUR_APP_ID";
    var appSecret = "YOUR_APP_SECRET";
    $.get('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appId + '&secret=' + appSecret + '&code=' + response.code + '&grant_type=authorization_code', function (accessTokenResponse) {
        // you should save access token response somewhere, e.g. cookies, local storage, etc.
        var accessToken = accessTokenResponse.access_token;
        var openId = accessTokenResponse.openid;

        // get user information
        $.get("https://api.weixin.qq.com/sns/userinfo?access_token=' + accessToken + '&openid=' + openId + '&lang=zh_CN", function (userInfoResponse) {
            console.log(userInfoResponse);
        });
    });
});
```

您的JQuery我是用的Wechat.auth，您的意思是这个是不正确的
因为刚入门 不确定怎么写
想了解下您那边的JQuery我应该是如何写呢
我facebook那边是`this.fb.login`，我尝试过用`this.Wechat.login`等等，xcode log那边显示都是无法识别，我想在写在前端，如何实现呢？ 
感谢！

**Comment by xu-li** [comment]
就是用jQuery写啊，按照我上面的代码。$和Wechat.auth不是一个东西。你去看一下文档吧。

-Xu

**Comment by YuyangHYY** [comment]
我用的是ionic3 typescript不识别JQ，我安装`npm install --save @types/jquery` ，使用了$之后xcode log显示了下面的error：
> 2017-11-27 14:58:06.145655+0800 民安-马来西亚[314:25807] THREAD WARNING: ['Wechat'] took '38.095947' ms. Plugin should use a background thread.
> 2017-11-27 14:58:07.408589+0800 民安-马来西亚[314:25807] FB handle url: wxec56aa94e0b75717://oauth?code=0117fL3W0pbitV1ANj5W0v7A3W07fL3j&state=_1511765886066
> 2017-11-27 14:58:07.451633+0800 民安-马来西亚[314:25807] Error in Success callbackId: Wechat552311291 : ReferenceError: Can't find variable: $

**Comment by xu-li** [comment]
#197 ,或者看我的https://github.com/xu-li/cordova-plugin-wechat-example/.

**Comment by YuyangHYY** [comment]
@xu-li 我看了你的example的那个 没有提取第三方登录的方法阿，分享我这边已经成功了

**Comment by YuyangHYY** [comment]
现在完全alert不出东西 xcode这边log显示
`Error in Success callbackId: Wechat240930706 : ReferenceError: Can't find variable: $`

**Comment by Bertwindwang** [comment]
你好，我想问一下你，用ionic2来做，  Wechat.auth下面打印出来是null，能麻烦告诉这个是什么原因吗？微信分享都没有问题？

**Comment by xu-li** [comment]
要通过审核，开通登录权限
