### ISSUE TITLE
安装时，会把gradle-wrapper.properties里的最后一行改成gradle-2.14.1-all.zip

### ISSUE THREAD

**Issue by buhairong** [xu-li/cordova-plugin-wechat#385]
因为现在使用的Android Studio的版本是2.3.1的，gradle-2.14.1-all.zip最多使用到Android Studio2.2版本，2.3.1的版本默认gradle是3.3的版本。
每次运行 cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID 安装时，就会报 Minimum supported Gradle version is 3.3. Current version is 2.14.1的错误，并且把gradle-wrapper.properties里的最后一行也改成了distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip。
请教该如何解决这个问题呢？麻烦您了。

**Comment by xu-li** [comment]
如果你用了Android Studio，你就一直用Android Studio，add只会在开始的时候用到一次。
