### ISSUE TITLE
Hello Super Application

### ISSUE THREAD

**Issue by negdim** [xu-li/cordova-plugin-wechat#386]
I want to integrate your cordova plugin with my ionic application. I'm Foriegner Ionic Develpor working in China now. Can you help me for this project? If you want i can pay to you. Thanks.
Can you leave me your wechat address? Thanks.

**Comment by xu-li** [comment]
Thanks for your interest. You may reach me at AthenaLightenedMyPath@gmail.com via email.

**Comment by negdim** [comment]
Thanks You are Cool 👍 💯
