### ISSUE TITLE
build android error

### ISSUE THREAD

**Issue by smallg** [xu-li/cordova-plugin-wechat#387]
![image](https://user-images.githubusercontent.com/225962/33296303-ca0ff328-d415-11e7-85ae-92e062fc3990.png)
昨天还是好的，今天突然就挂了

**Comment by smallg** [comment]
我查了下，这个地址下没有mm这个目录啊
https://repo1.maven.org/maven2/com/tencent/

**Comment by xu-li** [comment]
https://jcenter.bintray.com/com/tencent/mm/opensdk/wechat-sdk-android-with-mta/
