### ISSUE TITLE
安卓端微信登陆状态下无法调起

### ISSUE THREAD

**Issue by SunXingZ** [xu-li/cordova-plugin-wechat#388]
安卓端微信登陆状态下无法调起、返回未知错误，未登录状态可以调起。 @xu-li

**Comment by smallg** [comment]
检查签名https://github.com/xu-li/cordova-plugin-wechat/issues/389

**Comment by SunXingZ** [comment]
@smallg 谢谢！是签名的问题，问题已解决

**Comment by smallg** [comment]
@SunXingZ close下这个issue，thx
