### ISSUE TITLE
微信界面一闪而过，报未知错误

### ISSUE THREAD

**Issue by buhairong** [xu-li/cordova-plugin-wechat#389]
使用
Wechat.isInstalled(function (installed) {
    alert("Wechat installed: " + (installed ? "Yes" : "No"));
}, function (reason) {
    alert("Failed: " + reason);
});
打印出Wechat installed:yes

使用
var scope = "snsapi_userinfo",
    state = "_" + (+new Date());
Wechat.auth(scope, state, function (response) {
    // you may use response.code to get the access token.
    alert(JSON.stringify(response));
}, function (reason) {
    alert("Failed: " + reason);
});
微信界面一闪而过
打印 Failed:未知错误
请问是什么问题导致的呢？该如何解决呢？麻烦您了，谢谢！

**Comment by smallg** [comment]
首先检查签名
步骤：

1. 安装你的APP到手机
2.安装签名检测工具http://wiki.open.qq.com/wiki/%E7%AD%BE%E5%90%8D%E9%97%AE%E9%A2%98
输入包名
3.检测工具生成的签名是否和你keystore里的签名，还有公众平台配置的是否完全一直
4.卸载微信重装，我遇到的为止错误在这一步才解决……

**Comment by zhangjingle** [comment]
我改了appid,然后也这样了...我把微信卸载然后重新安装就好使了...这是个bug吧..

**Comment by ygr15893000** [comment]
小米5，签名正确的情况下，一闪而过报未知错误，我的做法是，手机恢复出厂设置，再安装app和微信，问题解决
