### ISSUE TITLE
IOS 提示 微信未安装

### ISSUE THREAD

**Issue by buhairong** [xu-li/cordova-plugin-wechat#391]
目前在安卓上微信登录使用良好。
但是ios里，使用
Wechat.isInstalled(function (installed) {
    alert("Wechat installed: " + (installed ? "Yes" : "No"));
}, function (reason) {
    alert("Failed: " + reason);
});
总是打印：Wechat installed: No
而在安卓下，是打印Yes的。
请问是什么地方出了问题，该如何解决呢？麻烦您了，谢谢！

**Comment by buhairong** [comment]
已解决

**Comment by ywcsz** [comment]
是怎么解决的？

**Comment by ywcsz** [comment]
可以了，info.list要加URL Schemes
