### ISSUE TITLE
微信分享成功后，点击返回app，app会重新启动？

### ISSUE THREAD

**Issue by qikong333** [xu-li/cordova-plugin-wechat#395]

**Comment by bowerliu** [comment]
我也遇到了

**Comment by qikong333** [comment]
http://www.jianshu.com/p/014920291e3b

**Comment by bowerliu** [comment]
我这应该不是签名问题，我用另外一个plugin 已经成功分享了，我用这个主要是用授权功能

**Comment by bowerliu** [comment]
问题解决，升级了cordova android platform 到7.0.0 退回6.3就可以 ，看来新的还是问题
