### ISSUE TITLE
cordova android 7.0.0 暂不支持

### ISSUE THREAD

**Issue by todayliu** [xu-li/cordova-plugin-wechat#396]
cordova android 7.0.0 暂不支持，有手工方法么

**Comment by xciceboy** [comment]
+1
可否通过修改xml配置操作呢

**Comment by xciceboy** [comment]
QQ也是刚修改的 support Cordova-Android 7.0
https://github.com/iVanPan/Cordova_QQ/commit/d4bf56146e3958dda0be5252e2be3e84bf5d444f

**Comment by xiao940622699** [comment]
我的android 7.0以下不支持

**Comment by xiao940622699** [comment]
请问有解决吗

**Comment by uddsoft** [comment]
有解决办法吗。

**Comment by zz-33** [comment]
@xu-li 大牛尽快支持Cordova-Andoird 7.0.0啊，不然别的跟别的插件依赖版本互斥，很尴尬啊...
