### ISSUE TITLE
和cordova-plugin-sharesdk 分享插件冲突  有什么解决办法么

### ISSUE THREAD

**Issue by xjh19920000** [xu-li/cordova-plugin-wechat#402]
Element activity#com.yijianyouqing.mm.wxapi.WXEntryActivity at AndroidManifest.xml:33:9 duplicated with element declared at AndroidManifest.xml:32:9

cordova-plugin-sharesdk分享插件中带了微信分享，这个插件中也带了分享功能. 好像是两个冲突了  ,我用这个插件主要是支付和登录功能。请教一下解决方案

**Comment by CodingHide** [comment]
@xjh19920000 你的问题解决了吗？

**Comment by CodingHide** [comment]
插件冲突比较难解决，我是直接卸载其他插件

**Comment by kanekilua** [comment]
同cordova-plugin-sharesdk冲突/doge，然后sharesdk也被我卸了= =
