### ISSUE TITLE
集成插件之后可跳转至微信授权页面，但是授权返回自己的APP之后  显示app停止工作，并重启app，导致取不到code

### ISSUE THREAD

**Issue by 248243224** [xu-li/cordova-plugin-wechat#407]

**Comment by 248243224** [comment]
我看了其他人报的BUG，有好几个跟我一样的，微信验证返回当前app会导致重启，我的问题跟https://github.com/xu-li/cordova-plugin-wechat/issues/340 应该是一样的。

**Comment by 248243224** [comment]
但是我这边编译项目由于种种原因不能像https://github.com/xu-li/cordova-plugin-wechat/issues/340上面说的修改插件里面的__PACKAGE_NAME__。能不能帮忙解决一下~急~~~

**Comment by 248243224** [comment]
用的是phonegap build

**Comment by iamnotstone** [comment]
这是cordova版本太高，不兼容这个插件所导致的。解决方案是修改$your_project/plugins/cordova-plugin-wechat/scripts/android-install.js中的
var targetDir = path.join(projectRoot, "platforms", "android", "src", packageName.replace(/\./g, path.sep), "wxapi");

修改为
var targetDir = path.join(projectRoot, "platforms", "android", "app","src","main","java", packageName.replace(/\./g, path.sep), "wxapi");

修改后，重新装一下平台
cordova platform remove android
cordova platform add android

这样同样能达到 @clyquan 所提到的修改效果，就是让插件把那三个类复制到正确的位置。

**Comment by zzhua2007** [comment]
谢谢感谢这个答案。

**Comment by iamnotstone** [comment]
@zzhua2007 客气了

**Comment by dut3062796s** [comment]
@iamnotstone   您好,很感谢您的答案,帮到了我，谢谢

**Comment by iamnotstone** [comment]
不用客气
----- 原始邮件 -----
发件人：杜鹏 <notifications@github.com>
收件人：xu-li/cordova-plugin-wechat <cordova-plugin-wechat@noreply.github.com>
抄送人：iamnotstone <iamnotstone@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[xu-li/cordova-plugin-wechat]_集成插件之后可跳转至微信授权页面，但是授权返回自己的APP之后_显示app停止工作，并重启app，导致取不到code_(#407)
日期：2018年04月04日 15点06分

@iamnotstone   您好,很感谢您的答案,帮到了我，谢谢

&mdash;

**Comment by lulersoft** [comment]
谢谢，这个可以。解决问题啦。
