### ISSUE TITLE
Can't find variable: Wechat

### ISSUE THREAD

**Issue by acylum** [xu-li/cordova-plugin-wechat#41]
I don't get why this is happening - it was working before.  now when I try to do things like:
Wechat.isInstalled(function (installed) {
                       alert("Wechat installed: " + (installed ? "Yes" : "No"));
                       }, function (reason) {
                       alert("Failed: " + reason);
                       });

I get - "Can't find variable: Wechat" - is as if something happened to the plugin mapping, but I checked the config.xml and it looks fine:
<feature name="Wechat">
        <param name="ios-package" value="CDVWechat" />
        <param name="onload" value="true" />
    </feature>

What else could have happened where the Wechat variable is not found?

**Comment by acylum** [comment]
So, I removed the previous we chat plugin, then reinstalled the latest we chat plugin and received this error message in the console:   CDVPlugin class CDVWechat (pluginName: wechat) does not exist.

**Comment by xu-li** [comment]
@acylum ios or android? cordova version? How about backup your source code, remove platform(ios or android), and add platform back?

**Comment by iVanPan** [comment]
@acylum  open Xcode，build Phases ，check Compile Sources，if you don't find CDVWechat，add it please。

**Comment by acylum** [comment]
Hi 

iOS - cordova 3.7.  I did try to add CDVWechat and received lots of build errors.  Finally, I rebuilt the project from an older backup to get everything working again...
