### ISSUE TITLE
使用Ionic3开发，请问如何添加 npm @native 的引用？

### ISSUE THREAD

**Issue by nixiaozi** [xu-li/cordova-plugin-wechat#410]
在使用Ionic 官方提供的分享插件的时候，我需要执行
$ ionic cordova plugin add cordova-plugin-x-socialsharing
$ npm install --save @ionic-native/social-sharing
前面用来添加插件，
后面一个命令用来添加对native引用。
但是我现在使用以下命令添加了这个插件
cordova plugin add cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID

但是却没有办法直接使用Wechat，，可能是没有添加native引用的原因，请问这个该如何添加？

页面参考 https://ionicframework.com/docs/native/social-sharing/

**Comment by xciceboy** [comment]
不用

**Comment by xciceboy** [comment]
(<any>window).Wechat

**Comment by nixiaozi** [comment]
@xciceboy   可以了。谢谢。
