### ISSUE TITLE
分享时出错，failed：未安装微信

### ISSUE THREAD

**Issue by ywcsz** [xu-li/cordova-plugin-wechat#412]
用最新版本在ios会出 "未安装微信"的错误，android下没问题，哪位大侠帮个忙！

  Wechat.share(params, function() {
            // alert("Success");
            utility.showToast($translate.instant('shareok'));
        }, function(reason) {
            alert("Failed: " + reason);弹出未安装微信
            utility.showToast($translate.instant('cancelshare'));
        });

**Comment by ywcsz** [comment]
解决了，info.list添加url Schemes！多谢！

**Comment by joehui** [comment]
Same problem.  Can you provide more details?   How do you add "url Schemes" to info.list?

**Comment by joehui** [comment]
I actually found and fixed the problem.  It is nothing to do with the "url schemes" in my case.  My problem was caused by the tooling I used didn't pass the WeChatAppId into the plugin.
