### ISSUE TITLE
开发者资质认证

### ISSUE THREAD

**Issue by hesijie** [xu-li/cordova-plugin-wechat#413]
使用这个微信插件开发，必须要进行开发者资质认证后才能成功分享吗？

**Comment by cslxxwilliam** [comment]
同问！

**Comment by hesijie** [comment]
@cslxxwilliam  我搞清楚了，分享到朋友圈和发送给朋友这两个功能是不用开发者资质认证也能分享成功的，其它的就要资质认证了

**Comment by cslxxwilliam** [comment]
@hesijie 确定吗？我在手机上试，能转跳到微信，但会报错：由于不支持的分享类型，，无法分享到微信；返回（未审核应用）。我已经是最简单的文字分享到朋友圈也有问题

**Comment by hesijie** [comment]
我确定，我周五才测试成功的，你的应用通过审核了吗？要通过审核才行，

**Comment by cslxxwilliam** [comment]
@hesijie 但是不做资格验证，可以通过审核应用吗？

**Comment by hesijie** [comment]
可以通过应用审核，只是等的时间比较长，我等了应该有五个工作日
