### ISSUE TITLE
安卓分享微信，我的手机可以分享，但其他的手机不可以分享，APP在不同手机上的应用签名也都是一致的，什么原因？

### ISSUE THREAD

**Issue by xiao940622699** [xu-li/cordova-plugin-wechat#414]
现在遇到的问题是，我的手机是可以分享微信成功，别人的手机不可分享微信时，直接退出应用程序。
有以下条件：
1.已经在微信开发者平台上安卓审核通过。
2.不能分享的手机上该程序的应用签名和在我的手机的上的应用签名是一致的。
3.以下的权限已经打开
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
4.IOS的都可以分享微信成功。

**Comment by ZiSeFeng** [comment]
-  @问题有解决吗
