### ISSUE TITLE
【求救】分享后app重启，GitHub上的办法都试过无用

### ISSUE THREAD

**Issue by moonlitnighta** [xu-li/cordova-plugin-wechat#418]
大神们帮帮忙   , 分享后app重启，GitHub上 什么改 targetDir     加preference name="AndroidLaunchMode" value="singleTask"  都试过  没有一点变化

cordova :7.0.1
cordova android :6.3.0
手机： 华为MT7

**Comment by tz310200** [comment]
我也是,同问

**Comment by Dorsey-CN** [comment]
同问   很是头疼

**Comment by Dorsey-CN** [comment]
#407 里面有解决方案

**Comment by moonlitnighta** [comment]
@Dorsey-CN 407我看了 改了targetDir 还是会重启app

**Comment by Dorsey-CN** [comment]
@moonlitnighta  修改后有移除平台，重新添加平台吗？   我改了targetDir ，然后重新添加平台后就没有再出现问题啦
