### ISSUE TITLE
android上thumb图片路径问题

### ISSUE THREAD

**Issue by fantasybei** [xu-li/cordova-plugin-wechat#42]
Wechat.share({
    message: {
        title: title,
       description: description,
       thumb: logo,
					        .....
					    },

如果这里的thumb传的是类似 www/img/xxx.png这样的字符串，ios上是可以的，android上会说找不到该文件。看了下代码是直接传给这个方法的 BitmapFactory.decodeFile(url);这里是要处理下路径问题吧？

**Comment by xu-li** [comment]
@fantasybei 可以用*external://*.

**Comment by fantasybei** [comment]
好的，我试试看先，能否添加我QQ啥的？有问题想请教你。我的邮箱: fantasybei@gmail.com

**Comment by fantasybei** [comment]
我试了下加上external://后变成了路径变成了 /storage/emulated/0/www/img/logo.png， 不过还是找不到文件。

**Comment by xu-li** [comment]
你需要的是相对路径，对吧？暂时好像不支持。回头可以加一个。QQ我基本不上，不好意思。

**Comment by fantasybei** [comment]
我之前做ios上的分享是参照你的例子，图片url写的是www/img/xxx.png  今天调android的时候发现分享不能用，就看了下，是找不到文件的原因，所以现在要弄个解决办法，我想应该是可以在Wechat.java中改下getImageURL这个方法，看怎么拿到图片在设备上的绝对路径应该就可以了，但是对android/phonegap插件不太熟，所以不知道该怎么拿到这个路径。

**Comment by xu-li** [comment]
可以试试[这个](http://stackoverflow.com/questions/16075778/access-a-image-dynamically-from-res-folder-android)，回头我更新个版本吧。

**Comment by fantasybei** [comment]
现在在赶时间弄项目，你有时间帮忙看看吧，谢谢

**Comment by xu-li** [comment]
@fantasybei 我更新了一下版本，应该没问题了。

**Comment by fantasybei** [comment]
恩，现在可以了，谢谢
