### ISSUE TITLE
同一订单第一次发起请求成功，取消后再次发起返回“普通错误”，log日志为invalid appkey

### ISSUE THREAD

**Issue by zurmokeeper** [xu-li/cordova-plugin-wechat#420]
Server response error code:404, error:{"ret":-1, "msg":"invalid appkey"}

已经是验证多次签名了，打的也是正式版了。但是还是报这个错？安卓端，cordova版本为7.0.0.
同样的后台代码，IOS没有什么问题。

**Comment by JayzeeHuang** [comment]
订单号是唯一的  再次发起要更新一下你的订单号

**Comment by zurmokeeper** [comment]
我的订单号是随机生成的啊，用的是时间戳，应该不会重复的啊。如果有重复的话，那IOS那里也会报错才对的啊？

**Comment by JayzeeHuang** [comment]
两边的appkey是相同的么？

**Comment by zurmokeeper** [comment]
你说的这个appkey指微信后台的那个吧，都是同样的后台代码，肯定是一样的。

**Comment by zurmokeeper** [comment]
我现在终于明白您说的两边的appkey是相同的什么意思了。我解决了。

**Comment by zurmokeeper** [comment]
解决方法：
用个工具：链接 https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=8_5 参考安卓部分。再安装好APK之后，再安装这个工具拿到你的app的应用签名，然后填到你的微信后台去，再次跑就可以了。

应用签名填写位置：#380 参考这个链接的。

同时你的APP 配置文件里面的包名和微信后台设置的那个包名也要一样的。
