### ISSUE TITLE
微信认证，微信分享，只在手机第一次安装app后发起有效

### ISSUE THREAD

**Issue by taixiangfei2016** [xu-li/cordova-plugin-wechat#423]
安卓系统，微信认证，微信分享，只在手机第一次安装app后发起能跳到微信app，以后发起认证，分享等功能全部是闪一下就跳回我的app了，这是什么原因？安装插件的时候只用到了AppId，AppSecret没用到，这个有用吗？

**Comment by Dorsey-CN** [comment]
你的错误原因我不清楚，但是安装插件的时候确实只需要AppId，不需要AppSecret

**Comment by xiao940622699** [comment]
应用程序的签名和微信平台上申请的应用程序签名一直吗，打包是Release打包的吗

**Comment by taixiangfei2016** [comment]
问题找到了，是应用签名和微信平添上申请appId时候填写的不一致导致的，因为前面的步骤是pm做的，我不知道错没错，花了好多时间才证明我的没问题，然后让pm纠正微信的签名key，当天还是不行，以为自己还是哪里没弄好，很丧气，但是第二天又试了一遍，成功发起了，我想原因就是 微信上的签名改了之后得第二天0点才更新，所以遇到同样情况的朋友们第二天在试试，可能就好了

**Comment by dsitn201703** [comment]
@taixiangfei2016  请问一下，你们使用这个插件时，appid都是用的线上正式的appid吗？有没有用微信沙箱appid的？

**Comment by taixiangfei2016** [comment]
@dsitn201703  pm给我的就一个正式appid
