### ISSUE TITLE
最新的2.3.0版本安卓编译不过

### ISSUE THREAD

**Issue by swcan-xmouse** [xu-li/cordova-plugin-wechat#429]
最新的2.3.0版本安卓编译不过
跟#427类似，少了前面的错误，以下错误还存在
/platforms/android/src/xu/li/cordova/wechat/Wechat.java:337: 错误: 无法将类 Wechat中的方法 getAppId应用到给定类型;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  需要: 没有参数
  找到: Activity
  原因: 实际参数列表和形式参数列表长度不同
/platforms/android/src/xu/li/cordova/wechat/Wechat.java:656: 错误: 无法从静态上下文中引用非静态 变量 preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
                    ^

**Comment by yahaln** [comment]
platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:281: 错误: 无法将类 Wechat中的方法 getAppId应用到给定类型;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  需要: 没有参数
  找到: Activity
  原因: 实际参数列表和形式参数列表长度不同
E:\workspace_ionic\estate-app\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:600: 错误: 无法从静态上下文中引用非静态 变量 preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
                    ^

**Comment by itguliang** [comment]
可以把那个方法的static去掉

**Comment by tianjin500w** [comment]
final String savedAppid = getAppId(cordova.getActivity()); 明显是写错了，是 getSavedAppId(cordova.getActivity())
另一条错误还在研究中

**Comment by tianjin500w** [comment]
大神给修复了  https://github.com/xu-li/cordova-plugin-wechat/pull/445

**Comment by ChrisFuck** [comment]
还是编译不过啊，有解决的吗

**Comment by zhqInfinity** [comment]
我只用了微信支付功能，根据大神的修复虽然编译不报错了，但是微信支付功能不能用，会出现闪退，然后我看到有人用之前的老版本可以，我尝试了下，插件用2.1.0版本，cordova-android用6.4.0版本是可以使用的，目前是这么解决的，回退版本

**Comment by jasonz1987** [comment]
请使用 2.5.0版本
