### ISSUE TITLE
Do WeChat have a webview for authentication?

### ISSUE THREAD

**Issue by winsonchan** [xu-li/cordova-plugin-wechat#43]
It maybe a weird question, but just want to ask if there are any webview for WeChat for authentications.

Thank you for this great plugin, it worked charm in both iOS and Android, but when it comes to app submission to the Apple app store rejected claiming we should provide ways to allow people  to authenticate/login with WeChat for people without installing the WeChat app...such as a native webview.
So we wonder if there are any ways to provide such..

Many Thanks!

**Comment by xu-li** [comment]
@winsonchan I am afraid wechat doesn't have a native webview for authentication.

**Comment by Jeff-Tian** [comment]
@winsonchan , my app was rejected by the ios approval team due to the exact same reason you provided. It was finally got approved by my hidding the Wechat Login button if the wechat app was not detected. The code looks something like this:

```
            $scope.showWechatLogin = false;
            if (typeof Wechat !== 'undefined') {
                Wechat.isInstalled(function (installed) {
                    if (installed) {
                         // Only show wechat login button if the Wechat App was detected
                        $scope.showWechatLogin = true;
                    }
                }, function (reason) {
                });
            }
```
