### ISSUE TITLE
编译错误:

### ISSUE THREAD

**Issue by lulersoft** [xu-li/cordova-plugin-wechat#431]
BUILD FAILED in 2s
27 actionable tasks: 3 executed, 24 up-to-date
(node:2082) UnhandledPromiseRejectionWarning: Error: /Users/hfy/H5/LocalCar/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/hfy/H5/LocalCar/platforms/android/app/src/main/java/xu/li/cordova/wechat/Wechat.java:281: 错误: 无法将类 Wechat中的方法 getAppId应用到给定类型;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  需要: 没有参数
  找到: Activity
  原因: 实际参数列表和形式参数列表长度不同
/Users/hfy/H5/LocalCar/platforms/android/app/src/main/java/xu/li/cordova/wechat/Wechat.java:600: 错误: 无法从静态上下文中引用非静态 变量 preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "wx064dd4d317366f89");

**Comment by moonlitnighta** [comment]
同样问题，cordova 7.1.0!
@lulersoft  你先降到2.2.0 build 没问题的

**Comment by lulersoft** [comment]
@moonlitnighta 这怎么个降级法？请指点一下:)

**Comment by lulersoft** [comment]
@moonlitnighta 分享取消，APP会崩溃重启

**Comment by moonlitnighta** [comment]
#407

**Comment by jasonz1987** [comment]
请使用 2.5.0版本

**Comment by Codevers** [comment]
最后我发现把gradle升级一下就可以使用最新版，用cordova-android-support-gradle-release插件升级，我的cordova是7.1.0,cordova-android是6.3.0，gradle升级到26.+
