### ISSUE TITLE
2.3.0 编译失败 getAppId 错误

### ISSUE THREAD

**Issue by moonlitnighta** [xu-li/cordova-plugin-wechat#432]
cordova 7.1.0!

**Comment by exgphe** [comment]
应该是因为getSavedAppId错写成了getAppId

**Comment by JackZhang1988** [comment]
请问这个有解决方案吗？

**Comment by tianjin500w** [comment]
281行 改为 final String savedAppid = getSavedAppId(cordova.getActivity());  就解决这个问题了

**Comment by leedorian** [comment]
同样的问题，无解？

**Comment by tianjin500w** [comment]
惭愧，我水平低，现在暂时不用这个插件，以免工作卡壳，待后续程序完成了再研究。不过在 https://cordova.apache.org/plugins/?q=wechat&sortBy=Recently%20Updated  有若干个版本，有的近期才更新，还有网友说 cordov 8 不太兼容这个插件，说  cordov 7可以，但是我试过了，都能编辑过去，也都能运行，但是我在获取授权code时候就出错了。



tianjin500w

发件人： dorian lee
发送时间： 2018-07-08 11:12
收件人： xu-li/cordova-plugin-wechat
抄送： tianjin500w; Comment
主题： Re: [xu-li/cordova-plugin-wechat] 2.3.0 编译失败 getAppId 错误 (#432)
同样的问题，无解？

**Comment by jasonz1987** [comment]
请使用 2.5.0版本
