### ISSUE TITLE
安卓集成微信支付功能，使用微信沙箱账号，不能调起微信支付，报普通错误

### ISSUE THREAD

**Issue by dsitn201703** [xu-li/cordova-plugin-wechat#434]
您好，我这边使用微信官方提供的沙箱appid, 签名也是按照官方提供的方法获得的，在使用这个插件的支付功能时，不能成功唤启本地安装的微信app, 报错提示‘普通错误’。这个是什么原因呢？是不是这个插件不支持沙箱账号呢？下面是我使用这个插件传的参数。

var params = {
              partnerid: body.partnerId, // merchant id
              prepayid: body.prepayId, // prepay id
              noncestr: body.nonce, // nonce
              timestamp: `${body.timestamp}`, // timestamp
              sign: body.signature, // signed string
            }
Wechat.sendPaymentRequest(params, function () {
              alert("Success");
            }, function (reason) {
              alert("Failed: " + reason);
            });

**Comment by dsitn201703** [comment]
@xu-li   这个是不是因为我用的微信测试appid 导致的不能成功调起微信app? 请问你之前有用过测试appid来开发调试过吗 ？看了好多评论，感觉就这个插件靠谱点，但是一直不能成功调用，好捉急~在线等啊~

**Comment by haoning7788** [comment]
同理，参数没有什么问题，但是提示普通错误，估计是插件有问题@xu-li

**Comment by dsitn201703** [comment]
你也是使用的微信的沙箱账号来调用这个插件的支付功能吗 @haoning7788

**Comment by haoning7788** [comment]
@dsitn201703 不是的，是公司的账号，2.3有bug，appid没法获得，2.1普通错误，再试试2.2,不行就give up了....

**Comment by ygr15893000** [comment]
打包apk 使用release

**Comment by zurmokeeper** [comment]
为什么你要使用沙箱账号呢，直接使用正式的账号不行嘛？签名也是按照官方提供的方法获得的，你是用GenSignature 的这个APP获得的嘛？

**Comment by zhqInfinity** [comment]
安卓版本要验证包名的，打包成release版本，而且包名和你申请时候填写的包名一致才可以！
