### ISSUE TITLE
android微信支付出现”普通错误“

### ISSUE THREAD

**Issue by KanShadowsong** [xu-li/cordova-plugin-wechat#439]
plugin版本号 2.1.0

用Wechat.sendPaymentRequest() 出现“普通错误”..求帮助..

1. appId, app signature 和 package name与开发平台一致，测试过发text消息给个人，分享给朋友圈等，都成功。
2. 我发送的param：
`{
            'partnerid': PaymentConfig.MERCHANT_ID,
            'prepayid': prepayId, // 之前generate prepayid所得， wx开头的
            'noncestr': '<与我发给去generate prepayId的那个nonce_str一致>',
            'timestamp': Date.now(),
            'sign': '<calculateSign()所得，在https://pay.weixin.qq.com/wiki/tools/signverify/中调试过，结果一致>',
          };
`

3. log:

05-09 09:37:00.784 19433-19514/? D/Cordova.Plugin.Wechat: plugin initialized.
05-09 09:37:00.784 19433-19514/? D/Cordova.Plugin.Wechat: sendPaymentRequest is called. Callback ID: Wechat......
05-09 09:37:00.828 19433-19514/? I/Cordova.Plugin.Wechat: Payment request has been sent successfully.
05-09 09:37:01.103 19433-19433/? D/Cordova.Plugin.Wechat: com.tencent.mm.opensdk.modelpay.PayResp@.....
05-09 09:37:23.779 19433-19514/? D/Cordova.Plugin.Wechat: sendPaymentRequest is called. Callback ID: Wechat.......
05-09 09:37:23.814 19433-19514/? I/Cordova.Plugin.Wechat: Payment request has been sent successfully.
05-09 09:37:23.930 19433-19433/? D/Cordova.Plugin.Wechat: com.tencent.mm.opensdk.modelpay.PayResp@.....
05-09 09:40:38.215 19433-19514/? D/Cordova.Plugin.Wechat: sendPaymentRequest is called. Callback ID: Wechat.......
05-09 09:40:38.247 19433-19514/? I/Cordova.Plugin.Wechat: Payment request has been sent successfully.
05-09 09:40:38.359 19433-19433/? D/Cordova.Plugin.Wechat: com.tencent.mm.opensdk.modelpay.PayResp@.....

求助还有什么其他我忽略的会导致这个普通错误呢？

**Comment by KanShadowsong** [comment]
。。。没看到这个sign是要generate 2次而且timestamp是10位的。。。close了。。

**Comment by shawbs** [comment]
你好，我也碰到了同样的问题，请问你是怎么解决的呢？

**Comment by KanathanZhou** [comment]
> 你好，我也碰到了同样的问题，请问你是怎么解决的呢？

这个原因还蛮多的，我的是因为这个sign在支付的时候延用了第一次的而没有重新生成导致的，第二次的时候再生成一遍就好了。
你如果params都是通过后端直接调用微信api的话，应该不存在我这个问题。需要帮助的话可以贴code上来我帮你看下

**Comment by Tiramisu1** [comment]
> > 你好，我也碰到了同样的问题，请问你是怎么解决的呢？
> 
> 这个原因还蛮多的，我的是因为这个登录在支付的时候延用了第一次的而没有重新生成导致的，第二次的时候再生成一遍就好了。
> 你如果PARAMS都是通过后端直接调用微信API的话，应该不存在我这个问题。需要帮助的话可以贴代码上来我帮你看下

你好 我的params直接通过后台返回的数据 但是我还是报错“普通错误”，参数有noncestr partnerid prepayid sign timestamp 谢谢楼楼！

**Comment by 634596678** [comment]
你好 我从后台调了 appid                           partnerid
                            prepayid
                            noncestr
                            timestamp
                            sign
                            package: "Sign=WXPay"
这些参数
Wechat.sendPaymentRequest()的时候报了普通错误，请问有可能和你出错的方式一样吗
