### ISSUE TITLE
2.1版本和1.4版本可以编译成功，但是这两个版本的插件分享功能都只能成功分享到朋友圈，不能分享到会话

### ISSUE THREAD

**Issue by dsitn201703** [xu-li/cordova-plugin-wechat#441]
@xu-li 您好，2.1版本和1.4版本可以编译成功，但是这两个版本的插件分享功能都只能成功分享到朋友圈，不能分享到会话，这个是什么原因啊？能不能给我一个既能够分享到会话又能够分享到朋友圈的版本？求大侠帮帮忙！

**Comment by kzsense** [comment]
2.1是可以的。提供一些log才能帮
