### ISSUE TITLE
Can I share WeChat applet with this plugin?

### ISSUE THREAD

**Issue by senson2018** [xu-li/cordova-plugin-wechat#442]
Hello, friends.
My application has installed this plug-in. If I need to share a small program! What code do I need to change?Thank you very much！：）

Wechat.share({
    message: {
        title: "Hi, there",
        description: "This is description.",
        thumb: "www/img/thumbnail.png",
        mediaTagName: "TEST-TAG-001",
        messageExt: "这是第三方带的测试字段",
        messageAction: "<action>dotalist</action>",
        media: "YOUR_MEDIA_OBJECT_HERE"
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

**Comment by jasonz1987** [comment]
you can see branch `develop-mini`
