### ISSUE TITLE
亲爱的小伙伴们，可以进行小程序分享吗？

### ISSUE THREAD

**Issue by senson2018** [xu-li/cordova-plugin-wechat#443]
项目已经加入cordova-plugin-wechat有段时间了，最近看到cordova-plugin-wechat有微信小程序分享功能，请问一下，需要对下面的代码进行哪些更改吗？十分感谢哦！！！

Wechat.share({
    message: {
        title: "Hi, there",
        description: "This is description.",
        thumb: "www/img/thumbnail.png",
        mediaTagName: "TEST-TAG-001",
        messageExt: "这是第三方带的测试字段",
        messageAction: "<action>dotalist</action>",
        media: "YOUR_MEDIA_OBJECT_HERE"
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

**Comment by cinos1** [comment]
从目前看到的源代码应该是不行的，需要自己稍微修改下原生的部分

**Comment by jasonz1987** [comment]
#463
