### ISSUE TITLE
ionic3微信登陆问题

### ISSUE THREAD

**Issue by baixiaohuan** [xu-li/cordova-plugin-wechat#444]
使用这个插件的时候，吊起了微信获得了code，但是发送请求的时候却无法成功发起请求，总是执行到了错误代码里面，代码如下
![57f0263401f28e332c64e9a63c85c87](https://user-images.githubusercontent.com/23373759/41084989-3c8864f6-6a68-11e8-92b4-d9669bdc1308.png)
，手机上登录之后显示如下
![679693678696174669](https://user-images.githubusercontent.com/23373759/41085017-4e8e0656-6a68-11e8-9594-7f92933efc74.jpg)

**Comment by zhaoxu666** [comment]
获取access_token，openid，和获取用户信息  都是需要后台去发请求的。前端只能获取到code

**Comment by gdongy** [comment]
题主解决了吗，我在Android上市可以正常使用的，在iOS上会出现一样的问题

**Comment by kigh143** [comment]
hey, guys, have we found the solution to this, I read and it was a problem with the HTTP request and was related to the CORS.

**Comment by gdongy** [comment]
我最后的解决办法是，前端获取到之后把code给后台，由后台去请求，找到的说法是这个请求不支持在APP里做
