### ISSUE TITLE
安卓微信登录授权后，返回APP的时候，没有停留在之前APP的页面，而是重新打开App导致code无法获取到

### ISSUE THREAD

**Issue by tongjh2** [xu-li/cordova-plugin-wechat#447]
安卓微信登录授权后，返回APP的时候，没有停留在之前APP的页面，而是重新打开App导致code无法获取到，请问这个怎么解决

**Comment by ChaoHui123** [comment]
我也出现了这个问题,感觉像是app因为某个错误崩溃了

**Comment by ChaoHui123** [comment]
将
[https://github.com/xu-li/cordova-plugin-wechat/blob/ccf50820b5bc6c05f03ebdef0dc0a3801491896a/scripts/android-install.js#L42](android-install.js 42行) 改为下面代码
`var targetDir  = path.join(projectRoot, "platforms", "android", "app","src","main","java", packageName.replace(/\./g, path.sep), "wxapi");`

https://github.com/xu-li/cordova-plugin-wechat/issues/407
