### ISSUE TITLE
ionic3+cordova7.0.1+jdk1.8+gradle4.1=> :app:compileDebugJavaWithJavac 

### ISSUE THREAD

**Issue by dielangsea** [xu-li/cordova-plugin-wechat#449]
BUILD FAILED in 4s
(node:4448) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
D:\NewProject\GreenOlive3Project\GreenOlive3\page\mobile\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:281: ����: �޷����� Wechat�еķ��� getAppIdӦ�õ���������;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  ��Ҫ: û�в���
  �ҵ�: Activity
  ԭ��: ʵ�ʲ����б����ʽ�����б��Ȳ�ͬ
D:\NewProject\GreenOlive3Project\GreenOlive3\page\mobile\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:600: ����: �޷��Ӿ�̬�����������÷Ǿ�̬ ���� preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
                    ^
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
2 ������

FAILURE: Build failed with an exception.

**Comment by ALMONLU** [comment]
i have this problem,too.

**Comment by ALMONLU** [comment]
My config is ionic3+cordova8.0.0+jdk1.8+gradle4.1=> :app:compileDebugJavaWithJavac, so i think the reason for gradle's version.
