### ISSUE TITLE
cordova-plugin-wechatv2 新的插件名字是这个，我说为什么找不到- -

### ISSUE THREAD

**Issue by dielangsea** [xu-li/cordova-plugin-wechat#451]

**Comment by cinos1** [comment]
呃，这个插件是我在这个基础上改的，修改了这个版本里的分享图片bug，增加了小程序支持，支持android7的，小程序分享的代码我稍后提交下

**Comment by cinos1** [comment]
地址在https://github.com/guoanfamily/cordova-plugin-wechat 这里

**Comment by pedoc** [comment]
@cinos1 谢谢，后续测试一下

**Comment by JohnnyXuPeng** [comment]
大神 @cinos1 分享小程序好用了吗

**Comment by cinos1** [comment]
好用了，我们线上用的就是这个，具体使用看一下我插件中的js就好

**Comment by 54huige** [comment]
> 好用了，我们线上用的就是这个，具体使用看一下我插件中的js就好

感谢大神

**Comment by lyb12358** [comment]
@cinos1 大佬你用的android版本是多少啊？我试了下7.1.2~7.1.4都不行啊

**Comment by cinos1** [comment]
> @cinos1 大佬你用的android版本是多少啊？我试了下7.1.2~7.1.4都不行啊

我们用的是6.x，一直没升级到7

**Comment by lyb12358** [comment]
> > @cinos1 大佬你用的android版本是多少啊？我试了下7.1.2~7.1.4都不行啊
> 
> 我们用的是6.x，一直没升级到7

我也想试试6.4.0来着，直接报错了。。。是不是我哪里设置有问题？
`Unmet project requirements for latest version of cordova-plugin-wechatv2:
    cordova-android (6.4.0 in project, >=7.0.0 required)`

**Comment by cinos1** [comment]
@lyb12358 你最好直接在Android studio环境中编译一下看看，否则无法定位错误原因

**Comment by cinos1** [comment]
@lyb12358 抱歉，想起来了，因为当时偷懒，没有把小程序的key配置到配置文件中，需要手动在源码中修改，之前忘掉了

**Comment by kaygod** [comment]
@cinos1 我当前项目用的是7,可是不知道为什么安装了cordova-plugin-wechatv2,打包不成功,它报下面的错误
`BUILD FAILED in 18s
(node:11872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 1): Error: cmd: Command failed with exit code 1 Error output:
E:\xxx\platforms\android\app\src\main\java\xu\li\cordova\we
chat\Wechat.java:449: 
                    WXMiniProgramObject miniProgramObj = new WXMiniProgramObject
();
                    ^
          WXMiniProgramObject
  λ      Wechat`

**Comment by cinos1** [comment]
@kaygod 从描述看是小程序的对象创建失败，请直接用Androidstudio打开项目编译看看

**Comment by kaygod** [comment]
谢谢大佬的提示,我目前的项目是用ionic开发的,因为是前端,所以原生代码不知道如何改,但是项目只用到了微信分享和微信支付,小程序还用不到.所以我就把platforms/android/app/src/main/java/xu/li/cordova/wechat/Wechat.java 中的 448行 
case TYPE_WECHAT_SHARING_MINI : xxx  这个关于小程序的判断删除掉,然后打包就成功了!

**Comment by jasonz1987** [comment]
@cinos1 很棒的插件

官方插件也会继续维护，欢迎提供相关issue。
