### ISSUE TITLE
插件维护

### ISSUE THREAD

**Issue by jasonz1987** [xu-li/cordova-plugin-wechat#455]
刚看到作者的不能维护的公告，

有点儿遗憾，

很好的插件，我一直在用。

本人不才，

如果没人接手的话，

愿意申请成为维护者。

@xu-li

**Comment by jasonz1987** [comment]
收到了 谢谢～

**Comment by JayzeeHuang** [comment]
很好的插件，如果可以的话，我也献丑了

**Comment by chengrenz** [comment]
各位 谁能在这个插件加上 app 打开微信小程序的功能，非常感谢。
官方文档：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=21526646385rK1Bs&token=&lang=zh_CN

**Comment by xieweiqi1860** [comment]
很好的插件，如果可以的话，希望能贡献一份力量

**Comment by xieweiqi1860** [comment]
@xu-li @jasonz1987
