### ISSUE TITLE
2.4版本编译不通过

### ISSUE THREAD

**Issue by l-xue-yu** [xu-li/cordova-plugin-wechat#458]
应该还是老问题，同样的报错
BUILD FAILED in 15s
27 actionable tasks: 1 executed, 26 up-to-date
Error: cmd: Command failed with exit code 1 Error output:
D:\work\working\app\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.
java:281: ����: �޷����� Wechat�еķ��� getAppIdӦ�õ���������
;
            final String savedAppid = getAppId(cordova.getActivity());

ts代码
shareWeixin() {
    window.Wechat.share({
      message: {
        title: this.title,
        description:this.description,
        thumb: this.thumbnail,
      media:{
        type: window.Wechat.Type.WEBPAGE,
        webpageUrl: this.url
      }
      },
      scene: window.Wechat.Scene.SESSION   // share to SESSION好友
    }, () => {
      this.alert('分享成功');
    }, (reason) => {
      this.alert(reason, '分享失败')
    });
  }

还请大佬解决下。

**Comment by jasonz1987** [comment]
简单的看了一下，代码是有些问题。
你先把`Wechat.java` 第281行 改为

```
final String savedAppid = getSavedAppId(cordova.getActivity());
```

晚点儿，我自己再验证一下。

**Comment by l-xue-yu** [comment]
![menu saveimg savepath20180802162149](https://user-images.githubusercontent.com/42016055/43572023-01307cba-9671-11e8-8361-616120134546.jpg)

![menu saveimg savepath20180802162219](https://user-images.githubusercontent.com/42016055/43572055-1653b9ae-9671-11e8-999f-5ebfc6de1414.jpg)
![menu saveimg savepath20180802162650](https://user-images.githubusercontent.com/42016055/43572069-1de560f0-9671-11e8-9cb5-1da4f8141f81.jpg)

这两个bug改了，就能编译通过，但是，我测试微信分享的时候，分享返回app，app会闪退。
第一个bug是getAppId()这个方法（280行左右使用，方法定义在630行左右），不需要参数传入，你给了个参数，然后，返回的是个静态常量，我就把返回结果改成字符串，去掉传入的参数。
第二个bug是图片压缩方法（550行左右）的时候，ByteArrayOutputStream这个类，你没添加引用。加上就好了。

**Comment by tony2u** [comment]
appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
这行编译不过去，说是preferences没定义，getAppId静态函数修改了一下：
![image](https://user-images.githubusercontent.com/20885359/43682561-f52594a0-98aa-11e8-884d-4896c3eb84c9.png)

**Comment by l-xue-yu** [comment]
别用2.4，用2.0.这个就算编译通过，后面还有微信分享返回app，app重启的问题。

**Comment by pedoc** [comment]
@l-xue-yu 有能支持cordova android 7.x的版本吗。7.x版本微信登录也不会回调

**Comment by l-xue-yu** [comment]
> @l-xue-yu 有能支持cordova android 7.x的版本吗。7.x版本微信登录也不会回调

你试试2.0，或者之前的版本。

**Comment by pedoc** [comment]
@l-xue-yu 我换回android 6.4了。

**Comment by jasonz1987** [comment]
请大家尝试2.5.0版本
