### ISSUE TITLE
回调解决(支付宝同步)

### ISSUE THREAD

**Issue by mengkeys** [xu-li/cordova-plugin-wechat#462]
其实很简单 -> [SegmentFault链接](https://segmentfault.com/a/1190000016205577)

**Comment by JayzeeHuang** [comment]
闪一下显示“普通错误”  怎么办？

**Comment by mengkeys** [comment]
@JayzeeHuang 签名、参数不对吧，好好检查下，还有服务端接口返回的数据也有不对的可能

**Comment by jasonz1987** [comment]
@mengkeys 嗯 目前插件暂不支持promise写法。
