### ISSUE TITLE
授权登录报‘未知错误’

### ISSUE THREAD

**Issue by WhatDidTheFoxSay** [xu-li/cordova-plugin-wechat#465]
在进行微信授权登录的时候，第一次好像成功了，之后就一直报‘未知错误’，重新安装插件和在别的手机上测试都是这样。请问是咋回事啊？我使用的是2.0.0版本在安卓机上测试的

**Comment by duanwenjian** [comment]
请检查 微信开放平台 上面的android 应用签名 是不是“全小写，无冒号”
