### ISSUE TITLE
注意： 在cordova-android 7.x+下面，安装路径有问题。 

### ISSUE THREAD

**Issue by nevernet** [xu-li/cordova-plugin-wechat#467]
默认情况下， 安装到platforms/android/src目录。 
但是在cordova-android 7.x下面的真实路径路径是:
platforms/android/app/main/java/src/下面，所以安装后，需要人工复制三个Activity文件到这个目录。

**Comment by jasonz1987** [comment]
嗯 主要cordova7之后安卓项目路径发生了变化，现在已经修改了脚本代码，具体参见分支`develop-cordova7`
