### ISSUE TITLE
提示 linker command failed with exit code 1

### ISSUE THREAD

**Issue by wesleyxiao** [xu-li/cordova-plugin-wechat#468]
用ionic 3.9.2. 版本安装后 提示

xcode准备进行真机测试的时候 提示以下错误

linker command failed with exit code 1

**Comment by fakerLinXiao** [comment]
老哥，还没解决吗？是不是只能换插件了

**Comment by wesleyxiao** [comment]
> 老哥，还没解决吗？是不是只能换插件了


问题解决了， 如果你有发现类似问题，可以按照下面步骤来，但是问题是每一次在xcode查看都要重复下面的步骤。
ld: library not found for -lstdc++.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)


解决办法:  打开xcode ->打开项目-> General -> 拉到最下面 linked frameworks and libraries 

把libc++6这个给删除了，添加 libc++.1.1.tbd
就可以了

**Comment by fakerLinXiao** [comment]
> > 老哥，还没解决吗？是不是只能换插件了
> 
> 问题解决了， 如果你有发现类似问题，可以按照下面步骤来，但是问题是每一次在xcode查看都要重复下面的步骤。
> ld: library not found for -lstdc++.6
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 解决办法: 打开xcode ->打开项目-> General -> 拉到最下面 linked frameworks and libraries
> 
> 把libc++6这个给删除了，添加 libc++.1.1.tbd
> 就可以了

老哥，稳！ 这个方法解决了我的问题。

**Comment by jasonz1987** [comment]
线上的插件测试过没有该问题的。

可以发一下你们安装的插件版本和xcode版本吗？

微信sdk 依赖的`libstdc++.6.tbd`，请确保`linked frameworks and libraries`是否存在此库即可。

**Comment by 349989153** [comment]
@jasonz1987 请问确认得怎么样了，改吗

**Comment by SoundsAlive** [comment]
我把project document 中的project format，从默认的3.2compatible换到了更高的也好了。我这能解决，你们可以试试

**Comment by jasonz1987** [comment]
已更新
