### ISSUE TITLE
分享链接带图片问题

### ISSUE THREAD

**Issue by Luolei1992** [xu-li/cordova-plugin-wechat#469]
为什么微信分享给好友，android手机能正常显示缩略图，iphone手机就显示不出来，分享到朋友圈都不显示缩略图？？

 
![image](https://user-images.githubusercontent.com/23149226/48422671-21a15080-e79a-11e8-8947-d3bd45a5ec18.png)
![image](https://user-images.githubusercontent.com/23149226/48422728-3a116b00-e79a-11e8-9910-894dfa389ab0.png)

**Comment by elevenkey** [comment]
微信分享标题、描述里带“现金”、“红包”等文字的，可能会影响分享图。你可以修改一下标题或者描述试试。

**Comment by kk595076886** [comment]
我的是ios显示  android不显示你解决了没有昵

**Comment by 349989153** [comment]
@Luolei1992 图片地址是否https开头
