### ISSUE TITLE
安卓系统微信登陆没有转到微信页面

### ISSUE THREAD

**Issue by Mavlarn** [xu-li/cordova-plugin-wechat#48]
我用的魅族X4，系统是4.4，不管是自己的app，还是你提供的example的，微信登陆的时候，都进不去微信页面，就是在当前app的当前页闪一下，好像是试图打开别的应用，但是没有打开。

我不知道这是我的测试手机的问题，还是什么别的问题。帮我确认一下，谢谢。

**Comment by Mavlarn** [comment]
用adb logcat打出来的日志：
```
D/Cordova.Plugin.Wechat(24912): sendAuthRequest is called.
D/Cordova.Plugin.Wechat(11095): com.tencent.mm.sdk.modelmsg.SendMessageToWX$Resp@42b94700
```

**Comment by xu-li** [comment]
@Mavlarn 是不是签名不对？我的那个example的签名应该是对的，你是怎么安装的？

签名问题，请参见[Signature的生成方法](https://open.weixin.qq.com/zh_CN/htmledition/res/assets/signature_method.doc).

**Comment by Jeff-Tian** [comment]
我自己的应用，之前也碰到过这个问题。但是用了正式的签名打包后就可以了，估计你也是签名问题。

要排除是不是手机问题，可以安装 https://play.google.com/store/apps/details?id=com.diankeda.huaquanquan 这个应用，并尝试微信登录（这个应用的微信登录就是用这个插件做的）。我用各种安卓手机都测试过没有问题。

这个插件非常好用！

**Comment by xu-li** [comment]
多谢@Jeff-Tian提供的信息。
