### ISSUE TITLE
参数格式错误

### ISSUE THREAD

**Issue by liliangali** [xu-li/cordova-plugin-wechat#483]
你好，我用你最新版的2.5.0   andorid微信支付的时候提示 参数格式错误，我用以前的2.1.0的版本就可以正常支付，代码是一模一样的，看起来是新版本有bug，期望大神能在合适的时间修复此问题

**Comment by jasonz1987** [comment]
@liliangali 能具体贴出错误的日志和截图，以及调用的方法吗?

**Comment by SeaSky0606** [comment]
![image](https://user-images.githubusercontent.com/12839409/50747614-d83c2180-126f-11e9-8f13-18348e604083.png)

![image](https://user-images.githubusercontent.com/12839409/50747652-002b8500-1270-11e9-95f7-8cb2603e831f.png)
params的参数值到底是哪一种格式，为这么这里的demo没有和wechat.js的保持一致？

**Comment by qichangjun** [comment]
{noncestr: "1tC1TG9Y3QZ2GwXTwSlYkBjmVg7P5NM6"
partnerid: "1520607751"
prepayid: "wx1815102629146866776a434a3386489109"
sign: "562CC4BEB4F6B3C270F28E7161D68B57"
timestamp: "1547795426"}

这是我的params,同样报参数格式错误，是什么问题?

**Comment by 349989153** [comment]
同意@qichangjun，params里需要加“appid”字段。
```js
var params = {
    appid: '',// your appid
    partnerid: '10000100', // merchant id
    prepayid: 'wx201411101639507cbf6ffd8b0779950874', // prepay id
    noncestr: '1add1a30ac87aa2db72f57a2375d8fec', // nonce
    timestamp: '1439531364', // timestamp
    sign: '0CB01533B8C1EF103065174F50BCA001', // signed string
};
```

**Comment by jasonz1987** [comment]
hi,all,经过验证 确实是问题，下个版本会修复。
