### ISSUE TITLE
升级xcode10之后微信登录报这个错误，用xcode9是打包是可以正常登录的

### ISSUE THREAD

**Issue by liliangali** [xu-li/cordova-plugin-wechat#494]
![image](https://user-images.githubusercontent.com/18063081/53153759-0f824a00-35f4-11e9-811e-e4bbd1260dfe.png)
![image](https://user-images.githubusercontent.com/18063081/53153815-33de2680-35f4-11e9-8ab9-cc04e4fc4e00.png)

**Comment by liliangali** [comment]
![image](https://user-images.githubusercontent.com/18063081/53212054-67659300-367e-11e9-9d49-b7fc5862b0c1.png)

**Comment by duanwenjian** [comment]
检查打包的 bundle ID 和微信平台上面填写的信息是否一致
