### ISSUE TITLE
图片不能分享了，有问题

### ISSUE THREAD

**Issue by match08** [xu-li/cordova-plugin-wechat#50]
你好，这个插件图片分享有问题。分享不了。文本可以

**Comment by AaronChen118** [comment]
同样的问题，link和text可以分享，但是video等不行，run example的时候闪退

**Comment by match08** [comment]
我看了下里面的代码，是video没实现。

**Comment by AaronChen118** [comment]
那个文件？@match08,看看能不能自己实现了

**Comment by match08** [comment]
你看源码  原生的部分

**Comment by xu-li** [comment]
@match08 请问用的哪个版本？什么平台？代码是怎么样的？

@AaronChen118 android暂时只有文本，图片和链接。

**Comment by xudao520** [comment]
插件好像分享链接不能带缩略图哦，貌似作者没有写图片缩略，微信分享链接只能允许32k的图片过去

**Comment by xudao520** [comment]
protected Bitmap resizeBitmap(Bitmap bitmap, int w, int h) {
    	if(null == bitmap) {
    		return null;
    	}
    	
    	Bitmap BitmapOrg = bitmap;  
        int width = BitmapOrg.getWidth();  
        int height = BitmapOrg.getHeight();  
        int newWidth = w;  
        int newHeight = h;  
 
        float scaleWidth = ((float) newWidth) / width;  
        float scaleHeight = ((float) newHeight) / height;  
 
        Matrix matrix = new Matrix();  
        matrix.postScale(scaleWidth, scaleHeight);  
        // if you want to rotate the Bitmap   
        // matrix.postRotate(45);   
        Bitmap resizeBitmap = Bitmap.createBitmap(BitmapOrg, 0, 0, width,  
                        height, matrix, true);    
        
        bitmap.recycle();
        
        return resizeBitmap;
    }
加上这个就可以压缩图片引入import android.graphics.Matrix;望作者采纳

**Comment by xu-li** [comment]
@xudao520 原来插件的想法是尽量做的和官方SDK一样，也就是说，仅仅作为一个Javascript调用SDK的中转。最近比较忙，回头我测试一下你的代码，看看吧。

**Comment by xu-li** [comment]
终于有点时间看图片的问题了，现在新的版本加入了压缩的代码。

**Comment by xudao520** [comment]
可以出一系列的社会化分享
