### ISSUE TITLE
ionic 微信授权登陆能正常唤起，但是点击确认后app闪退

### ISSUE THREAD

**Issue by JohnnyXuPeng** [xu-li/cordova-plugin-wechat#507]
ionic 打包环境:
cordova 8.0.0
android 7.0.0
cordova-plugin-wechat 2.6.0 && 2.7.1 

问题描述：
安装最新的插件后，可以正常唤起微信授权登陆页面，但是点击确认后app直接崩溃了，也没有报错，也没走到成功分支里，求赐教，先谢谢啦

var scope = "snsapi_userinfo",
      state = "_" + (+new Date());
    Wechat.auth(scope, state, function (response) {
      // you may use response.code to get the access token.
      alert(JSON.stringify(response));
      alert(response.code);
      })
    }, function (reason) {
      alert("Failed: " + reason);
    });

**Comment by jasonz1987** [comment]
@JohnnyXuPeng  检查一下项目目录/platforms/android/src/你的包名/ 路径下是否有wxapi文件，并且该目录下有这个3个文件

![image](https://user-images.githubusercontent.com/7090036/54516878-2faaec00-499b-11e9-8d62-983f4e058fb4.png)

并且这3个文件的package 为你的包名

![image](https://user-images.githubusercontent.com/7090036/54516921-510bd800-499b-11e9-93b6-353f7c805dfa.png)

**Comment by JohnnyXuPeng** [comment]
@jasonz1987 感谢大神这么快就回复。已经检查过三个package的包名是没有问题的，但是路径跟你给的不太一样，我项目的目录是/platforms/android/**app**/src，不知道是不是这个影响的

![image](https://user-images.githubusercontent.com/11940800/54576658-0db17800-4a34-11e9-8aa7-5498479049a2.png)
![image](https://user-images.githubusercontent.com/11940800/54576668-1609b300-4a34-11e9-9611-04f26aa254da.png)

另外，我们试了2.1.0的那个插件（手动改了不支持android7.0+的那个路径），居然可以正常工作...

**Comment by jasonz1987** [comment]
@JohnnyXuPeng 嗯 那应该还是插件安装有问题，可以手动拷贝文件，或者删除插件重新安装试试。
