### ISSUE TITLE
你好，我使用你的控件总是提示 授权失败

### ISSUE THREAD

**Issue by wat2012** [xu-li/cordova-plugin-wechat#51]
我直接使用的是cordova，然后总是授权失败。
我在plugin add的时候添加了appid，然后在config添加appid，
然后build android
实际运行的时候提示授权失败。
我尝试更换成官网的libammsdk.jar
发现好多的类引用不匹配，能帮我解决一下吗

**Comment by AaronChen118** [comment]
你build的时候生成app 签名，报名都正确吗？

**Comment by wat2012** [comment]
1 cordova platform rm android
2 cordova plugin add https://github.com/xu-li/cordova-plugin-wechat--variable wechatappid=APPID
3 cordova platform add android
4 cordova build android
5 使用adt eclipse导出，使用release的keystore进行导出的apk
直接在我的项目使用
https://github.com/xu-li/cordova-plugin-wechat#share-link
Wechat.share({
        		message : {
        			media : {
        				type : Wechat.Type.LINK,
        				webpageUrl : "http://sj.zouqi.mobi/zouqi/html/activity/share.html?id="+activityId
        			}
        		},
        		scene : Wechat.Scene.TIMELINE // share to Timeline
        	}, function () {
        		alert("Success");
        	}, function (reason) {
        		alert("Failed: " + reason);
        	});

前面再没有项目中再没有Wechat的调用
这样的步骤，正确吗？

**Comment by xu-li** [comment]
@wat2012，你申请的微信APP里面有没有设置签名？请查阅[签名的生成方法](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。

**Comment by wat2012** [comment]
设置签名了，你什么时间有空，帮我远程一下好吗
Q 249895015
email cxh01987@163.com

**Comment by xu-li** [comment]
@wat2012 不好意思，最近有点忙，请问你试过我的那个DEMO么？

**Comment by litingjun2015** [comment]
@xu-li ，请问包名要填 xu.li.cordova.wechat 吗？

**Comment by xu-li** [comment]
如果是Android，包名和签名绑定的。也就是说你运行我的demo，应该要用我的demo的包名。

**Comment by litingjun2015** [comment]
是Android，那应该是 xu.li.test.cordova.plugin.wechat 对吧？

**Comment by xu-li** [comment]
对，xu.li.test.cordova.plugin.wechat。

题外话，如果你clone下来，应该是不需要你改东西的。

**Comment by litingjun2015** [comment]
你的意思是 wechatappid=wx4a525790c75c494f 也用你的吗?

**Comment by xu-li** [comment]
是的。

**Comment by litingjun2015** [comment]
build的时候曾出现红色的告警：
:preDexDebugwarning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.b.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

执行“发送Text消息给微信”时报“Failed：未知错误”
