### ISSUE TITLE
[cordova-android]Wechat.auth 拉起微信授权成功后，返回到app主页面而不是调用授权的页面，也没有任何回调

### ISSUE THREAD

**Issue by lideshengai** [xu-li/cordova-plugin-wechat#513]
Wechat.auth(
          scope,
          function(response) {
            alert("begin callback!")
              vm.response = response;
            // you may use response.code to get the access token.
            var message = JSON.stringify(response);
            var code = response.code;
            alert("回调message:"+message);
          },
          function(reason) {
            alert("Failed: " + reason);
          }
        );

**Comment by lideshengai** [comment]
不知道是不是因为vue路由使用hash的问题

**Comment by duanwenjian** [comment]
正常情况下，无论用户选择授权或者取消，都会回调error 或者 success 函数。这两个函数没有任何调用提示么？

**Comment by lideshengai** [comment]
@duanwenjian 没有任何提示，app直接到首页了，我这边有试过成功过，如果成功会回到调用的页面去，并显示回调结果。最奇怪的是，同一个成功的项目我只是添加删除平台，然后再打包，结果又是没有任何提示，app直接回到首页，你能帮我看下嘛，我把模板发给你

**Comment by lideshengai** [comment]
@duanwenjian 问题确定了，只要移出平台然后重新加入平台后，构建的apk就出现授权成功后，直接返回app首页，而且没有回调函数

**Comment by lideshengai** [comment]
哇，真心服了，除了第一次建项目加入 平台，会将插件的java源码打入app中外，后面只要进行了重新移出添加平台后，java源码都不在了，我只有手动加入到app中，插件才能正常使用
