### ISSUE TITLE
cordova Android 7.1.4 唤起微信后闪退

### ISSUE THREAD

**Issue by blade-feng-wang** [xu-li/cordova-plugin-wechat#517]
安卓上的问题，cordova platform android@6.4.0能用，不指定版本号自动加载最新的7.1.4会闪退，微信唤起了，点击确认登陆后一会儿就闪退了。

**Comment by XYQgithup** [comment]
我是用了6.4.0版本的安卓平台，但是还是会出现闪退的问题

**Comment by jasonz1987** [comment]
重新安装过插件吗？

**Comment by maxaio** [comment]
请问这个问题有解决吗?

**Comment by jasonz1987** [comment]
@maxaio  @blade-feng-wang  @XYQgithup 请使用 2.8.0版本
