### ISSUE TITLE
升级到cordova9.0后引用该插件编译报错

### ISSUE THREAD

**Issue by l1044635791** [xu-li/cordova-plugin-wechat#519]
Failed to restore plugin "cordova-plugin-wechat" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running subprocess cordova.

**Comment by l1044635791** [comment]
问题描述：https://stackoverflow.com/questions/55304065/cordova-error-using-requirecordovamodule-to-load-non-cordova-module-q-is-no

**Comment by jasonz1987** [comment]
增加了cordova9 支持，可以测试一下 #521

**Comment by l1044635791** [comment]
好的，感谢

**Comment by zhanglongyu** [comment]
这个修复什么时候能发布到npm？

**Comment by gougou168** [comment]
cordova9.0在ios上面没有问题  在android上面支付完成后返回app直接奔溃

**Comment by jasonz1987** [comment]
@zhanglongyu  这周应该就会发布

**Comment by jasonz1987** [comment]
@gougou168  如果是app奔溃问题 应该是插件安装的问题

**Comment by jasonz1987** [comment]
2.8.0 已发布 #529
