### ISSUE TITLE
Sharing local images fails

### ISSUE THREAD

**Issue by objectkuan** [xu-li/cordova-plugin-wechat#52]
Hi @xu-li ,

I try sharing an local image with this plugin and my app crashes.

Here is a screenshot of my Xcode:

![error](https://cloud.githubusercontent.com/assets/2225492/9192636/5a8ef2b8-403f-11e5-8ca4-24cd9f67b81b.jpg)

According to [this discussion](http://stackoverflow.com/questions/26410420/nsstring-containsstring-crashes), it seems an iOS version related issue. And I suggest that 

`    }else if([url containsString:@"temp:"]){`

should be modified to 

`    }else if([url rangeOfString:@"temp:"].length != 0){`

and this works on my iOS 7 phone.

**Comment by xu-li** [comment]
@objectkuan Thanks, I will take a look and merge that in the next release.

BTW, I would not recommend you to use this as in android, this is not supported.
