### ISSUE TITLE
微信登陆点击确认登陆后闪退

### ISSUE THREAD

**Issue by wenlz123** [xu-li/cordova-plugin-wechat#534]
专家们，我刚开始接触cordova和wechat。最近刚装了cordova android 8.0.0. 之后装了cordova-plugin-wechat 2.8.0。签名最开始没弄对，改对之后，点击微信登陆，微信登陆能成功调出，但是点确认登陆的时候整个app闪退了。我试了VIVO Z3 Android 8.1.0 和 OPPO A5 Android 8.1，都有这个问题。请问这个问题怎么解决，或者可以告诉我怎么调试。谢谢了。
<plugin name="cordova-plugin-wechat" spec="^2.8.0">
        <variable name="WECHATAPPID" value="wx61d83e46aa93c77b" />
    </plugin>

**Comment by duanwenjian** [comment]
这个比较麻烦，可以加群详细咨询

**Comment by wenlz123** [comment]
谢谢各位的支持，问题解决了。不知道为什么，三个微信相关的Java文件打包的时候被删除了。加回来就好了。

**Comment by wyljya** [comment]
我也遇到这个问题了，不知道怎么解决，点击确认登录后，重新打开了app,并没有进入回调方法中，请大神们多多帮忙 啊。
cordova 8.1.2
cordova-plugin-wechat 2.0.0
