### ISSUE TITLE
请问一下安装插件时wechatappid的作用是什么？

### ISSUE THREAD

**Issue by hujiakai** [xu-li/cordova-plugin-wechat#541]
cordova plugin add cordova-plugin-wechat  --variable wechatappid=YOUR_WECHAT_APPID
请问一下安装插件时wechatappid的作用是什么？ 如果不同的客户需要付款到不同的微信账户中，则会有多个APPID，这时候安装插件时wechatappid改怎么处理？？？
谢谢！！！

**Comment by jasonz1987** [comment]
暂不支持多appID
