### ISSUE TITLE
为什么分享带图片文字时，只有图片能够显示出来，而文字丢掉了？

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-li/cordova-plugin-wechat#56]
代码：

···
WechatApp.share({
                    message: {
                        title: 'title',
                        description: 'description',
                        thumb: '',
                        mediaTagName: "Jiy",
                        messageExt: "叽歪",
                        messageAction: "<action>dotalist</action>",
                        media: {
                            type: Wechat.Type.IMAGE,
                            image: 'https://avatars0.githubusercontent.com/u/171665?v=3&s=48'
                        }
                    },
                    scene: Wechat.Scene.TIMELINE   // share to Timeline
                }, 
···

![1 pic](https://cloud.githubusercontent.com/assets/3367820/9299352/9c2faef8-44ed-11e5-8a77-c68645ad4b03.jpg)

**Comment by xu-li** [comment]
@Jeff-Tian 是这样的，分享图片，只有图片。
