### ISSUE TITLE
会考虑把iOS的微信sdk换成1.8.6.1的么？iOS到13，烦

### ISSUE THREAD

**Issue by androidwzl** [xu-li/cordova-plugin-wechat#564]
会考虑把iOS的微信sdk换成1.8.6.1的么？iOS到13，烦

**Comment by androidwzl** [comment]
你那边有iOS WeChatOpensdk1.8.0的不含微信支付的包么？跪求，iOS不能接含支付的sdk

**Comment by jasonz1987** [comment]
@androidwzl  官网上下载不到吗？

**Comment by androidwzl** [comment]
官网上没找到，最后在pod源找到了历史版本

**Comment by 5thgfka** [comment]
https://developers.weixin.qq.com/doc/oplatform/Downloads/iOS_Resource.html

**Comment by jasonz1987** [comment]
develop 已更新到3.0.0 支持微信最新SDK @androidwzl

**Comment by lingdu0001** [comment]
> develop 已更新到3.0.0 支持微信最新SDK @androidwzl

请问啥时候release 正式版到npmjs啊？

**Comment by jasonz1987** [comment]
这周吧，竟然没人反馈BUG~

**Comment by lid1987** [comment]
> 这周吧，竟然没人反馈BUG~

大佬，发正式版本不？

**Comment by jasonz1987** [comment]
@lingdu0001 @lid1987  已发布。
