### ISSUE TITLE
微信认证不能没有callback

### ISSUE THREAD

**Issue by harryhan1989** [xu-li/cordova-plugin-wechat#57]

**Comment by xu-li** [comment]
@harryhan1989 什么意思？

**Comment by harryhan1989** [comment]
我的app的appid和key都在微信开发者平台申请好了，但是执行下面代码想回掉获得code时，始终没有回掉：                Wechat.auth(scope, function (response) {
                    alert(JSON.stringify(response));
                    window.top.location.hash = '#home';
                }, function (reason) {
                    alert("Failed: " + reason);
                    window.top.location.hash = '#home';
                });

**Comment by harryhan1989** [comment]
解决了，是因为我在申请完微信开发者账号后，忘了把plugin里面的以前的appid替换掉，删除重装，并输入正确appid就解决了
