### ISSUE TITLE
Ios 无法识别微信是否安装

### ISSUE THREAD

**Issue by jwan3453** [xu-li/cordova-plugin-wechat#570]
用capacitor 安装插件，但是在cap sync的时候一只提示要在plist 添加配置，实际上已经添加了, 微信app id 也加了。
![WechatIMG94](https://user-images.githubusercontent.com/4488805/69045196-5725ed00-0a31-11ea-8d48-3c908e8f7519.jpeg)
运行没有报错， 但是isInstalled  都是返回没有安装。
安卓上面直接报错了， Failed: Attempt to invoke interface method 'boolean com.tencent.mm.opensdk.p[enapi.IWXAPI.isWXAppInstalled()' on a null object reference.

**Comment by jwan3453** [comment]
这个插件， 还有人在维护吗？

**Comment by jasonz1987** [comment]
capacitor 应该支持cordova的 晚点儿我试试~

**Comment by CodeforChao** [comment]
IOS现在无法检测是否安装微信，android是好用的，另外这个plugin支持ipad吗

**Comment by CodeforChao** [comment]
> IOS现在无法检测是否安装微信，android是好用的，另外这个plugin支持ipad吗

好用了 ipad也支持
