### ISSUE TITLE
苹果要弃用UiWebview的API了，可以更新一下插件吗

### ISSUE THREAD

**Issue by leeewh** [xu-li/cordova-plugin-wechat#576]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information

用了这个插件的话就会收到这样的邮件，移除插件就不会被提醒。

**Comment by wing505** [comment]
我也遇到同样的问题，移除此插件后就可以到App Store了。

**Comment by leeewh** [comment]
> 我也遇到同样的问题，移除此插件后就可以到App Store了。

其实更新到3.0.0就好了

**Comment by wing505** [comment]
> > 我也遇到同样的问题，移除此插件后就可以到App Store了。
> 
> 其实更新到3.0.0就好了

感谢你的答复，我试试升级到3.0.0版本。非常感谢。

**Comment by wing505** [comment]
> > 我也遇到同样的问题，移除此插件后就可以到App Store了。
> 
> 其实更新到3.0.0就好了

已测试到，使用3.0.0版本正常。
