### ISSUE TITLE
登录、支付正常，分享没反应

### ISSUE THREAD

**Issue by zhenfuxu** [xu-li/cordova-plugin-wechat#587]
能够通过微信登录和支付，但是分享没有报错，也不弹出和跳转到微信，请问什么问题？我看有人说跟写权限有关系。

**Comment by helloJincheng** [comment]
+1

**Comment by ZhongYueHui** [comment]
ios也支付正常吗

**Comment by zhenfuxu** [comment]
> ios也支付正常吗

没试过，iOS 没有用微信支付，用的内购，今天换成2.9.0 版本，登录是可以的，但是分享依然是没有反应。

**Comment by leoshuaige** [comment]
+1 支付，登录正常，分享没用任何反应

**Comment by ZhongYueHui** [comment]
我的一切正常 支付 分享

**Comment by zhenfuxu** [comment]
我的也解决了 用 declare var Wechat:any; 不用ionic 封装的就好了

**Comment by zhenfuxu** [comment]
用 declare var Wechat:any; 不用ionic 封装的就好了
