### ISSUE TITLE
iOS Xcode linker errors after updating to latest we chat plugin

### ISSUE THREAD

**Issue by acylum** [xu-li/cordova-plugin-wechat#59]
I recently tried to update the we chat plugin by doing 
cordova plugin rm xu.li.cordova.wechat
then
cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable wechatappid=wx0........

Now, when I try to build the project, I get this:

Undefined symbols for architecture armv7:
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[CDVReachability connectionRequired] in CDVReachability.o
      -[CDVReachability currentReachabilityStatus] in CDVReachability.o
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[CDVReachability reachabilityWithAddress:] in CDVReachability.o
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[CDVReachability reachabilityWithHostName:] in CDVReachability.o
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[CDVReachability startNotifier] in CDVReachability.o
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[CDVReachability stopNotifier] in CDVReachability.o
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[CDVReachability startNotifier] in CDVReachability.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xu-li** [comment]
@acylum I'm afraid **CDVReachability** is in org.apache.cordova.network-information, you can reinstall that plugin, or [add the framework manually](http://stackoverflow.com/questions/24411829/cordova-build-results-in-error-on-ios-after-installing-org-apache-cordova-networ).

**Comment by acylum** [comment]
Ok - I added it manually and solved the build issue, but now the app can't find the we chat plugin

"CDVPlugin class CDVWechat (pluginName: wechat) does not exist."

I traced it through - 
CDVVIewController.m
it does show up in .pluginsMap
919  NSString* className = [self.pluginsMap objectForKey:[pluginName lowercaseString]];

but when it tries to retrieve the classname here
928   obj = [[NSClassFromString(className)alloc] initWithWebView:webView];

it receives a "null"

So, How do I manually get Cordova to recognize the wechat plugin class?

**Comment by xu-li** [comment]
The easiest solution would be (if you haven't modified anything inside platform/ios/):
1. remove ios platform, e.g. ```cordova platform rm ios```
2. add it back, e.g. ```cordova platform add ios```

If you do have made changes inside platform/ios:
* Make sure CDVWechat.h and CDVWechat.m source file exist
* Make sure CDVWechat.m exist in *Build Phases* -> *Compile Sources*.

**Comment by acylum** [comment]
Solved - I just removed CDVWechat.h and m and then re added to fix
