### ISSUE TITLE
当更新了/ cordova-plugin-wechat 3.0.0 版本，并且IOS配置成功Universal Links 之后，cordova-plugin-customurlscheme 插件不工作了，我该怎么办？

### ISSUE THREAD

**Issue by super-maoMao** [xu-li/cordova-plugin-wechat#591]

**Comment by super-maoMao** [comment]
此插件利用 (window as any).handleOpenURL = (url: string) => {} 函数获取url
安卓可以成功获取到url，并且跳转成功，但是IOS获取不到这个url了，我不知道该怎么处理

**Comment by guanyuan** [comment]
我也遇到这样的问题，请问是怎么解决的呢？

**Comment by guanyuan** [comment]
> _No description provided._

我也遇到这样的问题，请问是怎么解决的呢？
