### ISSUE TITLE
最新版3.0.0的ios分享失败,没有报错,打开不了微信,

### ISSUE THREAD

**Issue by Benamin** [xu-li/cordova-plugin-wechat#599]
之前由于`UIWebview`不能使用升级到了最新版本 3.0.0,但是发现ios不能分享,
安卓的是正常的, 把版本降到2.8.0之后ios的分享正常,
看了文档,发现 可能是 `Universal Link `的配置问题 ,但是这个该怎么配置啊....
求救!!!
插件版本: 3.0.0
ionic3

**Comment by Riuhou** [comment]
在app文件夹下的config.xml中添加：  
```
  <preference name="WECHATAPPID" value="wx app id" />
  <preference name="UNIVERSALLINK" value="https://xxx.com/" />
```

另外问一下你分享正常，微信登陆能正常拿到返回数据吗？

**Comment by Benamin** [comment]
> 在app文件夹下的config.xml中添加：
> 
> ```
>   <preference name="WECHATAPPID" value="wx app id" />
>   <preference name="UNIVERSALLINK" value="https://xxx.com/" />
> ```
> 
> 另外问一下你分享正常，微信登陆能正常拿到返回数据吗？

没试过登陆，仅用的分享，所以我也不太清楚

**Comment by Benamin** [comment]
填一下坑，
解决了，`Universal Link `，填个任意地址就行了
