### ISSUE TITLE
cordova-plugin-wechat 问题

### ISSUE THREAD

**Issue by guzenyin** [xu-li/cordova-plugin-wechat#60]
@xu-li  ，你好。
我在ionic下面使用你的控件，发现几个问题：
1.运行你的demo时，android下面，发送朋友圈消息时总是提示“授权失败”。
2.运行你的demo时,ios 模拟器下面，"微信授权登录" 提示参数错误。

请问以上2个问题有好的解决办法么？ 不甚感激！
同时我对Wechat.auth 方法中的 “use response.code to get the access token.” 不是特别理解，能烦请解释一下么?

**Comment by xu-li** [comment]
1. 授权失败，我不是很清楚，可能是审核的问题？和第二个问题一样。
2. 参数失败是因为我的demo应用没有通过审核。
3. 可以参见[网页授权获取用户基本信息](http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html)，特别是*第二步：通过code换取网页授权access_token*.

**Comment by guzenyin** [comment]
非常感谢
