### ISSUE TITLE
wepay - using payment_demo.php - no return response

### ISSUE THREAD

**Issue by acylum** [xu-li/cordova-plugin-wechat#61]
I've been trying to use the new wepay function in the latest plugin.  At first, I received an error from the plugin.  Then I traced the problem to the returned prepayid="" from the payment_demo.php.

Looking further, I found that the $result = curl_exec($ch); in payment_demo.php is returning empty objects:  i.e.  {"return_code":{},"return_msg":{}};

So, I don't even get an error to figure out what is the issue.
In the payment_demo.php,  I did change these to my app info:
define("APP_ID",  WEIXIN_APPID);
define("MCH_ID",  WEIXIN_BIZID);
define("APP_KEY", WEIXIN_APPSECRET);

So, I'm not sure now what is the issue in the payment_demo.php

**Comment by acylum** [comment]
So, I was able to get an error - <return_msg><![CDATA[支付权限检查失败]]></return_msg>

So, it seems like a permission error - but how do I correct this?

**Comment by acylum** [comment]
Changing the trade_type to "JSAPI"    (I'm using the public account)  now gives me this as an error
JSAPI支付必须传openid.   So, now, what do I need to do to correct this?

**Comment by xu-li** [comment]
@acylum You don't have to change the trade_type.

Maybe [this](https://cnodejs.org/topic/5510f0eed792542a2978993f) will help?
