### ISSUE TITLE
android分享导致程序闪退

### ISSUE THREAD

**Issue by huip** [xu-li/cordova-plugin-wechat#63]
微信分享时，分享成功后，返回到应用
android版本应用崩溃。
ios版本还停留在微信上。

**Comment by xu-li** [comment]
@huip 

android应用崩溃的错误是？
ios版本的Url Type没设置把？参见FAQ。

**Comment by ice-cream-zbb** [comment]
这问题解决了吗？报错  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.etf.hxzt.wxapi.WXEntryActivity"

**Comment by jasonz1987** [comment]
@ice-cream-zbb  请使用最新版本插件。
