### ISSUE TITLE
分享成功，但是返回app 不成功

### ISSUE THREAD

**Issue by ljie** [xu-li/cordova-plugin-wechat#65]
用android 手机将您的demo跑起来了，现在可以分享到我的好友，但会返回app的时候会提示  [demo已经停止运行]  是什么原因呢

**Comment by xu-li** [comment]
@ljie 错误日志里面写的是什么？

**Comment by wukongcxy** [comment]
我也遇到了相同的问题，原因是返回的app名字，可以修改下plugins下的android.json中PACKAGE_NAME和根目录的config.xml试试
