### ISSUE TITLE
请问你的插件是否提供“微信登录接入”功能

### ISSUE THREAD

**Issue by litingjun2015** [xu-li/cordova-plugin-wechat#66]
你的Demo在我本地运行还有点问题，想请问一下你插件里“微信授权登录“是否就是
http://mp.weixin.qq.com/s?__biz=MjM5NDAxMDg4MA==&mid=208833692&idx=1&sn=daa41a5b34ce7ffeb48985964e613941&scene=0#rd
这个链接里描述的“微信登录接入”功能？

谢谢！

**Comment by xu-li** [comment]
@litingjun2015 , 具体问题是什么？ 是的，那个链接说的很详细。

**Comment by litingjun2015** [comment]
Demo的主界面能够出来，但是点击其中“微信授权登录”没有反应。点击“发送Text消息给微信”等按钮会跳出“请稍候……”马上又回到主界面了。

另外你插件里“微信授权登录“是否就是这个链接里描述的“微信登录接入”功能？

**Comment by xu-li** [comment]
Demo的问题，你在那个项目开个issue吧。请说明你的操作过程，比如clone，build，之类的。

"微信授权登录“ **就是** 那个链接里描述的“微信登录接入”功能。

**Comment by litingjun2015** [comment]
多谢！
