### ISSUE TITLE
微信分享

### ISSUE THREAD

**Issue by phym** [xu-li/cordova-plugin-wechat#68]
您好，我想分享一个链接代码如下：
function share(){
		Wechat.share({
		    message: {
		        media: {
		            type: Wechat.Type.LINK,
		            webpageUrl: "www.baidu.com"
		        }
		    },
		    scene: Wechat.Scene.TIMELINE   // share to Timeline
		}, function () {
		    alert("Success");
		}, function (reason) {
		    alert("Failed: " + reason);
		});
	}
当我触发事件的时候在 logCat中报这样的错误
![image](https://cloud.githubusercontent.com/assets/9352452/9598606/93790240-50bf-11e5-9ba9-c09caedf44a1.png)
请问为什么？

**Comment by xu-li** [comment]
需要加个title。比如:

```Javascript
Wechat.share({
    message: {
        title: "Hi, there",
        description: "This is description.",
        thumb: "www/img/thumbnail.png",
        mediaTagName: "TEST-TAG-001",
        messageExt: "这是第三方带的测试字段",
        messageAction: "<action>dotalist</action>",
        media: {
            type: Wechat.Type.LINK,
            webpageUrl: "http://www.baidu.com"
        }
    },
    scene: Wechat.Scene.TIMELINE   // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});
```

请看[demo](https://github.com/xu-li/cordova-plugin-wechat-example)。

**Comment by phym** [comment]
好的，谢谢！
