### ISSUE TITLE
微信分享问题

### ISSUE THREAD

**Issue by phym** [xu-li/cordova-plugin-wechat#69]
您好：我用的是标签触发事件，事件调用
       Wechat.share({
		    message: {
		    	title: "Hi, there",
		    	description: "This is description.",
				mediaTagName: "TEST-TAG-001",
				thumb: "www/img/cancel.png",
				messageExt: "测试",
				messageAction: "<action>dotalist</action>",
		        media: {
		            type: Wechat.Type.LINK,
		            webpageUrl: "www.baidu.com"
		        }
		    },
		    scene: Wechat.Scene.TIMELINE   // share to Timeline
		}, function () {
		    alert("Success");
		}, function (reason) {
		    alert("Failed: " + reason);
		});
logCat中没有错误，但是在跳转微信的时候时只是 闪一下屏 然后就 跳到 alert("Failed: " + reason); 请问这是什么问题，我是新手麻烦了！

**Comment by phym** [comment]
![image](https://cloud.githubusercontent.com/assets/9352452/9622076/5390669e-5161-11e5-92b1-4c5604c02cb4.png)
您好，这是 logCat日志的输出

**Comment by xu-li** [comment]
@phym 请问你试过[demo](https://github.com/xu-li/cordova-plugin-wechat-example)了么？

闪退的话，应该是你的设置问题。比如APPID和签名等。

**Comment by phym** [comment]
您好，我没有用过demo，因为项目比较急，然后我APPID是相同的但是  签名 是在那边设置啊？

**Comment by xu-li** [comment]
错误提示是什么？你也没说。LogCat的截图也只有一半。我很难判断。

签名可以参见[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。

**Comment by phym** [comment]
能分享了，我是一个菜鸟，楼主能这样帮助太感谢了，然后再次感谢楼主提供的插件！

**Comment by xu-li** [comment]
没事，能用了就好。
