### ISSUE TITLE
Wechat.share error: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by jianbo** [xu-li/cordova-plugin-wechat#7]
Wechat.share cause the app to crash:

2015-01-02 19:52:57.138 App[4912:6207] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x15549740
2015-01-02 19:52:57.143 App[4912:6207] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x15549740'
*** First throw call stack:
(0x3023ef4b 0x3a67f6af 0x302428e7 0x302411cb 0x301904d8 0xb75dd 0xb6adb 0x3ab62d1b 0x3ab69d71 0x3ab69f59 0x3aca4dbf 0x3aca4c84)
libc++abi.dylib: terminating with uncaught exception of type NSException

Wechat.share({
		    message: {
		        title: "Hi, there",
		        description: "This is description.",
		        thumb: "www/img/thumbnail.png",
		        mediaTagName: "TEST-TAG-001",
		        messageExt: "这是第三方带的测试字段",
		        messageAction: "<action>dotalist</action>",
		        media: "YOUR_MEDIA_OBJECT_HERE"
		    },
		    scene: Wechat.Scene.TIMELINE   // share to Timeline
		}, function () {
		    alert("Success");
		}, function (reason) {
		    alert("Failed: " + reason);
		});

**Comment by xu-li** [comment]
Have you changed **YOUR_MEDIA_OBJECT_HERE**?

You may also try the [Demo app](https://github.com/xu-li/cordova-plugin-wechat-example/tree/master/ionic).

**Comment by jianbo** [comment]
Works now : )
