### ISSUE TITLE
请问使用个人微信开发者账号申请的 app Id，能分享成功吗？

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-li/cordova-plugin-wechat#70]
引用了这个包，然后填入个人开发者账号的 appid，还能分享成功吗？

**Comment by xu-li** [comment]
@Jeff-Tian 什么叫*引用了这个包*? 你的意思是安装了这个插件？

**Comment by Jeff-Tian** [comment]
@xu-li ，我在我的 Ionic 项目中用 

```
cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID
```

安装了这个插件，但是  YOUR_WECHAT_APPID 是用个人开发者账号申请的 appid，还能使用分享功能吗？因为在微信的接口管理处显示，个人开发者账号是没有调用分享接口的权限的。

**Comment by xu-li** [comment]
可以啊，我的demo就是用的个人账号申请的。


2015-09-05 10:49 GMT+08:00 Jeff <notifications@github.com>:

> @xu-li <https://github.com/xu-li> ，我在我的 Ionic 项目中用
>
> cordova plugin add https://github.com/xu-li/cordova-plugin-wechat --variable wechatappid=YOUR_WECHAT_APPID
>
> 安装了这个插件，但是 YOUR_WECHAT_APPID 是用个人开发者账号申请的
> appid，还能使用分享功能吗？因为在微信的接口管理处显示，个人开发者账号是没有调用分享接口的权限的。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xu-li/cordova-plugin-wechat/issues/70#issuecomment-137896299>
> .
>



-- 
Thanks.
--
Xu Li,  Shanghai, China
