### ISSUE TITLE
Cloning into '\git\1441610337771'... fatal: unable to access 'https://github.com/xu-li/cordova-plugin-wechat/': Empty  reply from server

### ISSUE THREAD

**Issue by prp632791853** [xu-li/cordova-plugin-wechat#71]
大神这个是什么原因，提示无法访问。fatal: unable to access 'https://github.com/xu-li/cordova-plugin-wechat/': Empty  reply from server

**Comment by xu-li** [comment]
@prp632791853 可能是你网络的原因吧？

**Comment by prp632791853** [comment]
谢谢，刚才试了一下可以了。因为之前我用浏览器可以打开，所以就很奇怪为什么git不能访问呢。
