### ISSUE TITLE
分享完毕后，可否选择留在微信？

### ISSUE THREAD

**Issue by wukongcxy** [xu-li/cordova-plugin-wechat#72]
分享完毕后，可否选择留在微信，或者是返回app

**Comment by xu-li** [comment]
这是微信的内置功能，自动带的。

**Comment by wukongcxy** [comment]
请问那为什么我的分享成功了，直接跳回app，没有显示选择的的弹窗？是在调用的时候需要设置一下吗？

**Comment by xu-li** [comment]
没有设置的地方，我记得iOS和Android，一个会弹选项，一个会自动回到APP。

**Comment by wukongcxy** [comment]
也就是说，如何返回没有接口控制，是被微信写死的？

**Comment by xu-li** [comment]
是的。
