### ISSUE TITLE
无法在iOS9中使用

### ISSUE THREAD

**Issue by Zhangjianzy** [xu-li/cordova-plugin-wechat#73]
Wechat.isInstalled方法在iOS9中返回false，确认微信已安装

**Comment by Huikit** [comment]
我也是 之前在ios8 还可以的 但是今天升级到 ios9 就无法 build了

**Comment by Zhangjianzy** [comment]
https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1442386606&version=11&lang=zh_CN&token= <https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1442386606&version=11&lang=zh_CN&token=>
看了下需要加，iOS9的新策略
<key>LSApplicationQueriesSchemes</key>
<array>
 <string>weixin</string>
 <string>wechat</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
 <key>NSAllowsArbitraryLoads</key>
<true/>
</dict>

**Comment by Huikit** [comment]
我的错误提示是 error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Zhangjianzy** [comment]
经过这两个修改后，微信登录出现了，一直用你开发的这个插件，还未请教你的称呼呢。我是张舰H5开发工程师，目前在一创业团队
发自我的 iPhone

**Comment by Huikit** [comment]
http://www.cocoachina.com/ios/20150703/12392.html 这里有参考资料 http 也做了显示 我的问题出在bitcode 设置

**Comment by xu-li** [comment]
多谢，我更新了一下plugin.xml，现在应该没问题了。

@Zhangjianzy 我是做PHP开发的，偶尔自己弄点App的东西。
