### ISSUE TITLE
Wechat.auth not working

### ISSUE THREAD

**Issue by davidxie** [xu-li/cordova-plugin-wechat#74]
All shares, install check functions work except Wechat Authentication.
After calling Wechat.auth function, my app switches comes a screen saying sorry, oops! something went wrong:(.

**Comment by xu-li** [comment]
You have to submit your app for review.

**Comment by davidxie** [comment]
Thanks,

You have to submit your app for review.

—
Reply to this email directly or view it on GitHub
<https://github.com/xu-li/cordova-plugin-wechat/issues/74#issuecomment-142226247>
.
