### ISSUE TITLE
ionic build android 发出警告,分享时候弹出未知错误

### ISSUE THREAD

**Issue by duchao1990** [xu-li/cordova-plugin-wechat#75]
Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.openapi.WXApiImplV10$ActivityLifecycleCb$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.mm.sdk.b.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

**Comment by xu-li** [comment]
警告都是微信SDK的代码，可以忽略。

分享的时候报的错误是什么？LogCat里面有什么？

**Comment by duchao1990** [comment]
安装上之后有这样提示,我没操作
Running android-install.Hook: after_plugin_install, Package: com.xxxx.xxxx, Path: D:\wamp\www\appc.
就是已经弹出微信页面但是闪退回来了,alert对话框显示失败,未知错误

**Comment by xu-li** [comment]
那很可能是你的微信APP ID或者签名没设置对。看[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。

**Comment by duchao1990** [comment]
非常感谢,在您的提醒下,我修改了,签名格式,2C:F7:B2:FC:F5:61:F4:F3:85:FB:30:C5:0D:88:73:6C这是我之前填写的签名.后来改成2cf7b2fcf561f4f385fb30c50d88736c,格式才行,谢谢

**Comment by iyibo** [comment]
嗯  是的 签名错误，非常感谢！
