### ISSUE TITLE
跳转回应用之后没有返回值

### ISSUE THREAD

**Issue by xingwanying** [xu-li/cordova-plugin-wechat#76]
你好，关于sso登录的调用
 var scope = "snsapi_userinfo";
Wechat.auth(scope, function (response) {
    alert(JSON.stringify(response));
}, function (reason) {
    alert("Failed: " + reason);
});
能够授权并从wechat客户端返回到我的应用，但是fuction里面的代码都没有执行，没有得到token和userid
也没有任何报错

**Comment by xu-li** [comment]
iOS还是Android？插件的版本是什么？function里面的代码都没有执行的话，试试用alert(123);替代alert(JSON.stringify(response));呢？

**Comment by Huikit** [comment]
iOS 有 但是 android 没有

**Comment by xingwanying** [comment]
是iOS，Cordova 5.1.1，function里面替换成alert或者console都没有执行，分享的功能是正常的，唯独登陆不行

**Comment by xu-li** [comment]
@xingwanying 还有这个问题么？我重现不了。如果方便的话，能否共享你的app信息？

**Comment by userrcs** [comment]
@xu-li 首先感谢你的无私,给予了我们很多的帮助。  
我也遇到@xingwanying一样的问题 是调用了
var scope = "snsapi_userinfo";
Wechat.auth(scope, function (response) {
alert(JSON.stringify(response));
}, function (reason) {
alert("Failed: " + reason);
});  
在EntryActivity 没有执行 微信客户端也没有被拉起
我测试发现 如果微信账号没有登陆 微信客户端会被拉起 否则执行改方法后没有任何效果
我qq:547447184 我可以提供app给你重现

**Comment by xu-li** [comment]
@userrcs 多谢，发我邮箱吧: AthenaLightenedMyPath@gmail.com。需要你的AppID，AppSecret，应用签名，应用包名，以及你的keystore的信息。

**Comment by userrcs** [comment]
@xu-li  经过我下午的仔细研究你的代码 发现不是插件的问题,插件非常完美,出现这种情况是由于微信开发平台的签名和app签名对不上,而微信没有任何提示 再次感谢@xu-li 大神的无私

**Comment by xu-li** [comment]
好的，多谢测试。
