### ISSUE TITLE
关于INSTALL的问题

### ISSUE THREAD

**Issue by koika2015** [xu-li/cordova-plugin-wechat#77]
INSTALL的第三点
3. (iOS only) if your cordova version <5.1.1,check the URL Type using XCode

请问我的cordova版本是4.1.2，在URL Type 需要怎样的修改？

现在我安装了0.8.0版本之后，Wechat 是 Undefined type，并没有初期化。。。

**Comment by xu-li** [comment]
这部应该会自动完成。可以看一下[这个图](https://res.wx.qq.com/open/zh_CN/htmledition/res/img/pic/app-access-guide/ios/image0042168b9.jpg)。

我觉得很可能你插件都没装对，URL Type没有设置，最多不能返回你的应用。
