### ISSUE TITLE
Wechat.isInstalled在iOS9失效了么？

### ISSUE THREAD

**Issue by RyC37** [xu-li/cordova-plugin-wechat#79]
安装了微信，但是没有检测到。
升级iOS9之前没有这个问题.
不知道是否兼容性的bug?

**Comment by RyC37** [comment]
补充：分享也报错 - 『未安装微信』
但是我安装了微信。

**Comment by xu-li** [comment]
什么版本的插件？最新的版本有修改关于iOS9的配置。看[这里](https://github.com/xu-li/cordova-plugin-wechat/commit/c4e6e8406d646a5b333b00fc8b3cc4dc5d9859a7).

(我发现我忘记加版本号了.)

**Comment by RyC37** [comment]
最新版本0.8.1 - 更新0.8.2还是不行
可能是我编译的问题？
之前老的开发环境 iOS8 + xcode6.3 + cordova 4.x编译之后发布线上版本，微信分享、安装检测是work的
现在iOS9.1 + xcode7.0 +cordova 5.3.3 编译之后，就只有登录可以使用。分享、安装检测都不work了。。
你知道怎么办么？

可以加我微信 luo9137

**Comment by RyC37** [comment]
具体报错是：点击『分享』-『未安装微信』
纳闷。。。

**Comment by RyC37** [comment]
我在info-plist里面添加这段代码之后，真机调试，bug解决了。（据说一定要上真机）
```html
<key>LSApplicationQueriesSchemes</key>
   <array>
      <string>weixin</string>
      <string>wechat</string>
   </array>
<key>NSAppTransportSecurity</key>
<dict>
   <key>NSAllowsArbitraryLoads</key>
   <true/>
</dict>
```

**Comment by xu-li** [comment]
奇怪，这个应该会自动加上啊。[c4e6e8406d646a5b333b00fc8b3cc4dc5d9859a7](https://github.com/xu-li/cordova-plugin-wechat/commit/c4e6e8406d646a5b333b00fc8b3cc4dc5d9859a7)的改动就是解决这个问题的。
