### ISSUE TITLE
Can I share a webpage with a remote image url

### ISSUE THREAD

**Issue by jianbo** [xu-li/cordova-plugin-wechat#8]
With following code I can only share webpage url and and title, is there a way I can share a remote image url along the webpage? 

Wechat.share({
					    message: {
					        title: $scope.message,
					        description: $scope.message,
					        media: {
						            type: Wechat.Type.LINK,
						            webpageUrl: $scope.url
						        }
					    },
					    scene: Wechat.Scene.TIMELINE   // share to Timeline
					}, function () {
					    alert("Success");
					}, function (reason) {
					    alert("Failed: " + reason);
					});

**Comment by xu-li** [comment]
Are you referring to _thumb_?

Try this(not tested):
```javascript
Wechat.share({
    message: {
        title: $scope.message,
        description: $scope.message,
        thumb: "http://dev.wechat.com/static/en_US/app2/img/banner/banner_wechat-api.jpg",
        media: {
            type: Wechat.Type.LINK,
            webpageUrl: $scope.url
        }
    },
    scene: Wechat.Scene.TIMELINE // share to Timeline
}, function () {
    alert("Success");
}, function (reason) {
    alert("Failed: " + reason);
});

**Comment by jianbo** [comment]
Works great :)
