### ISSUE TITLE
wechat ios9 error

### ISSUE THREAD

**Issue by AaronChen118** [xu-li/cordova-plugin-wechat#80]
非常感谢这个plugin，ios9之前一直没有问题，但是现在分享似乎不能work了。我看了xcode的error message显示：
canOpenURL: failed for URL: "weixin://app/XXXXXXXXXX/" - error: "This app is not allowed to query for scheme weixin"

我search了下，网上说哟在info.plist里加入
<key>LSApplicationQueriesSchemes</key>

<array>

<string>urlscheme</string>

<string>urlscheme2</string>

<string>urlscheme3</string>

<string>urlscheme4</string>

</array>

但是我的info.plist已经加了：
			<key>LSApplicationQueriesSchemes</key>
			<array>
				<string>weixin</string>
				<string>wechat</string>
			</array>
			<key>NSAppTransportSecurity</key>
			<dict>
				<key>NSAllowsArbitraryLoads</key>
				<true/>
			</dict>

**Comment by RyC37** [comment]
我遇到了一样的问题。
但是之前build的版本在iOS9里面是work的。
我觉得也许是开发环境的问题。
具体看我的issue - https://github.com/xu-li/cordova-plugin-wechat/issues/79
2015-10-02 16:08:50.818 MyProject[1601:590975] -canOpenURL: failed for URL: "weixin://app/xxxxxx/" - error: "This app is not allowed to query for scheme weixin"
2015-10-02 16:08:58.837 MyProject[1601:590975] THREAD WARNING: ['Wechat'] took '8050.069092' ms. Plugin should use a background thread.

**Comment by RyC37** [comment]
我在info-plist里面添加这段代码之后，bug解决了。
<key>LSApplicationQueriesSchemes</key>
    <array>
      <string>weixin</string>
      <string>wechat</string>
    </array>
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
