### ISSUE TITLE
Wechat share for android can't work

### ISSUE THREAD

**Issue by goneaway1981** [xu-li/cordova-plugin-wechat#81]
你好，最新版的插件在进行安卓分享时貌似不能正常调用了。
判断是否安装了微信是可以使用的，如果微信没有登录也可以调出微信，提示登录，但就是分享动作时不可用。

包括使用你的example，加入最新wechat插件都不可以。

麻烦您给看一下。不知道是我使用的问题还是其他问题。以前是可以正常使用的。

**Comment by goneaway1981** [comment]
你好，能不能问一下现在是问题没有复现还是说只是没有时间来看这个问题？
如果是你那边测试了OK的，那我就再在本地找问题，如果不是，那可能我就需要另想办法了。
谢谢。

**Comment by xu-li** [comment]
不好意思，最近比较忙。还没有时间去测试。

基本上，应该是签名的问题。

**Comment by goneaway1981** [comment]
你好，我估计问题也不会很大，所以还麻烦你能不能抽点时间解决一下这个问题。我们这边初创团队，几个人，都没搞过安卓和ios，用的h5，所以自己调试起来还是有困难的。原计划本周末能够出版本呢，结果现在就被这一个主要问题卡住了。不胜感谢。

**Comment by xu-li** [comment]
不好意思，没想到那么急。

刚才抽空看了一下，测试了几个版本，都没有问题。可能是你这边安装上的问题。

1. 你这边的签名是怎么弄的？
2. 测试我的example的时候，你用的app id是哪个？
3. 如果方便的话，把你们的代码给我，我帮你调试一下？

**Comment by goneaway1981** [comment]
你这边有方便的联系方式吗？qq或微信什么的，我们好沟通。我现在直接用你的example，然后cordova plugin add 你的插件 --加我的appid都不可以。以前是可以的。现在在苹果OK，在安卓有问题，可以看到闪一下就退出了。

**Comment by goneaway1981** [comment]
有邮箱也可以，我把我建的你的例子的工程发给你，麻烦你帮忙看一下

**Comment by xu-li** [comment]
应该用我的appid，因为是我注册的，appid，签名和package id是对应的，在申请的时候提交。

**Comment by goneaway1981** [comment]
那如果要用我自己的呢？需要修改哪里？所有人用这个控件都用你的合适吗？会有安全隐患吗？

**Comment by xu-li** [comment]
当然可以用自己的。

1. appid，这个是微信给你的。
2. package id，这个是你自己定义的。比如我的example里面叫xu.li.test.cordova.plugin.wechat.
3. 签名，根据你打包android应用的key和package id生成。看[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318060&token=&lang=zh_CN)。

然后你的微信申请页面，要按照这个来填。
