### ISSUE TITLE
怎么可以调试呢？

### ISSUE THREAD

**Issue by xhrwp** [xu-li/cordova-plugin-wechat#83]
各位大神，初学cordova，不知道如何是永cordova来调试程序，我现在做分享，打开微信的时候微信直接闪退了，不知道什么原因。

**Comment by xu-li** [comment]
iOS还是Android? 简单的调试就是看日志，比如Android的LogCat。复杂点的就用官方推荐的IDE，比如Android的Android Studio，iOS的XCode。
