### ISSUE TITLE
按照readme文档操作微信直接闪退

### ISSUE THREAD

**Issue by xhrwp** [xu-li/cordova-plugin-wechat#84]
hi  我用xdk开放html5的应用时，使用该插件做微信分享的功能，出现微信闪退效果，分享不成功。操作步骤是安装readme中来做的。

**Comment by xu-li** [comment]
是iOS还是android？有没有错误提示？

**Comment by goneaway1981** [comment]
我和他似乎是同样的问题。IOS是OK的。Android会闪一下就退出了，没有错误提示。但判断微信是否安装是可以正常判断的，包括调用微信，提示登录也是可以的，但登录后就没有继续执行分享动作了。

**Comment by xhrwp** [comment]
appid我是设置正确了的，应该是没有问题。我使用的是xdk开放工具加入的插件 不是使用命令行的方式，是否与这个有关系

**Comment by xu-li** [comment]
是iOS还是android？你还没回答我。Android的话，可以参考一下我在#81最后的评论。

不用命令行添加的话，hook里面的很多东西可能没执行，比如android里面的类包名字的替换。可以看[这里](https://github.com/xu-li/cordova-plugin-wechat/blob/develop/scripts/android-install.js)。

**Comment by yiyou609** [comment]
我的也是这个样子，将微信卸载，安装早期版本，可以正常分享，6.2的出现楼主所描述的闪退问题。

**Comment by xu-li** [comment]
测试了一下，6.2和最新的6.3.5都没有问题。
