### ISSUE TITLE
invalid appKey

### ISSUE THREAD

**Issue by xhrwp** [xu-li/cordova-plugin-wechat#87]
你好！我想请问下，我通过eclipse连接手机测试的时候，微信返回{ret:-1,msg:invalid appKey}。
我的appid是正确的，这个可以肯定。但是我的开发者账号是没有认证的。请问是不是因为没有认证的造成的错误呢？

**Comment by ryanlin1986** [comment]
调试模式用的是自动生成的签名，所以可能是签名的问题， 用release模式， 把你的release签名绑定到微信app
