### ISSUE TITLE
有计划加入微信登录么？

### ISSUE THREAD

**Issue by mkliu** [xu-li/cordova-plugin-wechat#9]
我正准备写一个，看到你这个plugin

**Comment by xu-li** [comment]
最近会加上，只是现在没有审核过的APP，所以可能测试比较麻烦。

**Comment by mkliu** [comment]
我有通过审核的，纯android版我测试过了，正准备port到cordova plugin。不过我要先学习下plugin怎么写。

**Comment by xu-li** [comment]
没关系，我找了官方SDK Example的APP_ID，微信认证已经加入到iOS。

如果你有兴趣，可以把android版本的发过来，我merge进去。
