### ISSUE TITLE
微信支付 - 无法跳转到微信

### ISSUE THREAD

**Issue by cao262** [xu-li/cordova-plugin-wechat#96]
Cordova: 5.1.1
Device: Iphone 6 plus ios 8.3

安装好第一次运行是好的，在该次应用打开时，重复跳转微信支付页没问题。
杀掉应用后，再进去，就跳不到微信了，重启机器后，才可以。

是否会存在某些资源释放的问题呢？

**Comment by cao262** [comment]
有些时候，会自动释放，过段时间再开就自动恢复正常，有些时候过半个小时打开还是老样子。

**Comment by xu-li** [comment]
日志里面什么信息？能固定重现么？

**Comment by cao262** [comment]
可以固定重现，由于没有mac环境，所以不能debug，准备搭一个，有任何进展再联系您把。
如果方便，你也可以看看是否的确存在这个问题。

**Comment by cao262** [comment]
sorry，是这边js的代码影响到了插件的加载，不是插件本身的问题，关掉了。
