### ISSUE TITLE
android libammsdk.jar 版本太低，百度开发者平台禁用

### ISSUE THREAD

**Issue by xuender** [xu-li/cordova-plugin-wechat#99]
百度开发者平台提示libammsdk.jar中包含财付通网银支付sdk，被禁用，最新版本的libammsdk.jar则可以通过

**Comment by xu-li** [comment]
没发现最新版的啊。[这里](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN)的SDK就是我用的。

**Comment by mjbin** [comment]
大神，我用你的demo的代码，然后用的自己的appid和签名，能够正常识别到微信是否安装，但是发送文本就会返回错误，微信授权登陆点击了就没反应。。在没登陆微信的情况下，点击授权登陆是可以调出微信的登陆界面的。可以确认id和签名没问题。

**Comment by xu-li** [comment]
错误是什么？iOS还是android？

另外，你的问题跟这个issue好像没关系，最好重新开个issue。

**Comment by cxcxcxcx** [comment]
百度确实拒绝这个版本的 sdk。不知哪里有“单独的sdk”。或许可以试着把 jar 包里跟支付有关的文件去掉？

来自百度的信件：
 失败原因：1. 您的软件被扫描出含有财付通网银支付sdk，暂不收录个人开发者提交的带支付功能的应用，若您未嵌入支付sdk，请确认是否使用集成性sdk，若有使用请去除集成性sdk，使用单独的sdk后重新提交或请认证为公司开发者，感谢配合！ 请登录开发者平台查询应用状态。 谢谢您的支持。

**Comment by xu-li** [comment]
我觉得最好去问百度或者微信官方，有什么办法解决。

**Comment by gdamao** [comment]
为什么 andorid5.1 的运行这个插件一直没反应，android 4的没问题

**Comment by gdamao** [comment]
测试了一下 用ionic build android后  android-debug-unaligned 可以运行  但是 android-release签名后就一直没反应

**Comment by gdamao** [comment]
但是android 4.0的 android-release签名后可以运行

**Comment by xu-li** [comment]
@gdamao 能不能新开一个issue？你的问题好像和当前的issue没关系。

**Comment by buhe** [comment]
release 和 debug的apk 签名不同 @gdamao

**Comment by buhe** [comment]
百度这个问题 大家有好的解决办法嘛
